### ISSUE TITLE
Multiple serious errors in JSON Data causing exception and ambiguity in processing

### ISSUE THREAD

**Issue by barocsi** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#133]
So this is something that needs to be fixed asap. 
Codebase is identical, but the result is different on Android and on iOS.
Thre are multiple errors here.

Both tests same values using below for Facebook
```javascript
 contentMetadata: {
                         '$state': "main.tabs.single",
                         '$stateParams': {"postId": post.id},
                         something_else:{test:'bar'},
                         '$og_app_id': bt_const.fbAPPId
                       }
```
### Result in dashboard
```json
{
  "$og_app_id": "1757534501136057",
  "$stateParams": "{\\\"postId\\\":\\\"571c1d4ba5800ace7c9e4558\\\"}",
  "~creation_source": 2,
  "$og_title": "Is our president evil? Yes or No ?",
  "~tags": [],
  "$content_type": "",
  "~channel": "Facebook",
  "$state": "main.tabs.single",
  "source": "android",
  "$og_image_url": "https://api.grademill.com/api/localstorages/shared_2016-4-28/download/dc3d559a-df92-4551-b5f6-f8fab69ccf13.jpg",
  "$og_description": "This is a question, shared by @barocsi! Click and answer on Grademill asap, the real-time decision making app!",
  "$one_time_use": false,
  "$identity_id": "253230631314557549",
  "something_else": "{\\\"test\\\":\\\"bar\\\"}",
  "$canonical_identifier": "571c1d4ba5800ace7c9e4558_1461840113431",
  "$exp_date": "0",
  "~feature": "share",
  "$keywords": [],
  "~id": "254182727471912546",
  "+url": "bnc.lt/F5kk/iJsxzC3jWs",
  "$canonical_url": ""
}
```

### Result in dashboard:
```json
{
  "$og_app_id": "1757534501136057",
  "$stateParams": {"postId": "571c1d4ba5800ace7c9e4558"},
  "~creation_source": 3,
  "$og_title": "Is our president evil? Yes or No ?",
  "~channel": "facebook",
  "~feature": "share",
  "$state": "main.tabs.single",
  "$og_description": "This is a question, shared by @barocsi! Click and answer on Grademill asap, the real-time decision making app!",
  "~stage": "my_post",
  "$one_time_use": false,
  "$identity_id": "253230631314557549",
  "something_else": {"test": "bar"},
  "$canonical_identifier": "571c1d4ba5800ace7c9e4558_1461840337208",
  "$exp_date": 0,
  "$og_image_url": "https://api.grademill.com/api/localstorages/shared_2016-4-28/download/d7336874-06e6-4cbe-8082-547c696c7bcf.jpg",
  "$publicly_indexable": 1,
  "~id": "254183698788828614",
  "+url": "bnc.lt/F5kk/mTfaOIkkWs"
}
```
## Problems:

1. ~channel names are different. This is not good if later one wants to combine statistics.
2. Double escaping causes exception when processing link metadata generated by Android
3. Stage parameter is still missing from Android generated link as stated to be resolved in https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/122 but apparently not (probably I am using a wrong version 2.0.12.

Please fix, I wonder other clients never bump into these.

**Comment by renesansz** [comment]
Hmm, not sure if this is the plugin's current issue or with the SDK?
Need confirmation from @aaustin & @jestoniyap .

**Comment by aaustin** [comment]
Hey @barocsi - we'll look into the capitalization and escaping issue on the core SDK. @renesansz - can you look into the missing stage parameter from Android? I thought I fixed it in my last PR.

**Comment by barocsi** [comment]
Meanwhile this workaround did the trick 
```javascript
      if (typeof payload.$stateParams == 'string') {
        var __unescaped = payload.$stateParams.replace(/\"/g, "\"");
        payload.$stateParams = JSON.parse(__unescaped);
      }
```

**Comment by barocsi** [comment]
Meanwhile this workaround did the trick 
```javascript
      if (typeof payload.$stateParams == 'string') {
        var __unescaped = payload.$stateParams.replace(/\\/g, "");
        payload.$stateParams = JSON.parse(__unescaped);
      }
```

**Comment by renesansz** [comment]
@aaustin , `stage` parameter is present for Android. Not sure if this was the cause of the issue.
@barocsi , may I know where have you implemented your workaround in the plugin?

**Comment by renesansz** [comment]
@barocsi , need follow up if this is resolved now? thanks

**Comment by barocsi** [comment]
Hello, I had my workaround implemented (conditionally examining the JSON structure) so I am not sure, yet have no time to re-check any soon. I guess we can close this though.

**Comment by renesansz** [comment]
@barocsi 
cool, just let me know if you're still having problem with this ticket so that I can re-open it again.
Thanks!

**Comment by computerjazz** [comment]
This is still an issue on android, Branch-2.12.0

**Comment by ethanneff** [comment]
Hello @computerjazz, 

Before I revive this issue, can you please elaborate on the steps you are doing to replicate the issue? When testing, I am seeing the same deep link being parsed correctly by both Android and iOS when using Branch Cordova SDK `2.6.12`.
<img width="1358" alt="screen shot 2017-09-07 at 9 11 18 am" src="https://user-images.githubusercontent.com/2933593/30173615-20ea963e-93ad-11e7-8e5f-8a75e344fe14.png">

Thanks,

**Comment by computerjazz** [comment]
Whoops, wrong repo -- I'm on React Native. Will report the issue there.
Thanks!
