### ISSUE TITLE
Facebook og data does not work when $fallback_url is used

### ISSUE THREAD

**Issue by zanemcca** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#146]
It appears that Facebook will try to get the og data from the fallback_url and not from the branch link.

**Comment by aaustin** [comment]
Interesting. I just saw this in our code too. If you use $desktop_url, $ios_url and $android_url, your OG tags will be respected. I hesitate to change this now since it's been live for about 7 months. Sorry for the surprise @zanemcca !

**Comment by zanemcca** [comment]
Yeah that is the workaround I started using.

**Comment by aaustin** [comment]
Sorry about the confusion 👎

**Comment by zanemcca** [comment]
Thats alright. It would be nice if this info was available in the documentation as well.

**Comment by aaustin** [comment]
Got it on my todos
