### ISSUE TITLE
initSession while offline causes js exception on android

### ISSUE THREAD

**Issue by Morathil** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#147]
When we are calling `initSession` while the device (android) is offline we are getting the following error in `cordova.js:1070#processMessage`: `Uncaught SyntaxError: missing ) after argument list`

I had a look into this issue and found out that the js exception is thrown while trying to: `eval("NonBranchLinkHandler(Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.)")`
This string is built in `BranchSDK.java:716` with: `String.format("NonBranchLinkHandler(%s)", error.toString());`. To be able to `eval` this string in js it is required to replace `%s` with `\"%s\"`.

But even with this little fix, it is required to implement `NonBranchLinkHandler` function else a `NonBranchLinkHandler is not defined` error is thrown.

As i am not even sure why the error string is sent to javascript on line 717 and as i guess that it should not be required to implement `NonBranchLinkHandler` I want to ask you to have a look into this issue please :)

PS: easiest fix for our purpose is to just remove `BranchSDK.java:716/717` where the error string is sent to javascript

**Comment by renesansz** [comment]
Hey @Morathil ,
Thanks for the findings and solutions, I'll look into the error and submit a PR for the fix. 👍

**Comment by renesansz** [comment]
@Morathil ,
I've just submitted PR #148 , Hopefully this would resolve the issue.
Let me know if this fixes your problem. 👍

**Comment by aaustin** [comment]
Merged! I'll deploy to NPM with a version bump after a couple more PRs.

**Comment by Morathil** [comment]
@renesansz thanks! This fixed our issue! 👍

**Comment by renesansz** [comment]
@Morathil ,
No prob, I'm glad to hear that it fixes the issue. 👌
