### ISSUE TITLE
DeepLinkHandler with ionic route

### ISSUE THREAD

**Issue by ddalmia** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#152]
Hi,

I have a cordova ionic application which is using branch sdk for deeplink. What happens is when we click on a deeplink url, ionic route url gets fired first and then the deeplink url is opened. Ionic route and DeepLinkHandler are working in independent manner. 

Is there a way to sync both of them i.e. ionic route and DeepLinkHandler. When app is opened only ionic router url should be fired and when we try to open a deeplink url that should be the link opening instead of ionic route url getting opened first.

Any help would be appreciated.

Regards,
Deepak.

**Comment by renesansz** [comment]
Hey @ddalmia ,
I'll take a look at this problem, and give you a response to my findings.
So far we've assumed that the plugin should work well with any Cordova frameworks.

**Comment by renesansz** [comment]
@ddalmia , I'm trying to replicate the issue but somehow I can't reproduce on what you are trying to meant.
Currently, Ionic should be able to determine an external url from the app route. Have you tried to look on the whitelisting for Cordova? Maybe the url is blocked somehow. [[link](http://docs.ionic.io/docs/cordova-whitelist)]

**Comment by ddalmia** [comment]
Thanks for your response. The white list plugin is already added. The problem is that DeepLinkHandler fires after ionic route has redirected to the url specified in the route.

**Comment by aaustin** [comment]
Hey @ddalmia - This is the first we're hearing about this overlap in functionality. I appreciate you alerting us to it. Is it possible that you use the URL being passed to Ionic route to determine whether it's actionable or not? For example, if it's a Branch link, ignore routing in the Ionic routing and wait for the handler to be called.

Let me know your thoughts!

**Comment by ddalmia** [comment]
I had already implemented a wait handler in my code which does wait action for both ionic route and DeepLinkHandler. I wanted to know if there can be a more proper solution to this.

**Comment by aaustin** [comment]
Hey @ddalmia - Not at first glance. But I'd like to learn more if you wouldn't mind sharing. The problem is that none of us have played around with Ionic much.

A few questions:
- Is this the router you're referring to? https://www.thepolyglotdeveloper.com/2014/11/using-ui-router-navigate-ionicframework/
- Can you give an example of a URL that is causing the router to trigger in addition to DeepLinkHandler? Is it all URLs?

Maybe I can come up with a quick solution if I have more info.

**Comment by ddalmia** [comment]
Hi @aaustin,
The sample code which I have implemented is given below. In this code, I always open the load screen whether app is opened directly or from a deep link path. I have put a default wait time of 4 seconds. If app opened directly it waits for the given seconds and then redirected to home page. If app is opened from a deeplink path then from load screen, it is redirected to the desired page.

var MyController = angular.module('MyController',['ionic']);
var MyApp = angular.module('MyApp', ['ionic', 'MyController']);
MyApp.config(function ($stateProvider, $urlRouterProvider ) {
    $stateProvider
      .state('homepage',
        {
            url: "/homepage",
            templateUrl: "views/homepage.html",
            controller: 'homepagectrl',
        })
      .state('loadscreen',
        {
            url: "/loadscreen",
            templateUrl: "views/loadscreen.html",
            controller: 'loadscreenctrl',
        })

	    $urlRouterProvider.otherwise(function(){
	        return '/loadscreen';
	    });
})

function DeepLinkHandler(data) {
	localStorage.setItem("linkpath", data.deeplink_path);
}
MyController.controller('loadscreenctrl', function ($scope,$location,$interval) {
    var waitTimeSeconds = 4;
    var intervalMilliSeconds = 300;
    var waitMilliSeconds = waitTimeSeconds * 1000;
    var milliSecondsElapsed = intervalMilliSeconds;
    var stopTime = $interval(function () {
        var linkPath = "";
        linkPath = localStorage.getItem("linkpath");
        if (milliSecondsElapsed == waitMilliSeconds && linkPath == ""){
            $interval.cancel(stopTime);
            $location.path('/homepage');
        }
        if(linkPath != ""){
			$location.path(linkPath);
			localStorage.setItem("linkpath", "");
            $interval.cancel(stopTime);
        }
        milliSecondsElapsed =milliSecondsElapsed + intervalMilliSeconds;
    }, intervalMilliSeconds);
})

Waiting for your response.

**Comment by aaustin** [comment]
Hey @ddalmia. Thanks so much for the code.

What about if you just redirect to the load screen 100% of the time. Then, when DeepLinkHandler is called, you can redirect on top of the home screen, or pop up a modal with the destination URL.

**Comment by renesansz** [comment]
Hello @ddalmia ,
Just wanted to know if Alex's solution works for you? Does this issue still persist?

**Comment by ddalmia** [comment]
A solution similar, as suggested by Alex is already implemented and working.

**Comment by renesansz** [comment]
I see, thanks for the response.
I'll close the ticket now.
