### ISSUE TITLE
Can't build Android again

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#159]
I swear, this is like a monthly thing where my builds will just spontaneously stop failing because of this plugin.  

My Android builds are failing.  I locked the plugin version to be 2.0.9 from npm and am getting this error.  I'm building via the Phonegap command line version 6.0.  Up until like last week, this was working fine.:

Build Date: 2016-06-21 19:38:06 +0000

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.crashlytics.sdk.android:answers-shim:0.0.3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/android-sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/android-sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/android-sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/android-sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
     Required by:
         :project:unspecified > io.branch.sdk.android:library:1.14.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.406 secs
undefined

**Comment by aaustin** [comment]
Hey man - Really sorry about this... We're working on a partnership with Fabric that we're announcing tomorrow and it looks like we made a mistake that `jcenter` was used universally. We're about to deploy a fix for this where we host this dependency on maven. Just to get you unblocked, let me deploy a fix to NPM where we use the last version of the Android SDK. Working on this now.

**Comment by aaustin** [comment]
Hey Geoff - I just deployed 2.1.3 to NPM now. Would you mind giving this a try? It should downlevel the Android SDK and remove that Fabric dependency.

**Comment by gabaum10** [comment]
Ok, that fixed android, but it seems iOS is failing now.  

CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.o VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /tmp/gimlet/1050751/project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/s_/vmsnhgb97td15v6r7bbh0dtr0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/tmp/gimlet/1050751/project/build/include -I/tmp/gimlet/1050751/project/build/usr/local/lib/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/iphoneos/include -I/tmp/gimlet/1050751/project/build -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/tmp/gimlet/1050751/project/build -include /var/folders/s_/vmsnhgb97td15v6r7bbh0dtr0000gp/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-foiucwpemtokhrfletahvkaudsmh/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.d --serialize-diagnostics /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.dia -c /tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m -o /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.o
/tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m:13:9: fatal error: '../Fabric/Fabric+FABKits.h' file not found
#import "../Fabric/Fabric+FABKits.h"
        ^
1 error generated.

CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCServerInterface.o VeociDEV/Plugins/io.branch.sdk/BNCServerInterface.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /tmp/gimlet/1050751/project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/s_/vmsnhgb97td15v6r7bbh0dtr0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/tmp/gimlet/1050751/project/build/include -I/tmp/gimlet/1050751/project/build/usr/local/lib/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/iphoneos/include -I/tmp/gimlet/1050751/project/build -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/tmp/gimlet/1050751/project/build -include /var/folders/s_/vmsnhgb97td15v6r7bbh0dtr0000gp/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-foiucwpemtokhrfletahvkaudsmh/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCServerInterface.d --serialize-diagnostics /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCServerInterface.dia -c /tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BNCServerInterface.m -o /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCServerInterface.o
/tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BNCServerInterface.m:14:9: fatal error: 'BNCDeviceInfo.h' file not found
#import "BNCDeviceInfo.h"

**Comment by aaustin** [comment]
Hmm - the `BNCDeviceInfo.h` was left out but `Fabric+FABKits.h` is definitely in there. Sorry. NPM has strange import requirements since we can't use the framework. Try the latest? You might need to uninstall/re-add.

**Comment by gabaum10** [comment]
Would it be easier for everyone if I just wait a day or two for the new production ready version to release?

**Comment by aaustin** [comment]
Yes - we're going to deploy a hotfix to Android this afternoon.

**Comment by gabaum10** [comment]
Ok, I can do that.  Will it address the iOS issues as well? 

For reference, the most recent change is still throwing the Fabric error:
CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.o VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/59/lts8t4_d7yggqggtvh9l6plw0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/project/build -include /var/folders/59/lts8t4_d7yggqggtvh9l6plw0000gp/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-etxgboxrkptzrbbgwftlsgoxckng/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.d --serialize-diagnostics /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.dia -c /project/VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m -o /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BNCPreferenceHelper.o
/project/VeociDEV/Plugins/io.branch.sdk/BNCPreferenceHelper.m:13:9: fatal error: '../Fabric/Fabric+FABKits.h' file not found
#import "../Fabric/Fabric+FABKits.h"

**Comment by aaustin** [comment]
Hmm - I think you just need to remove and re-add. I just tested on a fresh project and it pulls that file in correctly and builds correctly. Or maybe, you can just copy the file directly into the plugin folder. https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/tree/master/src/ios/dependencies/Fabric

Super weird.

**Comment by gabaum10** [comment]
So here's the problem.  I'm building via Phonegap Build, and they are pulling in the dependencies there.  I just specify the link to the npm package and it does the rest.  I can't update manually unfortunately.  Something really strange is going on here.

**Comment by aaustin** [comment]
I reproduced. Hang on - let me sort it out.

**Comment by aaustin** [comment]
Ok - I figured it out. NPM adds all of the files in one folder, so the `../Fabric` path is no longer valid. I've just pushed an update.

**Comment by gabaum10** [comment]
Hey, sorry for the delayed response.  I was actually on vacation when this happened lol. But everything seems to be resolved now.  I didn't even have to change the npm version number.  

Thanks for this.
