### ISSUE TITLE
branchObj.setContentType(int) breaks build

### ISSUE THREAD

**Issue by peterholcomb** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#163]
See my comment here:  https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/da697373b6d6855517fd83eb0c3cd0ce0ab321f8

You are passing an int to setContentType which only accepts a string.  This won't compile.

**Comment by renesansz** [comment]
Hello @peterholcomb , Submitted PR #164 to fix this error.
Let me know if this will fix the issue. thanks 👌

**Comment by renesansz** [comment]
Issue has been resolved.
Closing ticket
