### ISSUE TITLE
No way to identify mixpanel id

### ISSUE THREAD

**Issue by lukemiles** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#166]
There is no clear way to instantiate the mixpanel id with the Cordova SDK as shown in these docs.

https://dev.branch.io/third-party-integrations/mixpanel/guide/#pass-mixpanel-distinct-id-recommended

**Comment by renesansz** [comment]
Hey @aaustin , just wanted to clarify if this is supported for the SDKs?

**Comment by aaustin** [comment]
Hey @lukemiles - Unfortunately we haven't rolled this out well to our non-native SDKs. In the meantime, if you want to unblock yourself, you'll need to do a client side transfer of data by calling the Mixpanel SDK directly from the Branch SDK callback. @derrickstaten do you have any other thoughts on this in the mean time?

@renesansz It'd be great to update both Android and iOS SDKs here, adding support for this call on iOS.

**Comment by lukemiles** [comment]
I have the mixpanel distinct ID, could you provide an example of how one would inform branch of it in JS? Or is this still totally unsupported?

**Comment by renesansz** [comment]
@aaustin , cool, I'll look in to the native SDKs on how to implement this one. thanks

**Comment by renesansz** [comment]
@aaustin , let me know if iOS call has been implemented. thanks!

**Comment by renesansz** [comment]
@lukemiles ,
Submitted PR #169 . Hopefully this would address the issue.
Let me know if this works.

**Comment by aaustin** [comment]
This has been merged in
