### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#168]
So this could very well be a configuration error on my end, but I'm getting this error running the cordova android builds: 

Error: Missing attribute value for attribute android:pathPrefix of element data
child_process.js:529
    throw err;
    ^

Error: Command failed: cordova build android --device --buildConfig ../devBuild.json --debug

As best I can tell, it's because there is a duplicate path or something? I tried deleting my old app off the branch dashboard and adding a new one using the same path.  Perhaps that screwed it up?  I have no idea how to fix it if that's it.   I thought as long as you had a different key, you could use the same paths?

**Comment by aaustin** [comment]
You were using this build command to add the SDK?
```cordova plugin add https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git --variable BRANCH_KEY=your-branch-key --variable URI_SCHEME=your-app-uri-scheme --variable``` 

And what is the current appearance of your <branch-config> tags in the config.xml?

**Comment by gabaum10** [comment]
I'm currently running installing via npm like so

`cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=branchKey --variable URI_SCHEME=uriScheme`

The tags in my config.xml look like this: 
`<branch-config>
        <ios-team-id value="5HRW738635" />
        <host name="xxxx.app.link" scheme="https" />
        <host name="xxxx-alternate.app.link" scheme="https" />
    </branch-config>`

where the xxxx's are our app prefix in the branch dashboard.  Am I missing something?

**Comment by gabaum10** [comment]
After updating the plugin installation to point to the git repo, this problem went away.  I guess it's just not deployed to npm?

**Comment by aaustin** [comment]
Thanks for the heads up on this @gabaum10 - I found the issue (actually multiple) and have confirmed that NPM is resolved now with 2.1.10. I'm not sure how we weren't alerted to this earlier.
