### ISSUE TITLE
Header files missing from plugin.xml

### ISSUE THREAD

**Issue by shahbazkhan054** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#170]
I think new commit again missed the two files from plugin.xml 

```
<header-file src="src/ios/dependencies/Branch-SDK/BranchView.h" />
<header-file src="src/ios/dependencies/Branch-SDK/BranchViewHandler.h" />
```

I am again getting error as branch/branch.h not found.
Please verify.

**Comment by renesansz** [comment]
@shahbazkhan054 , it's there but in comment. should I enable this?

**Comment by shahbazkhan054** [comment]
I am not sure but last time when I faces issue it got resolved after adding these two files.
The last issue was [issue#139](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/139)

**Comment by renesansz** [comment]
Hello @shahbazkhan054 ,
Submitted #171 to address this issue.
Let me know if this fixes the error.

**Comment by aaustin** [comment]
I've just tested the Github repo without adding these two files and it builds fine. What did you use to add the library to your project?

**Comment by shahbazkhan054** [comment]
I am using visual studio tools for apache cordova. I am also in contact with visual studio team for the issue. I am not getting why I am getting same error again n again as  `branch/branch.h not found`

**Comment by aaustin** [comment]
That error seems unrelated to the BranchView class stuff. Are you sure the framework is getting included in the build? https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/tree/master/src/ios/dependencies/Branch.framework

**Comment by itbeyond** [comment]
Getting same error - using 2.1.10 and Visual Studio remotebuild!

**Comment by renesansz** [comment]
Issue resolved. Closing ticket now.
