### ISSUE TITLE
Branch/Branch.h file not found

### ISSUE THREAD

**Issue by itbeyond** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#176]
Compiling for IOS via Visual Studio Branch V 2.1.10 getting this error:

```
CompileC build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/Objects-normal/i386/BranchSDK.o IT\ Travel/Plugins/io.branch.sdk/BranchSDK.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>             cd /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios
1>             export LANG=en_US.US-ASCII
1>             export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/david/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/ios-sim/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/david/Development/adt-bundle-mac-x86_64/sdk/tools:/Users/david/Development/adt-bundle-mac-x86_64/sdk/platform-tools:/Users/david/Development/apache-ant-1.9.3/bin"
1>             /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/1p/q33p4x115_9g_rxv56ps9myc0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/IT\ Travel-generated-files.hmap -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/IT\ Travel-own-target-headers.hmap -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/IT\ Travel-all-target-headers.hmap -iquote /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/IT\ Travel-project-headers.hmap -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/emulator/include -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/emulator/usr/local/lib/include -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/UninstalledProducts/include -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/emulator -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/DerivedSources/i386 -I/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/DerivedSources -F/Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/emulator -FIT\ Travel/Plugins/com.transistorsoft.cordova.background-geolocation -FIT\ Travel/Plugins/io.branch.sdk -include /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/sharedpch/IT\ Travel-Prefix-dfetpqrvjdkslahkeqinfdjbfbsm/IT\ Travel-Prefix.pch -MMD -MT dependencies -MF /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/Objects-normal/i386/BranchSDK.d --serialize-diagnostics /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/Objects-normal/i386/BranchSDK.dia -c /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/IT\ Travel/Plugins/io.branch.sdk/BranchSDK.m -o /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/build/IT\ Travel.build/Debug-iphonesimulator/IT\ Travel.build/Objects-normal/i386/BranchSDK.o
1>         In file included from /Users/david/.taco_home/remote-builds/taco-remote/builds/6333/cordovaApp/platforms/ios/IT Travel/Plugins/io.branch.sdk/BranchSDK.m:8:
1>         IT Travel/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
1>         #import <Branch/Branch.h>
1>                 ^
1>         1 error generated.
1>
1>         ** BUILD FAILED **
```

I have also adjusted the headers in the plugin.xml file and still getting this error as:

```
       <header-file src="src/ios/BranchSDK.h" />
        <source-file src="src/ios/BranchSDK.m" />
        <header-file src="src/ios/dependencies/Branch-SDK/BranchView.h" />
        <header-file src="src/ios/dependencies/Branch-SDK/BranchViewHandler.h" />      
        <source-file src="src/ios/AppDelegate+BranchSdk.m" />
```

My App name has a space in it but not sure if this is of relevance. It seems if I go to the MAC system and run a cordova build ios - with the header changes above it compiles, without these changes it does not but it never compiles under RemoteBuild.

**Comment by renesansz** [comment]
@itbeyond , I can't replicate the issue that you are having.
Does Visual Studio requires some additional adjustments to make when installing plugins? I only compile the app through CLI and never have tried building through Visual Studio.

**Comment by itbeyond** [comment]
No there is typically nothing needed but I did have to add the headers above to get it to compile from CLI. I wonder if the space char is an issue?

**Comment by renesansz** [comment]
I see, hmm.. I'm not sure with space character issue, but you can try removing the space character in your app name then let's see if that resolves the issue.

**Comment by aaustin** [comment]
Can you look through the project in visual studio to ensure it's properly importing all of the Branch files. I worry that the framework (`Branch.framework` in [this folder](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/tree/master/src/ios/dependencies)) is not getting included in the build. I believe there's another issue in the repo dealing with the same issue with Vis Studio.

**Comment by aaustin** [comment]
Oh that other issue is you also :)

**Comment by renesansz** [comment]
@itbeyond does still this issue occurs?

**Comment by pinaganti** [comment]
This issue still exists, and failed to build.

**Comment by itbeyond** [comment]
Yes this issue still exists - my work around has been to build  directly in my Mac platform outside of Visual Studio however I still had to setup the plugin.xml as follows:

```
        <config-file target="*-Info.plist" parent="CFBundleURLTypes">
            <array>
                <dict>
                    <key>CFBundleURLName</key>
                    <string>io.branch.sdk</string>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>$URI_SCHEME</string>
                    </array>
                </dict>
            </array>
        </config-file>
        <header-file src="src/ios/BranchSDK.h" />
        <source-file src="src/ios/BranchSDK.m" />
        <header-file src="src/ios/dependencies/Branch-SDK/BranchView.h" />
        <header-file src="src/ios/dependencies/Branch-SDK/BranchViewHandler.h" />      
        <source-file src="src/ios/AppDelegate+BranchSdk.m" />
        <!-- COMMENT if building for NPM -->
        <framework custom="true" src="src/ios/dependencies/Branch.framework" />
        <!-- UNCOMMENT if building for NPM -->
```

**Comment by mdonstad** [comment]
Im getting this error still. Any updates on what the issue with Visual Studio Cordova Tools is? The Branch.framework is getting included on the mac side to build and I still get this error. Here is my current config:

<platform name="ios">
        <config-file target="config.xml" parent="/*">
            <feature name="BranchSDK">
                <param name="ios-package" value="BranchSDK" />
            </feature>
        </config-file>
        <config-file target="*-Info.plist" parent="branch_key">
                <string>$BRANCH_KEY</string>
        </config-file>
        <config-file target="*-Info.plist" parent="CFBundleURLTypes">
            <array>
                <dict>
                    <key>CFBundleURLName</key>
                    <string>io.branch.sdk</string>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>$URI_SCHEME</string>
                    </array>
                </dict>
            </array>
        </config-file>
        <header-file src="src/ios/BranchNPM.h" />
        <header-file src="src/ios/BranchSDK.h" />
      <source-file src="src/ios/BranchSDK.m" />
      <source-file src="src/ios/AppDelegate+BranchSdk.m" />
      <framework custom="true" src="src/ios/dependencies/Branch.framework" />
      <header-file src="src/ios/dependencies/Branch-SDK/BranchView.h" />
      <header-file src="src/ios/dependencies/Branch-SDK/BranchViewHandler.h" />
     
    </platform>

**Comment by aaustin** [comment]
Hey @mdonstad - I'm sorry as I don't have VS set up over here so I'm grasping at straws. Is it possible that Visual Studio is putting it in an incorrect folder and it's having trouble referencing it? That config assumes it's at `src/ios/dependencies` but VS might move it around after incorporating it?

This issue on Google Maps seems to have a solution for you all https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/719

**Comment by ethanneff** [comment]
Hello. We had another partner with a similar issue. Installing Branch from VS TACO does not work whenever you import the plugin from its plugin name. You will need to download it from GitHub (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking) and import **locally**. Can you attempt this and see if this works for you too?

**Comment by aaustin** [comment]
Ethan has confirmed that this method of installing works. Closing issue for now.
