### ISSUE TITLE
Android compile error transformClassesWithJarMergingForDebug

### ISSUE THREAD

**Issue by hussainanver52** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#185]
hello 
I am trying to add this plugin for ionic framework (android) but when compiling i get different errors, 
firstly i was getting multiple dex file error and i added multiDexEnabled true
now i am getting the following error 

```
:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
```
i tried following ways to fix but i am not able to fix it 

1. tried to exclude android support v4 for branch by adding dependencie

```
compile('io.branch.sdk.android:library:1+') {
	exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
    }
```
plugins i have installed are 

com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
cordova-plugin-admobpro 2.14.0 "AdMob Plugin Pro"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-extension 1.3.0 "Cordova Plugin Extension"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12-dev "SocialSharing"
cordova-plugin-x-toast 2.5.0 "Toast"
es6-promise-plugin 3.0.2 "Promise"
io.branch.sdk 2.1.10 "branch-cordova-sdk"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"

2. I tried to change android support v4 with android suppoert v4:13
3. I added ` renderScriptTargetApi 23 to config`
4. I tried `configurations { all*.exclude group: 'com.android.support', module: 'support-annotations' }`
5. I tried to refresh the cordova by removing and adding back also

**Comment by renesansz** [comment]
@hussainanver52 , can you try doing this [workaround](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#android-resolving-issue-with-multiple-support-lib-v4)?
Hopefully this will resolve the issue.

**Comment by hussainanver52** [comment]
no it didnt worked its a issue with support v4 jar file replacing it by support v4:13 and updating the calls in facebook core to this api woked for me
