### ISSUE TITLE
Update BranchSDK version

### ISSUE THREAD

**Issue by Floppy1009** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#186]
Hey,

is there any schedule when you update to the new branch sdk version? I'm just asking since there is a version Branch-2.0.2.jar already out and here is still Branch-1.13.0.jar used which is already 2 months old.
Is there more to edit than just to include the new SDK?

**Comment by renesansz** [comment]
@Floppy1009 , sure, I'll do a follow-up pr for this.

**Comment by renesansz** [comment]
submitted pr #189

**Comment by Floppy1009** [comment]
@renesansz Thank you! :)
Hope it forks and gets merged soon

**Comment by renesansz** [comment]
@Floppy1009 , no prob 👍 
btw PR has been merged, I'll close the issue now.
