### ISSUE TITLE
showShareSheet or generateShortUrl not working

### ISSUE THREAD

**Issue by hussainanver52** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#190]
helo i tried to call showShareSheet and generateShortUrl to create link to share for branch io but both of these functions neither generates error or success in promise.

i tried to create banch by using createBranchUniversalObject object  and its giving successfull message

any help will be appreciated

**Comment by renesansz** [comment]
@hussainanver52 , can you provide you code for this? also provide some other details (eg: Android/iOS version, plugin version, and cordova version)

**Comment by hussainanver52** [comment]
hello I am trying to use the sample source code specified in git readme file 
android version 23 
cordova version 6.2.0
and branch plugin 2.1

**Comment by aaustin** [comment]
Hey @hussainanver52 - Can you make sure that you've done the following:
- allowed internet in the Android app with this line in tiapp.xml:
`<uses-permission android:name="android.permission.INTERNET"/>`
- done the proper Branch initialization as described here: https://dev.branch.io/getting-started/sdk-integration-guide/guide/titanium/#start-a-branch-session

If you've done both of those, please add this line to the tiapp.xml:
`<meta-data android:name="io.branch.sdk.TestMode" android:value="true" />`

Then, try to call the above methods and post the logs here.

**Comment by renesansz** [comment]
@hussainanver52 does this still issue occurs?

**Comment by hussainanver52** [comment]
No its working with updates sprcified with @aaustin
thanks everyone and sorry for late reply
