### ISSUE TITLE
runtime error `Uncaught module babel-runtime/core-js/promise not found`

### ISSUE THREAD

**Issue by khagesh** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#198]
`Uncaught module babel-runtime/core-js/promise not found` is the error we are getting after running the app. This is because of generated `branch.js` in `www` which does require of `babel-runtime/core-js/promise`. 

I have tried adding `babel-polyfill` global.js, but it did not work. I am not well versed with babel as much, can you please suggest some quick fix?

**Comment by aaustin** [comment]
hey @khagesh - can you try this again? We've just remove the babel dependency?

**Comment by aaustin** [comment]
I've confirmed this is resolved. Apologies for the breakage.
