### ISSUE TITLE
Align npm package name with plugin ID in plugin.xml

### ISSUE THREAD

**Issue by jakub-g** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#199]
Hello,

FYI, in `plugin.xml` you have

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/plugin.xml#L28

    <plugin ... id="io.branch.sdk" version="2.1.10">

whereas the package name of the plugin in npm is `branch-cordova-sdk`

This discrepancy is confusing, no other cordova plugin we're using is doing this. 

We found this out because we have some tooling put in place that verifies before build if each plugin from app's `package.json` (we use ionic) is installed, and up to date, by checking `./plugins/${npm-package-name}/plugin.xml` and/or `package.json`, but in your case, the folder created in `plugins` dir is 
`io.branch.sdk`, not `branch-cordova-sdk` as the npm repo name suggests.

**Comment by aaustin** [comment]
That is suspicious. I'm not sure when this occurred. It'll be hard to change the name on NPM, but it shouldn't be too hard to change the plugin title.

Do you foresee any breaking changes if we were to change the id of the plugin in terms of backwards compatibility?

cc @amit-bansil

**Comment by amit-bansil** [comment]
My concern is that when you install if the plugin id changes you'll end up
with a new copy and an old copy. Maybe we can test on the testbed and then
see what the plugins directory contains? I'm not at a computer until Monday
but can look into it then.

**Comment by amit-bansil** [comment]
I've tested several approaches to solving this problem and it looks like there is no way to change the plugin id without ending up with two copies of the plugin installed on update. As such, although I completely understand your concern @jakub-g, at this stage in the game I think we are stuck with the mistake. I'm closing this issue.
