### ISSUE TITLE
Link always redirects to app store

### ISSUE THREAD

**Issue by hsmith825** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#200]
I am on IOS.An example link is https://pjab.app.link/Uy6xIJWoQv.  The link is an invite sent from my iOS app.  If a user clicks the link they are aways redirected to the App Store.  This occurs even if the user has installed the app.  When the app is installed the user should be redirected to the iPhone.

Any ideas are appreciated.

Thanks!
Howard

**Comment by hsmith825** [comment]
Additional comment.  This link worked until this weekend.I don't know of anything that happened this weekend to cause this link to break.  I have ow updated to the latest BranchMetrics plugin to see if that would help.  That did not help.

Thanks!

**Comment by aaustin** [comment]
Hey @hsmith825 - Thanks so much for the note. I've separately confirmed that there's no issue with Universal Links with the plugin at this point, so there must be a configuration issue. I'm going to close this ticket and request that you send a note to support@branch.io regarding your specific account. They'll help you iron out any bugs you might have.

Just to be somewhat useful in this note, here are some resources you can use to help debug:
1. First, paste the link into our Universal Link validator https://branch.io/resources/universal-links/. I pasted it in and saw that you've currently configured your Branch links to work with team ID `BF4Y5578V3` and bundle id `com.flickitt.flickitt22`
2. Now, it's important to ensure those configurations match your settings. Did you add the the lines to the config file as described here? https://dev.branch.io/getting-started/universal-app-links/guide/cordova/#add-the-associated-domains-entitlement-to-your-project
3. You can confirm your bundle id by looking into the ios.json file in your platform folder.

Hopefully this helps you track down the issue!

**Comment by hsmith825** [comment]
Thanks Alex!
