### ISSUE TITLE
Android - Link opened while app is running doesn't trigger the DeepLinkHandler callback

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#204]
If you try to redirect to a deep link in a browser to open the app if the app is NOT running it opens the app and calls the DeepLinkHandler callback.  Awesome.

If the app IS running but in the background (you were in an email or something), it brings the app to the foreground, but doesn't trigger the DeepLinkHandler callback.

This just started happening recently as far as I can tell.  Honestly I don't have a good way of knowing which update would have caused it.

Do I need to do something special when the app is brought to the foreground to check if it was from a deep link?   For example: do I need to call the Branch.initSession(); again?

**Comment by gabaum10** [comment]
Indeed, that does seem to be the case.  You should updated your docs, or add some sort of better handler for when the app is brought to the foreground.

**Comment by renesansz** [comment]
@gabaum10 , yes, you should implement the `onResume` checking by yourself.
You can do that by doing
```
document.addEventListener("resume", function () {
     Branch.initSession();
});
```
`DeepLinkHandler` response will let you know if it comes from a deep link or if the app has been opened manually.

Let me know if this helps you with your issue, then I'll submit a PR to update the instructions on using the plugin.

**Comment by gabaum10** [comment]
Yeah, I figured that out after some trial an error.  I left this open so you guys could update your docs or just make it work otherwise.  I had no idea adding that handler was something that was needed to be done.

**Comment by aaustin** [comment]
Hey @gabaum10. Updated:
1. docs site https://dev.branch.io/getting-started/sdk-integration-guide/guide/cordova/#start-a-branch-session
2. readme https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/README.md#initsession

Thanks for the tips!
