### ISSUE TITLE
Branch's node dependencies are not contained within the plugin

### ISSUE THREAD

**Issue by jaksah** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#205]
When installing the branch sdk using the instructions in the README
```
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=<your-branch-key> --variable URI_SCHEME=<your-app-uri-scheme-without-colon-and-slashes>
```
The `npm install -D ' + moduleName;` in `beforePluginInstallHook.js` adds branch's dependencies to the root package.

Our project structure looks like this
```
app/
├── package.js  <-- Branch's deps are added here
├── node_modules/
├── src/
├── cordova
│   └── plugins
│            └── io.branch.sdk
```
This would probably be solved if you could add the dependencies to `bundledDependencies` in `package.json` and run `npm publish`

Ref: https://docs.npmjs.com/files/package.json#bundleddependencies

**Comment by aaustin** [comment]
Thanks so much for the investigation and thorough feedback @jaksah - This doesn't look like a major or breaking change so we'll get it done in the next update.

**Comment by jaksah** [comment]
Tahnks @aaustin :)

**Comment by aaustin** [comment]
Just merged the fix in!
