### ISSUE TITLE
Issue submitting to store with entitlements file from hooks

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#207]
https://github.com/phonegap/build/issues/279#issuecomment-200986755

**Comment by Notifium** [comment]
Hi Austin,
I think the issue here is that Phonegap build don't support build hooks. I'm posting here in case a solution comes up later :-)
Andy

**Comment by ethanneff** [comment]
After looking into the Xcode projects, the entitlements file is correctly being correctly on all platforms (Cordova, Ionic 1, Ionic 2, and PhoneGap). 

Should I attempt to submit a test app to the App Store to see if there are any issues post App Store release?

**Comment by aaustin** [comment]
Nah - let's hold on this one! Thanks

**Comment by ethanneff** [comment]
fixed with #245
