### ISSUE TITLE
Incompatible with Crashlytics SDK on Android

### ISSUE THREAD

**Issue by lookitsatravis** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#208]
After installation on Android, I am unable to build. I get a `com.android.dex.DexException` because both `io.branch.external.answersshim` (which is a dependency of the Android SDK) and `com.crashlytics.sdk.android` import the same classes (specifically in the error `com/crashlytics/android/answers/shim/KitEventLogger`). The Android SDK docs specify how to exclude that module, but I cannot determine how to accomplish this for the Cordova plugin. I know you guys are now affiliated with Fabric, so I'm hoping this is a quick fix and perhaps I've just missed something in the Cordova docs.

Any assistance would be appreciated!

**Comment by lookitsatravis** [comment]
I was indeed able to get the project to build by doing the following:

1) Commenting out the following line in the plugin.xml

```xml
<!--<framework src="io.branch.sdk.android:library:1.+" />-->
```

2) Adding the following to `platforms/android/build.gradle`:

```gradle
compile ('io.branch.sdk.android:library:1.+') {
    exclude module: 'answers-shim'
}
```

The question now is...is this possible to do without editing the plugin? Unfortunately, I can't find any way to do it in the Cordova docs.

**Comment by aaustin** [comment]
Ugh that's annoying. Let me look at how we could do an exclude from the plugin.xml or from within the project config. I'm sure Cordova supports it.

Thanks for the heads up! Glad you found the temporary work around.

**Comment by aaustin** [comment]
Hey man - What do you think about this? https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/209 Then, when you encounter the conflict, you could just add
``` {
    exclude module: 'answers-shim'
}``` to the gradle extension file.

**Comment by lookitsatravis** [comment]
@aaustin I think it looks good. I did the same thing myself after I posted the comment above. 

Honestly, it always feels off to me to have to do these kind of things, because I'd really love to leave the plugins directory out of my repos in the same way that I leave out node_modules. At the same time, I can't find a better way to do it short of adding it as part of the plugin install process. Basically, using a variable during the install command to do that configuration automatically. Of course, the drawback then is that if you want to change it, you have to remove and then add the plugin back which has it's own set of issues. It also seems like a lot of work for what is likely an edge case.

All of that nonsense to say... 👍 !

**Comment by aaustin** [comment]
Travis - thanks for the feedback. The functionality was merged in, and I'll get the docs merged in next update.
