### ISSUE TITLE
Build Fail on iOs

### ISSUE THREAD

**Issue by PRotig** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#214]
Hello guys, 

Since the recent update (about severals hours ago), build fails for ios. 

Can you help me please.

Cheers

The error : 

** BUILD FAILED **

The following build commands failed:

	CompileC build/Quatre\ Epingles.build/Debug-iphonesimulator/Quatre\ Epingles.build/Objects-normal/x86_64/BNCFabricAnswers.o Quatre\ Epingles/Plugins/io.branch.sdk/BNCFabricAnswers.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/paul/Sites/quatre-epingles-app/platforms/ios/cordova/build-debug.xcconfig,-project,Quatre Epingles.xcodeproj,-target,Quatre Epingles,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/paul/Sites/quatre-epingles-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/paul/Sites/quatre-epingles-app/platforms/ios/build/sharedpch

**Comment by aaustin** [comment]
Hey @PRotig - This is totally my fault. I merged a few PRs in earlier, including one from another party that broke our automated deployment. I just fixed the automated deployment and it should have correctly pushed to NPM. Please update to 2.2.0 (which was released about 20 minutes after you put the ticket in).

Super sorry about the annoyance.

**Comment by PRotig** [comment]
It is working !

Thanks a lot

<https://www.quatreepingles.fr/>   PAUL *RÖTIG*
CO-FONDATEUR
*QUATRE EPINGLES*
06 64 17 79 78
paul@quatreepingles.fr
www.quatreepingles.fr
<https://itunes.apple.com/fr/app/quatre-epingles/id1007102899?mt=8>
<https://play.google.com/store/apps/details?id=fr.quatreepingles.app>





2016-09-15 23:15 GMT+02:00 Alex Austin <notifications@github.com>:

**Comment by phanthinh** [comment]
similar issue with error message below

`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CSSearchableIndex", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_CLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
