### ISSUE TITLE
Changelog needs an update

### ISSUE THREAD

**Issue by giltotherescue** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#215]
Just noticed your changelog was not updated as part of your most recent release (yesterday). I was able to tell the changes by looking at the Releases page, however.

**Comment by aaustin** [comment]
Thanks for the note! We'll keep that updated in the future https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/216
