### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by aluzino** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#223]
Error: Cannot read property 'forEach' of undefined
![2016-09-27 12_16_37-kiklu - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/10666050/18884264/4991b448-84ac-11e6-9ead-f8b44bab1a26.png)

**Comment by aaustin** [comment]
Hey @aluzino - Thanks so much for the note. How often is this happening for you? We have yet to see this in production.

Looking at the code, it seems that you might not have defined your platforms yet https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/hooks/afterPrepareHook.js#L43. Example `cordova platform add ios`.

**Comment by aluzino** [comment]
I resolve these error but in VS found other error: 'Brach/Branch.h' file not found BranchSDK.h

**Comment by aaustin** [comment]
Hey @aluzino - That's very strange too. Can you see if this issue fits your pattern of usage? https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/176 We believe there's a visual studio issue.
