### ISSUE TITLE
Conflicting naming

### ISSUE THREAD

**Issue by hx-markterry** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#228]
On NPMJS this plugin is named `branch-cordova-sdk`, when it is saved in the `config.xml` in your project it appears as:

```
<plugin name="io.branch.sdk" spec="~2.2.2" />
```

This means when you restore the platforms for the project cordova tries to download the plugin `io.branch.sdk` which can't be found on NPMJS.

Could the name of this plugin match the name on NPMJS?

**Comment by aaustin** [comment]
Hey @hx-markterry - Thanks for pointing this out. It's unfortunately due to a legacy migration and we're pretty stuck with it at the moment, lest we break a lot of builds for an update. https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/199
