### ISSUE TITLE
fatal error: 'CoreSpotlight/CoreSpotlight.h' file not found #import <CoreSpotlight/CoreSpotlight.h>

### ISSUE THREAD

**Issue by FlatironSoftworks** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#232]
I have an Ionic/Cordova project with a deployment target of 8.3 

I added sdk via "cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_xxxx--variable URI_SCHEME=scheme"

Initially received Error:

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CSSearchableIndex", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_CLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Added CoreSpotlight.framework as an optional linked framework.
Cleaned Project & Deleted Derived Data

Upon build I now receive 

```
platforms/ios/projectname/Plugins/io.branch.sdk/BranchCSSearchableItemAttributeSet.h:11:9: fatal error: 'CoreSpotlight/CoreSpotlight.h' file not found
#import <CoreSpotlight/CoreSpotlight.h>
```

I also tried adding the plugin from the github repository directly with no success.

**Comment by FlatironSoftworks** [comment]
Is there some reason for no response?

**Comment by aaustin** [comment]
Hey @FlatironSoftworks - Sincere apologies here. @ethanneff Is supposed to be covering responses here although I think he must have forgotten to reply. Let me check with him as I know he's working on a few fixes in this PR https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/231

**Comment by FlatironSoftworks** [comment]
Thanks for the quick reply!

**Comment by ethanneff** [comment]
Hello @FlatironSoftworks,

Sorry about the delay. My notification for this repository were triggered off for some reason. 

We have a Pull Request in the making for this issue. https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/231. This Pull Request is still not ready for prod yet, so in the meantime can you please try the following to bypass npm?

```bash
# replace the xxxx's with the corresponding values within https://dashboard.branch.io/settings/link
cordova plugin remove io.branch.sdk;
cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git --variable BRANCH_KEY=xxxx --variable URI_SCHEME=xxxx;
```

Keep in mind, you might have to reinstall your platforms to clear the cache of the bad Branch sdk:

```bash
ionic platform remove android;
ionic platform remove ios;
ionic platform add android;
ionic platform add ios;
```

**Comment by FlatironSoftworks** [comment]
Will do. Thanks!

**Comment by FlatironSoftworks** [comment]
That allowed it to build correctly. Thanks! Will test and validate functionality.

**Comment by phanthinh** [comment]
Hi @FlatironSoftworks  @ethanneff 

I really not working with me. I still saw similar issue. Can you help me on it?

**Comment by adityasaxena** [comment]
@phanthinh There is an open pull request by @elliotstokes. That should help I think. 💃
