### ISSUE TITLE
createBranchUniversalObject return "pending" Promise

### ISSUE THREAD

**Issue by heks** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#233]
var branchUniversalObj = null;

Branch.createBranchUniversalObject({
  canonicalIdentifier: 'identifier',
  title: 'Just another title',
  contentDescription: 'Just another description',
  contentImageUrl: '/img.jpg',
  contentType: 'text',
  contentIndexingMode: 'public'
}).then(function (newBranchUniversalObj) {
  // Success Callback
  branchUniversalObj = newBranchUniversalObj;
  console.log(newBranchUniversalObj);
}, function (err) {
  // Error Callback
  console.error(err);
});

I try copy pasting this code in cordova app and is return a Promise {"status": "pending"} that never resolves. I am using the latest package (2.3.0) on iOS. What can be the problem?

**Comment by renesansz** [comment]
@heks , have you checked if you've initialized Branch?
`Branch.initSession()`

**Comment by ethanneff** [comment]
Hello @heks,

The reason you are getting a `pending` response is because you creation of the Branch Universal Object is malformed. Can you please try the following example and tell me if you are experiencing a similar issue?

```js
// only canonicalIdentifier is required
var properties = {
    canonicalIdentifier: "123",
    canonicalUrl: "http://example.com/123",
    title: "Content 123",
    contentDescription: "Content 123 " + Date.now(),
    contentImageUrl: "http://lorempixel.com/400/400",
    price: 12.12,
    currency: "GBD",
    contentIndexingMode: "private",
    contentMetadata: {
        "custom": "data",
        "testing": 123,
        "this_is": true
    }
};

// create a branchUniversalObj variable to reference with other Branch methods
var branchUniversalObj = null;
Branch.createBranchUniversalObject(properties).then(function(res) {
    branchUniversalObj = res;
    alert("Response: " + JSON.stringify(res));
}).catch(function(err) {
    alert("Error: " + JSON.stringify(err));
});
```

**Comment by heks** [comment]
That fixed it thanks.
