### ISSUE TITLE
iOS shareText/shareTitle and other "localization" properties

### ISSUE THREAD

**Issue by chancezeus** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#235]
On iOS if you try to use the localization option as an object with the text/title/etc properties, everything get's inserted as a text blob (including the copyToClipboard and other "non relevant" keys).

Looking at the code in `cordova-ionic-phonegap-branch-deep-linking/src/ios/dependencies/Branch-SDK/BranchUniversalObject.m` on line 181 the shareText is a NSString, later in this method on lines 187 and 229 it looks like the NSString is accessed as a dictionary using valueForKey (which I assume is incorrect, since it is still a NSString not a dictionary). The end result is the entire object being inserted as a string without the properties being parsed and/or used.

**Comment by ethanneff** [comment]
Hello @chancezeus,

Thank you for reaching out. The **localization** field is outdated in our documentation. I apologize for this. We are in the process of updating all of our documentation. 

Please look at this document and this example for the Branch share sheet feature:
https://gist.github.com/ethanneff/614e56fa3d3f98c03beaa07c66e6ccbe#share-deep-link

```js
// optional fields
var analytics = {
    channel: "channel",
    feature: "feature",
    campaign: "campaign",
    stage: "stage",
    tags: ["one","two","three"]
};

// optional fields
var properties = {
    $fallback_url: "www.example.com",
    $desktop_url: "www.desktop.com",
    $android_url: "www.android.com",
    $ios_url: "www.ios.com",
    $ipad_url: "www.ipad.com",
    more_custom: "data",
    even_more_custom: true,
    this_is_custom: 41231
};

var message = "Check out this link";

// needs a universal object

// optional listeners (must be called before showShareSheet)
branchUniversalObj.onShareSheetLaunched(function(res) {
  // android only
  alert(JSON.stringify(res));
});
branchUniversalObj.onShareSheetDismissed(function(res) {
  alert(JSON.stringify(res));
});
branchUniversalObj.onLinkShareResponse(function(res) {
  alert(JSON.stringify(res));
});
branchUniversalObj.onChannelSelected(function(res) {
  // android only
  alert(JSON.stringify(res));
});

// share sheet
branchUniversalObj.showShareSheet(analytics, properties, message);
```
