### ISSUE TITLE
Missing branch.js.map file

### ISSUE THREAD

**Issue by jworm7** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#236]
Upon running on my iOS device I get a message stating "[directory]/www/plugins/io.branch.sdk/www/branch.js.map" was not found. I've also verified that the file doesn't exist in the listed directory. The only file in that directory in branch.js. I am using the the last spec 2.2.3. I've tried uninstalling the plugin and reinstalling and the same goes for the ios platform. Is there a configuration that I'm missing?

**Comment by renesansz** [comment]
@jworm7 , can you try to install the plugin directly from Github?
`cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git --variable BRANCH_KEY=key_live_xxxx --variable URI_SCHEME=YOUR_URI_SCHEME`

Based on the repo the [branch.js.map](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/www/branch.js.map) file should still exist.

**Comment by jworm7** [comment]
I tried that as well but unfortunately no luck

**Comment by renesansz** [comment]
That's weird, have you clean up all the `platform` and `plugin` folders before reinstalling the plugin?
```
cordova platform add ios;
cordova platform add android;
cordova plugin remove io.branch.sdk;
cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git --variable BRANCH_KEY=key_live_xxxx --variable URI_SCHEME=YOUR_URI_SCHEME
```

So far, I can't replicate the issue that you're having.

**Comment by jworm7** [comment]
Yes I have and still no success. This is how my system is currently configured:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.0.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 8.1 Build version 8B62 

Is there anything in this configuration that would be problematic?

**Comment by ethanneff** [comment]
Hello @jworm7 


We have a Pull Request in the making for this issue. #231. This Pull Request is still not ready for production yet, so in the meantime can you please try the following to bypass npm?

```bash
# replace the xxxx's with the corresponding values within https://dashboard.branch.io/settings/link
cordova plugin remove io.branch.sdk;
cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git --variable BRANCH_KEY=xxxx --variable URI_SCHEME=xxxx;
```

Keep in mind, you might have to reinstall your platforms to clear the cache of the bad Branch sdk:

```bash
cordova platform remove android;
cordova platform remove ios;
cordova platform add android;
cordova platform add ios;
```

**Comment by jworm7** [comment]
@ethanneff unfortunately what your proposed hasn't resolved the issue. Is there any timeline for the pull request?

**Comment by ethanneff** [comment]
Hello @jworm7,

Is the error preventing the app from compiling?

Is the error similar to this one? ![image](https://cloud.githubusercontent.com/assets/2933593/19788120/7ba0a9e6-9c5b-11e6-90b1-ae669102fcea.png)
Iff so, you can remove this error temporarily by removing this line from the bottom of APP_NAME/plugins/io.branch/sdk/www/branch.js. Again, you might have to reinstall your platforms to clear the cache of the bad Branch SDK. 
<img width="313" alt="screen shot 2016-11-09 at 8 29 06 pm" src="https://cloud.githubusercontent.com/assets/2933593/20164701/7279fa1a-a6bb-11e6-9d48-73e908d7cc72.png">

I apologize for this inconvenience.

**Comment by jworm7** [comment]
Hey @ethanneff 

Thanks for getting back. Thankfully it isn't a compiling issue it similar to what you pasted in. I've removed that line of code and it appears that the error has gone. I just want to verify that in removing the reference to the branch.js.map file that there aren't any features or branch capabilities that I would be missing?

**Comment by ethanneff** [comment]
Hey @jworm7,

The `.map` file is created whenever we convert our `.js.es6` code to `.js`.  Essentially, it is a temporary conversion file which should never belong in our production code. You will not lose any features or branch capabilities by removing that line of code.  

Best,
