### ISSUE TITLE
App fails on logout

### ISSUE THREAD

**Issue by IvanProdaiko94** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#243]
I have an Ionic/Cordova app that fails when I click logout, it started happening when I add Branch to my project, more over, I didn't even call `BranchInit()` method, moreover I didn't call 'Branch.logout()'.

Here is a screen from Xcode with error. 
[https://monosnap.com/file/OXzmfYRUj4Fd9vqGggQQViJ7xx2kkB](https://monosnap.com/file/OXzmfYRUj4Fd9vqGggQQViJ7xx2kkB)

**Comment by aaustin** [comment]
Hey @IvanProdaiko94 - Your screenshot is behind some sort of Github access wall. Can you try to open up permissions?

Can you share anything else about the failure? Is it a crash? Do you have crash logs? We haven't had any trouble with Ionic/Cordova with our own tests so we'll need more info. Thanks!

**Comment by IvanProdaiko94** [comment]
- What permissions do I need to set to launch branch? I thought plugin.xml will provide my app with require permissions.
It fails only on IOS. When I click logout, my app crashes from time to time and the error tracer says that it was branch, who fails. Please look at the peacture again

**Comment by aaustin** [comment]
I don't think it's a permission issue.

Can you share the code you're using to call [setIdentity](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#track-user)? It looks as if you might be passing a non-string object as a parameter that causing us to barf.

**Comment by IvanProdaiko94** [comment]
Yep, you are right. I provide an number parameter;
