### ISSUE TITLE
ionic build ios not working

### ISSUE THREAD

**Issue by phanthinh** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#244]
I saw error message when used "ionic build ios"

`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CSSearchableIndex", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_CLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

If there is a bug or error in this repo, please file the issue [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues).

If you are having trouble integrating the Branch SDK, please reach out to us [here](https://support.branch.io/support/tickets/new)

Thank you.

**Comment by ethanneff** [comment]
Hello @phanthinh,

Thank you for reporting this issue. We will look into it as soon as possible.

To aid in our investigations, can you please provide us with the following information? 
- The console output of `ionic info` and `ionic platform`

Best,

**Comment by renesansz** [comment]
@phanthinh , also please include the manifest settings or any additions you did in your project setup also a code implementation would help.

**Comment by phanthinh** [comment]
Hi @ethanneff 

`sh-3.2# ionic info

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************`

`ionic platform
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
Installed platforms:
  android 5.1.1
  ios 3.9.2
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0

`

That's info in the my source

**Comment by ethanneff** [comment]
Hello @phanthinh,

I did the following sample app using a test [Branch Dashboard](https://dashboard.branch.io/settings/link) configuration. 

# Sample Test App

#### 1) install

``` bash
npm install -g cordova ionic;
ionic start t3 tabs;
cd t3;
ionic platform add ios;
ionic platform add android;
ionic plugin remove io.branch.sdk;
# values should be from your Branch Dashboard https://dashboard.branch.io/settings/link
ionic plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_jnBhaHwt5K8xtn4g4hblHoleqsocI6C2 --variable URI_SCHEME=branchionic;
```

#### 2) update config.xml

``` js
<!-- values should be from your Branch Dashboard https://dashboard.branch.io/settings/link -->
<widget id="com.eneff.branch.ionic" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <branch-config>
    <ios-team-id value="PW4Q8885U7"/>
    <host name="cluv.app.link" scheme="https"/>
    <host name="cluv-alternate.app.link" scheme="https"/>
  </branch-config>
```

#### 3) update app.js

``` js
// sample app.js
angular.module('starter', ['ionic', 'starter.controllers', 'starter.services'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if (window.StatusBar) {
      StatusBar.styleDefault();
    }

    // Branch initialization
    Branch.initSession(function(data) {
      // read deep link data on click
      alert('Deep Link Data: ' + JSON.stringify(data));
    });
  });
})
// ...
```

#### 4) delete app off device

#### 5) compile ionic

``` bash
ionic build ios;
```

#### 6) open project in Xcode as assign team

``` bash
open -a Xcode platforms/ios/t3.xcodeproj;
```

#### 7) install on device (not simulator)

#### 8) create a deep link from your [Branch Dashboard](https://dashboard.branch.io/marketing)

#### 9) click on a deep link in iMessage to open the app

![image](http://i.imgur.com/YzeE14X.gif)

Can you please try to do the following example app with your own [Branch Dashboard](https://dashboard.branch.io/settings/link) configuration?

If you are still having trouble, you can contact Branch directly [here](https://support.branch.io/support/tickets/new) where we will be able to look into your account to better troubleshoot your issue.

Best,

**Comment by renesansz** [comment]
@phanthinh have you done executing the command `npm install -g ios-deploy`?

If you wish to build it to an iOS app you must also install the dependency for Cordova build

**Comment by phanthinh** [comment]
This is very weird. I will try again many times to resolved it.

Thank two you for any comment.

**Comment by phanthinh** [comment]
@ethanneff 

Oh it's conflict with ionic push plugin. So it's work fine now.

Thank you so much.
