### ISSUE TITLE
Branch.initSession not working 

### ISSUE THREAD

**Issue by phanthinh** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#248]
Hi everybody,

I have used code at below:
`
$ionicPlatform.ready(function() {
    // Branch initialization
    alert(JSON.stringify(Branch)) // {debugMode: false}
    Branch.initSession(function(data) {
      // read deep link data on click
      alert('Deep Link Data: ' + JSON.stringify(data));
    });
});
`

At simulator: It's just only show alert {debugMode: false}
At device: It's not any alert

What happen for this?

If there is a bug or error in this repo, please file the issue [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues).

If you are having trouble integrating the Branch SDK, please reach out to us [here](https://support.branch.io/support/tickets/new)

Thank you.

**Comment by renesansz** [comment]
Hello @phanthinh ,
Thanks for reporting the issue, we'll look into it.
At the moment, can you provide more details regarding the bug? eg: Cordova version, iOS/Android version.

Best,

**Comment by renesansz** [comment]
@phanthinh , the function parameter for `initSession` is a function callback for deep link data, this only triggers upon opening a deep link url.
Please note that the `initSession` is promisified, therefore you can do `.then()` and `.catch()`
Example:
```
Branch.initSession(handleDeepLinkCallback).then(onInitSuccess).catch(onInitError);
```

**Comment by phanthinh** [comment]
@renesansz  It's work for simulator?
