### ISSUE TITLE
Unable to install the plugin in Platforms directory using config.xml

### ISSUE THREAD

**Issue by adityasaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#251]
Hi,

In my config.xml I have two things:

1. 
```
<plugin name="io.branch.sdk" spec="~2.4.2">
        <variable name="BRANCH_KEY" value="key_live_igupHQAeyeHaILjCyCPGajcayDjCyCPG" />
        <variable name="URI_SCHEME" value="XXX" />
    </plugin>
```

2. 
```
<branch-config>
        <host name="XXX.app.link" scheme="https" />
    </branch-config>
```

When I try to do `cordova build android`, the plugin doesn't result in my AndroidManifest.xml changes.

However, if I tried to do `cordova plugin add ...` command, then the plugin does get added to AndroidManifest.xml.

Could someone help me understand what am I missing here ?

**Comment by renesansz** [comment]
@aditiverma ,
`<branch-config>` is okay, however can you try to set your branch_key & uri_scheme upon adding the plugin?
```
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=<YOUR-BRANCH-KEY> --variable URI_SCHEME=<YOUR-URI-SCHEME>;
```

**Comment by adityasaxena** [comment]
@renesansz I can't believe what I have for you :-) `io-branch-sdk` cannot fetch the plugin from registry when set like this:

```
<plugin name="io.branch.sdk" spec="~2.4.2">
        <variable name="BRANCH_KEY" value="key_live_igupHQAeyeHaILjCyCPGajcayDjCyCPG" />
        <variable name="URI_SCHEME" value="XXX" />
    </plugin>
```

What does work however is this:

```
<plugin name="branch-cordova-sdk" spec="~2.4.2">
        <variable name="BRANCH_KEY" value="key_live_igupHQAeyeHaILjCyCPGajcayDjCyCPG" />
        <variable name="URI_SCHEME" value="XXX" />
    </plugin>

```

Would someone have this fixed soon ? :-)

**Comment by adityasaxena** [comment]
I don't think any progress will be made here. I am making my way by using branch-cordova-sdk in the plugin's name field and that lets me move forward.
