### ISSUE TITLE
iOS .entitlements file location could be wrong

### ISSUE THREAD

**Issue by adityasaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#252]
When I do a `cordova build android`, I see that the location of the .entitlements file is under `<myapp>/Resources` but when I open the project in XCode, it doesn't realize the apple app site associations. When I move the file from `<myapp>/Resources` to `<myapp>`, that is when I start to see things work - anyone got any idea why?

**Comment by adityasaxena** [comment]
Anyone here?

**Comment by ethanneff** [comment]
Hello @adityasaxena,

Thank you for reaching out and I apologize for the delay. 

The correct location for the iOS .entitlements file is  `<myapp>/Resources`. Moving this file to `<myapp>` should not have made a difference. *(The directories within Xcode should not make a difference as long as the file is within the project)*

There are multiple ways that Branch deep link could have stopped working. Did you make any of theses changes while moving the entitlement's file which could have caused deep linking to start working again?

- Updated your platforms (e.g. `cordova platform rm ios; cordova platform add ios;`)
- Added your `Team` within Xcode *(activates Universal Linking)*
- Deleted and reinstalled the app *(lets Apple re-scrape the AASA for Universal Linking)*
- Re-enable deep linking by long pressing a deep link *(deep links can be disabled by user per device)*
- Updated your `config.xml` to new values which are represented in your [Branch Dashboard](https://dashboard.branch.io/settings/link)

Again, thank you for your patience. I am happy you were able to get Branch working and I hope you will utilize our service to the fullest to make your app the best.

Regards,

**Comment by adityasaxena** [comment]
Hi @ethanneff .Thank you for the response.
I did re-install the app multiple times because I needed to debug other issues as well. However, as of now, when I install the plugin and do `cordova build ios`, The Associated Site Domains under XCode are all empty. And, which is why, as of this moment, the deep linking isn't working for me on iOS.

<img width="692" alt="screenshot 2016-12-08 06 36 40" src="https://cloud.githubusercontent.com/assets/993800/20991388/b6229be4-bd10-11e6-97f1-02f8389c1a57.png">

**Comment by adityasaxena** [comment]
@ethanneff Btw, could node version be an issue? I'm on 0.12.7 and unfortunately I cannot move to a newer one in at least a couple more months.

**Comment by adityasaxena** [comment]
Hi @ethanneff, I think everything's correct with my installation except what I see here : Entitlements file which can't be located by the script available on branch.io. Something's definitely amiss. *And I cannot manually add Associated Domains in XCode everytime I need them*

<img width="867" alt="screenshot 2016-12-08 07 44 41" src="https://cloud.githubusercontent.com/assets/993800/20993022/6773905c-bd1a-11e6-9aa1-cdf8891ea08c.png">

**Comment by adityasaxena** [comment]
@ethanneff Another finding I just have is things didn't work for me on XCode 8 but for a colleague of mine, it did work ( cc @rajnishdashora ). He is on XCode 7

**Comment by adityasaxena** [comment]
Hello @ethanneff . Could you maybe talk more about your point No. 3 
```
Deleted and reinstalled the app (lets Apple re-scrape the AASA for Universal Linking)
```
What does this mean and how is my Test App which is **not yet in App Store** going to handle this ?

**Comment by ethanneff** [comment]
Hello @adityasaxena,

Sorry about the delay. You can test installs with your app with the following [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-simulating-an-install). I am closing this issue for now. Feel free to reach out if you still need help troubleshooting. 

Best,
