### ISSUE TITLE
$deeplink_path problem

### ISSUE THREAD

**Issue by fx69005** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#258]
hi everyone, i use your plugin on my ionic1 project.  i try to share on facebook , works great but i have a problem with configure $deeplink_path:

```
var branchUniversalObj = null;

        Branch.createBranchUniversalObject({
          canonicalIdentifier: eventRef.id,
          title: data.title,
          contentDescription: data.desc,
          contentImageUrl: data.picture, 
        }).then(function (newBranchUniversalObj) {
          branchUniversalObj = newBranchUniversalObj;
          console.log('new branchObject : ' , newBranchUniversalObj);

          // optional fields
          var analytics = {
            channel: "chanel1",
          };

          // optional fields
          var properties = {
            $deeplink_path: "detail/12345"
          };

          var message = "hello";

          // share sheet
          branchUniversalObj.showShareSheet(analytics, properties, message);

        });
```

Share works but my link havn't "$deeplink_path"

best regards

**Comment by renesansz** [comment]
Hey @fx69005 ,
Thanks for reporting, It seems getting the `$deeplink_path` on generate short url is missing.
Will provide a PR to fix this soon.

Cheers,

**Comment by renesansz** [comment]
Submitted PR #260 to fix this issue. Waiting for merge

**Comment by fx69005** [comment]
thanks !  how many time for merge ?

**Comment by ethanneff** [comment]
@fx69005 It will be merged today. I'll update you once it is live.

**Comment by ethanneff** [comment]
@fx69005 My schedule became busier than expected today. The pull request will be tested and merged first thing in the morning. Thank you for your patience.

**Comment by fx69005** [comment]
thanks

**Comment by ethanneff** [comment]
Hello @fx69005, 

Thank you for your patience. The code is now live through this pull request #262.
