### ISSUE TITLE
Configuration Done but DeepLink does not work

### ISSUE THREAD

**Issue by adityasaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#259]
Node version - 6.9.2
Cordova Version - 6.4.0
Cordova IOS Version - 4.3.1
XCode - 8
Configurations on Branch Dashboard work fine for me. But, I cannot get DeepLink to work

See attached screenshot on a validator tool

<img width="1179" alt="screenshot 2016-12-13 10 44 30" src="https://cloud.githubusercontent.com/assets/993800/21126949/06115b30-c122-11e6-9a03-534e3564ca2d.png">
Above is despite the fact that I have associated domains in my .entitlements file. And, in my Capabilities section in Xcode, I see Associated Domains as ON.

**Comment by renesansz** [comment]
Hey @adityasaxena thanks for reporting this issue, I'll take a look on this. 
By the way, can you provide the the content of your `config.xml`?

**Comment by adityasaxena** [comment]
@renesansz It's for a private project. I'm guessing you need the entire `config.xml`. Please suggest a way I should send it to you.

**Comment by ethanneff** [comment]
Hello @adityasaxena,

Are you still installing the plugin the following way?

```xml
    <plugin name="branch-cordova-sdk">
        <variable name="BRANCH_KEY" value="key_live_icCccJIpd7GlYY5oOmoEtpafuDiuyXhT" />
        <variable name="URI_SCHEME" value="branchtest" />
    </plugin>
```

I've noticed that our SDK is not setup correctly for this way to work (I believe it may be an issue with our hooks).

Have you tried installing branch [this way](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) instead?

Furthermore, if you [submit a ticket](https://support.branch.io/support/tickets/new) to Branch with your `config.xml` and `branch key`, we can better assist you and see what is wrong with your configuration.

Best,

**Comment by adityasaxena** [comment]
@ethanneff Hey Ethan. Yes, that is how I'm installing the plugin - all cordova plugins work that way just fine.

But, you're saying that could be an issue - so, please allow me to quickly verify if it works the other way. I'll come back to you real quick and if it can't be resolved, then I'll submit a ticket and let you know, too.

**Comment by adityasaxena** [comment]
@ethanneff So, this is what I did:

- `cordova create <myprojectname>`
- `cd <myprojectname>`
-  Add the following to config.xml
```
<branch-config> 
        <ios-team-id value="<teamid>"/> 
        <host name="xxxx.app.link" scheme="https" /> 
        <host name="xxxx-alternate.app.link" scheme="https" /> 
    </branch-config>
```
- `cordova platform add ios`
- `cordova build ios --developmentTeam="<teamid>" --device`

When I do this, my deep linking is still not working - I see Associated Domains ON, but the deep-linking doesn't work.

**Comment by ethanneff** [comment]
Hello @adityasaxena,

Sorry about the delay. I was wondering if you were able to get Branch working successfully in your app? I remember seeing your support ticket last week and I wanted to make sure everything was up and running. I believe I suggested installed in Branch using the terminal. This is the current workaround until we get update the plugin to install via the config.xml.
```
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_hiuejxqEdbHR8Tc1L92nmiijrse9OBpq --variable URI_SCHEME=branchcordova;
```

I am closing this ticket for now. Feel free to reach out if you are still having difficulty. 

Best,

**Comment by razam217** [comment]
I'm seeing the same issue. The deeplink is not working only on IOS but it works fine on Android. 
In IOS it always ask me **Open this page in App Store?**. 
Please let me know what I'm doing wrong.


I installed my plugin this way 
`cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_hiuejxqEdbHR8Tc1L92nmiijrse9OBpq --variable URI_SCHEME=branchcordova;`

Also added branch-config element to config.xml
```

<branch-config>
    <ios-team-id value="xxxxxxxxxxx"/>
    <host name="bnc.lt" scheme="https" />
</branch-config>
<preference name="AndroidLaunchMode" value="singleTask" />
```
