### ISSUE TITLE
Is onNonBranchLink() usable?

### ISSUE THREAD

**Issue by chanphillip** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#269]
As the doc does not mention onNonBranchLink() and NonBranchLinkHandler() seems to be depreciated, I would like to ask if onNonBranchLink() is usable?
I've tried using it but the behavior is a little strange. It will be fired every onResume no matter if the app is opened through a deeplink (i.e. appname://).

If onNonBranchLink() is not suppose to be used, what should be the way to handle non-branch deeplinks? Perhaps using another plugin?

**Comment by renesansz** [comment]
@chanphillip you can look in to this part of the doc on how to handle non-universal [link](https://dev.branch.io/getting-started/universal-app-links/advanced/ios/#how-to-handle-non-universal-links-links-relying-on-custom-uri-schemes).

**Comment by ethanneff** [comment]
Hello @chanphillip,

Ideally, `onNonBranchLink()` should never be called. This is a method to handle URI Schemes from other Cordova plugins which can interact with Branch URI Schemes. 

When clicking on a Branch deep link, all deep link data should be retreived from the `Branch.initSession(function(data)` callback regardless of `resume` or `deviceready`:
```javascript
Branch.initSession(function(data) {
  // read deep link data on click
  alert('Deep Link Data: ' + JSON.stringify(data));
});
```

Where you relying on the depreciated `NonBranchLinkHandler()` before? If so, I would like to know more (the steps, the use case, etc). It could be possible that the new `onNonBranchLink()` is not functioning correctly.

Best,

**Comment by jstoup111** [comment]
@ethanneff `onNonBranchLink()` was added as a request by me. 

I needed to Deep Links that were not Branch links. I.E. `my-scheme://home` instead of something that Branch generated.

@chanphillip is asking how to use this SDK while still being able to send non branch deep links to his application.

**Comment by ethanneff** [comment]
@chanphillip I am closing this ticket, feel free to reach out if you are still experiencing issues.
