### ISSUE TITLE
Clarification regarding "You must launch the app through Xcode for iOS"

### ISSUE THREAD

**Issue by adityasaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#271]
Hi. This line in the documentation `You must launch the app through Xcode for iOS` - does it mean that I cannot give the app to my users on an enterprise account and expect the universal links to work? If so, how do I test the functionality where all my beta test users are located in different countries. Please advise. Cheers!

**Comment by ethanneff** [comment]
Hello @adityasaxena,

To clarify: The `Development Team` gets removed whenever you rebuild your `cordova build`. I've tried using techniques such as `cordova build ios --developmentTeam="PW4Q8885U7";` without luck. For this reason, we recommend building with Xcode to set your `Development Team`.

As long your app has a `Development Team`, deep linking will work. 

You will need to make sure whenever you are creating your `.ipa` file for your enterprise app, that your have `Development Team` set through Xcode and all your [provisioning profiles properly configured](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingEnterpriseProgramApps/DistributingEnterpriseProgramApps.html).

Best,

**Comment by adityasaxena** [comment]
Hi @ethanneff 

For me: The `Development Team` does not get removed when I rebuild my `cordova build`. That is what I meant. The technique which you mentioned `cordova build ios --developmentTeam="PW4Q8885U7" works perfectly for me. How do I say that? I say that because after running `cordova build`, when I open the project inside XCode, I see the development team is already selected unlike what you show in your screenshot.

**Comment by jstoup111** [comment]
I'm noticing the same thing. The buttons all update as though the app is installed, but clicking on the link fails. Are there anything I can look at to resolve? Thanks!

**Comment by ethanneff** [comment]
The latest version of the Branch SDK no longer needs `xcode` to build your `development team` and `provisioning profiles`.
