### ISSUE TITLE
Incorrect doc property

### ISSUE THREAD

**Issue by NorthMcCormick** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#272]
Hello,

It looks like that in the example for creating a UC object the property 'contentIndexingMode' is being used but I'm pretty sure it should be 'contentIndexMode' as per the other half of the doc. 

It was just confusing until I realized it. If it's correct then can we get an explanation why?

**Comment by renesansz** [comment]
@NorthMcCormick ,
I apologize for the confusion, I've looked in to the native source code, it should be `contentIndexingMode`. I'll make a follow-up commit to fix the typo on the doc.

**Comment by ethanneff** [comment]
@NorthMcCormick Thank you for finding this issue with the docs. The docs have been updated.

@renesansz Thank you for making your pull request. It has been merged.
