### ISSUE TITLE
initSession not returning

### ISSUE THREAD

**Issue by Nostrus** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#274]
I recently updated my branch SDK, and trying to use it with Ionic 1.
After seeing the deprecated message for the global `window.DeepLinkHandler` function, I updated my code from

`Branch.initSession().then(function (response) {`
to
`Branch.initSession(function (response) {`

but it stopped working. I managed to trace it a bit, and found that it gets to the line
`return execute('initSession');`, but never returns. I had to revert back to using the global function, and it works fine (?).

I call initSession after `Branch.setDebug(DEVELOPMENT_MODE);` but that one seems to return fine.

**Comment by ethanneff** [comment]
Hello @Nostrus,

Thank you for reaching out.


#### So basically what is happening:
1) You update the Branch SDK
2) You got an error saying `DeepLinkHandler` is depreciated
3) You removed
  ```js
  // global function
  function DeepLinkHandler(data) {
    if (data) {
      alert('Data Link handler response: ' + JSON.stringify(data));
    }
  }
  ```
4) You added 
  ```js
  // Branch initialization
  Branch.initSession(function(data) {
    // read deep link data on click
    alert('Deep Link Data: ' + JSON.stringify(data));
  });
  ```
5) You click on your deep link
6) You are not getting data from the code in 4.

#### Can you please try the following?
1) Try the following [testing procedures](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios) so there is no cached version of your app
2) Give me your environment info ( `cordova plugin`, `cordova info`) and device info (iOS version, Android version)
3) Give me any relevant Branch code. Since you are using Ionic 1, the placement of `Branch.initSesssion` is important

I look forward to your response.

Best,

**Comment by Nostrus** [comment]
Hi @ethanneff, thanks for the quick reply!

So, when when seeing the deprecated message I still get back the initSession response saying
`{"+is_first_session":false,"+clicked_branch_link":false}`

After doing steps 3 and 4 I no longer manage to step into the callback of initSession, which I previously used to handle application logic (hiding main loader and navigating to subpage based on Branch data)

I don't click on any link in this scenario. I deleted my app from my Adnroid phone before reinstalling it, but same results.

Android version is 5.1.
`Branch.initSession(function (response) {` is being called inside `$ionicPlatform.ready(function () {`

I attached cordova info, hope this is enough information :)

[plugin-list.txt](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/files/717744/plugin-list.txt)
[cordova info.txt](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/files/717743/cordova.info.txt)

**Comment by renesansz** [comment]
@Nostrus , can you try executing your `Branch.initSession` inside the Angular `.run()` method instead of the `$ionicPlatform.ready`?

**Comment by Nostrus** [comment]
I tried this, and although my app doesn't halt anymore, the initSession callback is not called, either. Not sure anymore if it's supposed to be called in this new version. Same thing happens as I described originally:

> it gets to the line `return execute('initSession');` but never returns.

**Comment by ethanneff** [comment]
Hello @Nostrus,

Can you make sure `Branch` is defined in your app? You can do this by: launching your app to your device

**Comment by ethanneff** [comment]
Hello @Nostrus 

Can you make sure Branch is defined in your app? You can do this by:

- Connecting your device to your computer
- Launching your app
- Inspecting your app with Safari ([docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-show-console-logs))
- Typing in `Branch` into Safari console
- Example: ![image](http://i.imgur.com/nurrOiS.png)

Additionally, when you are initializing Branch, can you make sure you are doing it it both `deviceReady` and `resume`.



Best,

**Comment by Nostrus** [comment]
@ethanneff Sorry for not getting back on this. I started migrating my app to Ionic 2 and invested time in that instead. Will update my code to use the Typescript examples of your library and that will hopefully work just fine.
