### ISSUE TITLE
Update the guide

### ISSUE THREAD

**Issue by AndroideRob** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#275]
Please update the guide:

here: "document.addEventListener('resume', this.onDeviceReady, false);"
change this.onDeviceReady to this.onDeviceResume

// sample index.js
var app = {
  initialize: function() {
    this.bindEvents();
  },
  bindEvents: function() {
    document.addEventListener('deviceready', this.onDeviceReady, false);
    document.addEventListener('resume', this.onDeviceReady, false);
  },
  onDeviceReady: function() {
    app.branchInit();
  },
  onDeviceResume: function() {
    app.branchInit();
  },
  branchInit: function() {
    // Branch initialization
    Branch.initSession(function(data) {
      // read deep link data on click
      alert('Deep Link Data: ' + JSON.stringify(data));
    });
  }
};

app.initialize();

**Comment by ethanneff** [comment]
@AndroideRob Thank you for finding this. I will update the docs as soon as possible.

Best,
