### ISSUE TITLE
Why names different?

### ISSUE THREAD

**Issue by nicobytes** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#276]
The repo name: cordova-ionic-phonegap-branch-deep-linking
The id plugin: io.branch.sdk
The name plugin: branch-cordova-sdk

This create errors for use services like phonegap build or Ionic package:

For example with ionic the file package.json save all the plugins for then build in cloud:

```
{
      "id": "io.branch.sdk",
      "locator": "io.branch.sdk",
      "variables": {
        "BRANCH_KEY": "xxxx",
        "URI_SCHEME": "xxx"
      }
    }
```
 but io.branch.sdk not work for the name

Fetching plugin "io.branch.sdk@~2.4.9" via npm
Error: Failed to fetch plugin io.branch.sdk@~2.4.9 via registry.

**Comment by ethanneff** [comment]
Hello @nicobytes,

This was an error on our end whenever we first created the repo. We have plans to make it consistently `branch-cordova-sdk`, but we have to do regression test on everything to see how this will impact previous users who have older npm versions and want to update. 

For the time being, this is a low priority with no timeline for a correction.

When using `phonegap build` or `Ionic package`, are you still able to install the Branch Cordova SDK via the CLI? [install branch sdk](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#install-branch)

Best,
