### ISSUE TITLE
Error: Cannot read property 'branch-config' of undefined

### ISSUE THREAD

**Issue by BrainBacon** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#280]
I began integrating Branch.io into my Cordova project and ran across this build error. My `config.xml` file definitely has a `widget` element, but it seems like widget is resolving as undefined inside of `hooks/lib/configXmlParser.js` line 35:
```js
var ulXmlPreferences = configXml.widget['branch-config'];
```
I've tried this with the `config.xml` file inside of `testbed/config.xml` instead of my own as well and still had this error.

**Cordova**:
 - Version: 6.5.0
 - Installed platforms:
   - android: 5.2.2
   - ios: 4.2.1

**Comment by ethanneff** [comment]
Closing this ticket, handling this issue in support@branch.io
