### ISSUE TITLE
bnc.lt format still usable?

### ISSUE THREAD

**Issue by sfeast** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#284]
I don't see anything in the current README about using the old style links (bnc.lt), is this still supported & if so what should the config tag be for these?

**Comment by ethanneff** [comment]
Hello @sfeast,

The bnc.lt link domain should still be supported. You can find more information about this here:
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-optional-app-config

Ideally, you want to add the android-prefix `<android-prefix value="/WSuf" />` to your `<branch-config>

```xml
<!-- sample config.xml -->
<widget id="com.eneff.branch.example" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <!-- Branch -->
  <plugin name="branch-cordova-sdk" spec="~2.4.2" /> <!-- optional spec -->
  <branch-config>
    <branch-key value="key_live_ndqptlgXNE4LHqIahH1WIpbiyFlb62J3" />
    <uri-scheme value="cordovatestbed" />
    <link-domain value="testbed.app.link" />
    <ios-team-release value="PW4Q8885U7" />
    <ios-team-debug value="FG35JLLMXX" /> <!-- optional -->
    <android-prefix value="/WSuf" /> <!-- optional (for bnc.lt) -->
    <android-testmode value="true" /> <!-- optional (simulate installs) -->
  </branch-config>
```

May I ask, did you get a notification to update your Branch SDK? v2.5.0 is ideally meant for new users, so there may be some issues updating your SDK.

Regards,

**Comment by sfeast** [comment]
Thanks I'll give that a try - but should I be concerned about the relevance of android here since this is also for iOS?

No I didn't get a notification & I still haven't enabled universal links so hopefully this isn't an issue. My problem with using older SDKs is #283, I think something is getting pulled into old plugin release installs around the new format because the old format is breaking my builds - if that makes sense... if not just see #283 :)

**Comment by ethanneff** [comment]
Hello @sfeast,

I have tested `bnc.lt` and can confirm that the latest version of the Branch SDK supports `URI Scheme` deep linking.

Best,

**Comment by sfeast** [comment]
Perfect, thanks once again so much!
