### ISSUE TITLE
I can't show image when share moments with WeChat

### ISSUE THREAD

**Issue by phanthinh** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#287]
Hi all

I have using code below but still can not show image when share moments with weChat

`// optional fields
                          var analytics = {}

                          // optional fields
                          var properties = {
                            $desktop_url: res.url,
                            $android_url: res.url,
                            $ios_url: res.url,
                            $ios_wechat_url: res.url,
                            $android_wechat_url: res.url,
                            $og_title: TITLE_POPUP,
                            $og_description: desc,
                            $og_image_url: image,
                            more_custom: params,
                            even_more_custom: true,
                            this_is_custom: 1,
                            custom_integer: Date.now(),
                            custom_boolean: true,
                            custom_array: [1, 2, 3, 4, 5],
                            custom_object: { 'random': 'dictionary' }
                          }
                         branchUniversalObj.showShareSheet(analytics, properties, message);`

![img_2154 png](https://cloud.githubusercontent.com/assets/5910795/23543530/2fed90a8-0025-11e7-8d99-3346518918d9.jpg)

Who can help me for this?

Thanks

**Comment by ethanneff** [comment]
Hello,

So long story short, the Branch Cordova SDK is actually a wrapper around our iOS and Android SDKs. I tested the share functionality from Branch to WeChat on our iOS SDK and it is broken there too.
<img width="200" src="https://cloud.githubusercontent.com/assets/2933593/23559920/74987caa-ffed-11e6-978f-5f4beec567f6.jpg">

I am reaching out to my iOS team to see if they know of the issue and know of a workaround/solution.

I will keep you updated.

Best,

**Comment by ethanneff** [comment]
Hello again,

I wanted to let you know you have not been forgotten. This issue has been passed off to our iOS team and has been prioritized to be looked into.

After further testing, I can confirm the deep link preview image works with Facebook and Twitter. It does not work with WeChat. However, the deep link will still navigate into your app from WeChat (the image preview is just broken).

Thank you for your patience.

Best,

**Comment by ethanneff** [comment]
Hello, 

After further testing, this appears to be an issue with WeChat and not Branch. Images are broken whenever you share a link from Amazon to WeChat as well. 
<img width="200" src="https://cloud.githubusercontent.com/assets/2933593/23768377/a5f9c966-04c0-11e7-90a8-8bcf16a31d66.jpg" />

As mentioned in my last message, the deep link will still navigate into your app from WeChat (the image preview is just broken).

Thanks for finding this,
