### ISSUE TITLE
BNCServerInterface.processServerResponse has log but initSession isn't fired on iOS

### ISSUE THREAD

**Issue by chanphillip** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#288]
I'm using ionic 2. I've added calling Branch.initSession on deviceready and resume.
After clicking on the branch link on a webpage on chrome, it opens up the app but initSession didn't get fired...(it actually did fire occasionally)
I've turned on debug mode, in xcode I can see the BNCServerInterface.processServerResponse has log of the expected branch data.

Any advice for me to test in more detail?

**Comment by chanphillip** [comment]
I'm using branch 2.4.9
On android it's working perfectly though.

**Comment by ethanneff** [comment]
Hello,

I will investigate this. To help me troubleshoot, can you do some testing on your end as well?

1) Confirm this is not related to network connection loss? 
   - Make sure your device has a network connection when testing
2) Confirm the deep link data is being queued up? 
   - If the data is not coming in on first app open, does it come in on the second app open?
3) Provide me with the steps you do to replicate the issue.
   - Is it happening for all your deep links or only one?
   - Does it happen when the app is background or terminated?
   - Give me your `ionic info`
   - Give me your `ionic plugin`
   - Give me the device you are testing on info (e.g. iPhone 6s 10.1)

I will do some testing on my end in the meantime.

Best,

**Comment by chanphillip** [comment]
Hi @ethanneff Thanks for your help.
I just found a workaround, but not sure if it's a correct solution.
Anyways I'll give you the info.

1. Network connection was stable.
2. No. That's the strange part.
3. It happens when the app is in background. It has no problems during cold start (it involves authentication and some other loading procedures).
I'm testing on iPhone 7+ 10.2.1

After trying out for a while, finally I removed Branch.initSession on device resume and it was fixed.
I don't know if it is intended or not.

Ionic info:
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

I'm using WkWebView by the way. Don't know if it matters.
Ionic plugin:
```
com.cordova.plugins.cookiemaster 1.0.0 "CookieMaster"
com.instabug.cordova.plugin 1.0.0 "instabug-cordova"
cordova-custom-config 3.1.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-firebase 0.1.19 "Google Firebase Plugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-health 0.8.3 "Cordova Health"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-nativestorage 2.0.2 "NativeStorage"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-open-blank 0.0.2 "Open Blank"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.1 "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
es6-promise-plugin 3.0.2 "Promise"
io.branch.sdk 2.4.9 "branch-cordova-sdk"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
```

Thanks again

**Comment by ethanneff** [comment]
Hello @chanphillip,

It's good to hear you found a workaround. The reason why we recommend to use both `deviceReady` and `resume` is because there have been some instances where data was not passed on Android for Cordova. This may not be the case for Ionic. 

Regardless, we will continue investigating this as well as look into the compatibility of WKWebView.

Thanks,
