### ISSUE TITLE
Update plugin.xml id to be consistent with npm

### ISSUE THREAD

**Issue by djett41** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#290]
right now your npm id is branch-cordova-sdk but the plugin id is io.branch.sdk.  As a result, you have to add the plugin using branch-cordova-sdk but you have to remove the plugin using the plugin.xml id which is io.branch.sdk.

These id's should be consistent so theres no issues using the Cordova CLI

**Comment by ethanneff** [comment]
Hello,

I apologize for this, we are using [semantic release](https://github.com/semantic-release/semantic-release) for our versioning and it is not properly updating our `package.json` and `plugin.xml`. I have just pushed a new update to the SDK with theses values manually changed.

I will look into what went wrong and hopefully automate this process in the future.

I apologize for the inconvenience this may have caused. 

Thanks,

**Comment by ethanneff** [comment]
Hello @djett41,

I have made the following code modification so this error should not happen in the future:
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/98139def4ac9c2fc946d7161fc58f59036fa8130, https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/3b0c9ccccbc652384cb13b4b5e341e41800e8c57, https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/5071dcb333ecac305561af54aadfd083bb4afc79

Whenever you are importing Branch, be sure to add the `spec` field so you pull in the correct version:

exact: `<plugin name="branch-cordova-sdk" spec="2.5.0" />`
major+: `<plugin name="branch-cordova-sdk" spec="^2.5.0" />`
minor+: `<plugin name="branch-cordova-sdk" spec="~2.5.0" />`

Thank you for bringing this to our attention.

Best,

**Comment by djett41** [comment]
awesome thanks!
