### ISSUE TITLE
This plugin invalidates cordova's Entitlements-Debug.plist and Entitlements-Release.plist

### ISSUE THREAD

**Issue by djett41** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#299]
Hello I created a few issues related to the CLI for this plugin, we are having quite a few issues with the way the hooks modify the project files and hopefully you guys can address these.  Thanks a lot for your prompt replies by the way, I really appreciate it.

This issue is focused on the CODE_SIGN_ENTITLEMENTS property set within your xcodePreferences.js hook.  As of Cordova ios 4.3.0, Cordova sets this property in platforms/ios/cordova/build.xcconfig to point to the platforms/ios/{appName}/Entitlements-Debug.plist and Entitlements-Release.plist files...

Heres the property in build.xcconfig 
```
CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
```

This works with the Automatic code singing features from Xcode8, where the CLI will inject capabilities such as aps-environment etc.. so since your plugin modifies this path to the Resources folder, release builds will fail because they need to validate that the provisioning profile associated with config in build.json, matches the entitlements in the file, which it cant locate because of the change to CODE_SIGN_ENTITLEMENTS.  You can also see this in Xcode if you do a debug build and go to Xcode capabilities pane, you will see that your capabilities are all disabled..

This impacts anyone using Cordova CLI and automatic singing for cordova-ios version 4.3.0, which is the best practice.

I would recommend checking first for the CODE_SIGN_ENTITLEMENTS and if its set, merging your domains with the appropriate plist file (debug or release, or both?), otherwise maybe keep the Resources/{appName}.entitlements file.  Although honestly I would even recommend moving in the direction cordova did with the new entitlements location.

feel free to contact me regarding some of these issues, I may be able to help out since there are some other issues with the hooks wiping out manifest intent-filters that are not even associated with the branch plugin.. (put an issue in for that which got closed and still unresolved)

**Comment by ethanneff** [comment]
Hello Devin,

I have pushed #300 to fix the issue of overwriting intent filters within the `AndroidManifest.xml`. As for the `Entitlements` issue, I am currently researching the best solution to this problem. 

I will reach out as soon as I have more information, or if I need further information from you.

Thank you for your patience,

**Comment by djett41** [comment]
Nice @ethanneff thanks!

**Comment by ethanneff** [comment]
Hello again,

I was able to get Release Schemes working but it wasn't pretty. I had to do multiple attempts such as:

- **[fails]** pointing the `.xcodeproj` to `Entitlements-Debug.plist` and `Entitlements-Release.plist`
- **[fails]** updating the `build.json` with `"codeSignIdentity": "iPhone Developer"` for `release`
- **[fails]** removing the modification of `Entitlements-Debug.plist` and `Entitlements-Release.plist`
- **[fails]** relocating `/Resources/{app-name}.entitlements` to `./{app-name}.entitlements`
- **[works]** hardcorded `CODE_SIGN_IDENTITY = 'iPhone Developer'` for `.xcodeproj`

I understand this is not the ideal solution as it will prevent `release` `codeSignIdentity` modifications within the user's `build.json` configuration. However, I do have multiple apps in the App Store with Code Signing Identity set to `iOS Developer`.  Having this hard-coded should, hopefully, not be a problem.
<img width="300" alt="screen shot 2017-04-17 at 8 00 12 pm" src="https://cloud.githubusercontent.com/assets/2933593/25112863/b5dfc5a4-23a8-11e7-96c2-95d0c1326147.png">

I noticed you were looking for solutions [elsewhere](https://github.com/nordnet/cordova-universal-links-plugin/issues/8), but their code base was very similar to ours so I wasn't able to gain much insight. I think I'm going to push version `2.5.16` of the Cordova Branch SDK with the hard-coded change included. Wait and see to see if it work for other developers.

Thanks,
