### ISSUE TITLE
config.xml changes

### ISSUE THREAD

**Issue by Ziv-Barber** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#302]
In the past the config.xml was:

	<branch-config>
		<android-prefix value="myapp" />
		<ios-team-id value="12345678" />
		<host name="myapp.app.link" scheme="https" />
		<host name="myapp-alternate.app.link" scheme="https" />
	</branch-config>

And everything worked fine.
But you decided to change it in the last version.
I tried:

	<branch-config>
		<android-prefix value="myapp" />
		<branch-key value="key_live_ABCDEFG..." />
		<uri-scheme value="myapp" />
		<link-domain value="myapp.app.link" />
		<ios-team-prod value="12345678" />
		<ios-team-release value="12345678" />

		<ios-team-id value="12345678" />
		<host name="myapp.app.link" scheme="https" />
		<host name="myapp-alternate.app.link" scheme="https" />
	</branch-config>

I got an error:

Error: BRANCH SDK: Invalid "android-prefix" in <branch-config> in your config.xml

What I'm doing wrong?

**Comment by ethanneff** [comment]
Hello,

The only required values you need in your `config.xml` are: [docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app)
```xml
<!-- sample config.xml -->
<widget id="com.eneff.branch.cordovatestbed" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <!-- Branch -->
  <plugin name="branch-cordova-sdk" spec="^2.5.0" />
  <branch-config>
    <branch-key value="key_live_ndqptlgXNE4LHqIahH1WIpbiyFlb62J3" />
    <uri-scheme value="branchcordova" />
    <link-domain value="cordova.app.link" />
    <ios-team-release value="PW4Q8885U7" />
  </branch-config>
```

`<android-prefix>` is only needed if you have the legacy `bnc.lt` link domain. The format is `/WSuf`. [docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-optional-app-config)

If you are still having issues, you might need to reinstall Branch. [docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-errors)
```
# terminal
cordova plugin remove io.branch.sdk
cordova plugin remove branch-cordova-sdk
cordova build ios
```

Tell me if this fixes your issue.

Best,
