### ISSUE TITLE
No link in message when sharing with Facebook on Android 4.4

### ISSUE THREAD

**Issue by krysalead** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#307]
Hi,

Almost everything in the title.
When we share on old Android 4.4 phones using the branchUniversalObj.showShareSheet() method, everything is well passed to the method. Once the share sheet is shown click on Facebook, the message editor is open but without the link and the message that we have if we do the same with an email.

Thanks & regards

**Comment by ethanneff** [comment]
Hello,

Thank you for reaching out. I was able to test our Branch SDK with Android 4.2 and can confirm the deep link is not shared to Facebook. This looks to be a [bug of Facebook](https://developers.facebook.com/x/bugs/332619626816423/) as well as a limitation of the Facebook platform. [Pre-filling the share message is not allowed](https://developers.facebook.com/docs/apps/review/prefill). There seems to be a workaround where you install the Facebook SDK within your app and share the message that way. As for Branch and older versions of Android, this limitation is out of our control. 

Best,
