### ISSUE TITLE
Invalid "ios-team-release" error in config.xml

### ISSUE THREAD

**Issue by vitorfgsantos** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#308]
When I try to compile I get this error:

`Error: BRANCH SDK: Invalid "ios-team-release" in <branch-config> in your config.xml. Docs https://goo.gl/GijGKP`

What is "ios-team-release" and where I can get this parameter? I do not want to compile for iOS.

Installed platforms:
  android 6.1.2
Cordova version: 6.5.0

Thanks

**Comment by ethanneff** [comment]
Hello,

This is a known error and will be patched later today. In the meantime, you can add a dummy value in your `config.xml` so your app compiles. [docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app)

Thanks,

**Comment by vitorfgsantos** [comment]
Hmmm, thank you! =)

**Comment by ethanneff** [comment]
Hello again,

Please remove your Branch SDK and update it to `2.5.13` to fix this issue.

```bash
cordova plugin remove io.branch.sdk
cordova plugin remove branch-cordova-sdk
cordova build android
```

Thanks,

**Comment by Ziv-Barber** [comment]
We all try to find what is this secret ios-team-release setting
