### ISSUE TITLE
Why is it mandatory to use setIndentity to track user events?

### ISSUE THREAD

**Issue by epetre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#310]
The README seems to state that it's mandatory to call the Track User part (setIdentity).
I am wondering why it's mandatory and why can't the plugin simply use the device ID, ios IDFA or the Advertising ID for android?

**Comment by ethanneff** [comment]
Hello,

It is not mandatory to `setIdentity()` before `userCompletedAction()`. It's recommend because it allows you to relate your custom events to your users.

I will update the README to make it seem less mandatory.

Thanks.

**Comment by epetre** [comment]
It's just this part that confused me :

> Recommended to Track User before Track Event to associate custom events with a user

I didn't know if it's just recommended in the sense that it will work but I lose track of any previous data or if it's recommended to get a deeper Insight when we look at the dashboard.
