### ISSUE TITLE
Documentation about incompatibility

### ISSUE THREAD

**Issue by epetre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#311]
Since it's incompatible with most (maybe all) plugins that handle deeplinks,
is it safe to assume that:

```
Branch.initSession(function(data) {
    // read deep link data on click
});
```
is correctly called with **ALL** deeplinks, not just those that come from [Branch](https://branch.io/)?

**Comment by ethanneff** [comment]
Hello again,

Yes, the Branch Cordova SDK does not support other deep linking solutions ([Compiling: Incompatible Plugins](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-incompatible-plugins)). 

Additionally, you are correct in assuming the `Branch.initSession()` will handle other deep links. These non-Branch deep links will have the `data['+non_branch_link'] = true`
```js
Branch.initSession(function(data) {
    // read deep link data on click
});
```

Best,
