### ISSUE TITLE
Building the project for iOS seems to be creating an entitlements file directly under Resources for some reason.

### ISSUE THREAD

**Issue by epetre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#316]
I don't know why it's creating the entitlements in the Resources folder instead of adding them to the entitlements file that is already present at the root of my project. 

I am not sure if this is the new place for entitlements under XCode because I have trouble navigating Apple's documentation 😄.

But I can tell you that it's a big problem if you have 2 entitlements files, the one under Resources takes priority when deploying and everything that is not in it will simply not work.

**Comment by epetre** [comment]
It's my build settings that were pointing to 2 different paths. That this addon created an additional entitlement file and didn't care about the old one.

**Comment by razam217** [comment]
Hi @epetre, I'm seeing the same issue you mentioned above. Can you please tell we how did you fix it? I'm confused.
