### ISSUE TITLE
Missing : Commerce event tracking

### ISSUE THREAD

**Issue by PetruMagdeleine** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#320]
Hi,

I just find out that there is no implementation for Commerce event tracking? Is it missing ?
I found it in iOS, Android and Web Branch SDK.
Something similar than that: 
https://dev.branch.io/getting-started/user-value-attribution/guide/web/#commerce-event-tracking

**Comment by ethanneff** [comment]
Hello hello,

The Branch Cordova SDK currently does not support Commerce event tracking. I will add this to the backlog and try to get this developed as soon as possible. I will reach out as soon as it is available.

Thank you for your patience,

**Comment by ethanneff** [comment]
Hello again,

We have added [commerce tracking](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#track-commerce) to our SDK. Please update your [Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to use this feature.

Thanks,
