### ISSUE TITLE
Query Parameter getting stripped off

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#322]
I have a URL coming in through an email with the scheme like this:

`<themename>/447/?thread=pv8wivm9gy-40587 `

When the url gets to the app in the `data.deeplink_path` in the` window.DeepLinkHandler`, the query parameter is missing.  This used to work, but I recently updated and it seems to have broken.  

URLs without the query parameters work fine.

**Comment by gabaum10** [comment]
I just verified testing via the smart banner as well.  The data passed to the deelink_path is correct.  The query param is getting lost somewhere internally in the plugin as far as I can tell...

**Comment by gabaum10** [comment]
Thinking perhaps it was because I was using the legacy window.DeepLinkHandler, I updated my code to use the initSession(data) function instead.  I also updated to the latest version of the plugin (2.5.16).   None of that seemed to help the issue.

**Comment by ethanneff** [comment]
Hello again,

I have done the following tests with successful opening and passing of data into the app:

- **Deep link data**
  - https://cordova.app.link/DuOGQt8tNC
  - branchcordova://open?link_click_id=link-387624024139754837

- **Deep link data + query data**
  - https://cordova.app.link/DuOGQt8tNC?HELLO=WORLD

- **Query data only**
  - branchcordova://content/123
  - branchcordova://?HELLO=WORLD
  - branchcordova://content/123?HELLO=WORLD

Can you please provide me with some more information about how you are testing so I can simulate the issue on my end? Specifically, the steps including the deep link you are clicking, the data you want to pass, the device you are using, and any relevant Branch code within your app.

Thanks,

**Comment by gabaum10** [comment]
Sorry, I just saw this.  I bizarrely didn't get a notification...

I realized it was something we were doing.  We were trying to pass the raw web URL into the app via the deeplink_path parameter, but we weren't passing the query string in!  That's why it wasn't there.
