### ISSUE TITLE
Multiple Dex Exception on latest build branch-cordova-sdk 2.5.16

### ISSUE THREAD

**Issue by jragrag** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#326]
Hi,
I have a good running app when I added branch sdk then this issue comes during build:
**Here's some of my output log:**
:mergeReleaseShaders

:compileReleaseShaders

:generateReleaseAssets
:mergeReleaseAssets

:transformClassesWithDexForRelease
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

BUILD FAILED

Total time: 29.688 secs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Here's my project.properties:**
target=android-24
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-ads:+
cordova.gradle.include.1=cordova-plugin-badge/app-badge.gradle
cordova.system.library.2=com.facebook.android:facebook-android-sdk:4.8.+
cordova.system.library.3=com.google.android.gms:play-services-analytics:+
cordova.system.library.4=com.google.android.gms:play-services-location:+
cordova.system.library.5=com.android.support:appcompat-v7:24.1.0
cordova.system.library.6=io.branch.sdk.android:library:2+

**My Plugin List:**
android-camera-permission 1.0.0 "Android Camera Permission"
branch-cordova-sdk 2.5.16 "branch-cordova-sdk"
com.phonegap.parsepushplugin 0.9.0 "ParsePushPlugin"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-base64-to-gallery 4.1.1 "base64ToGallery"
cordova-plugin-admobpro 2.24.0 "AdMob Plugin Pro"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-audio-recorder-api 0.0.1 "AudioRecorderAPI"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-browsersync 0.1.1 "cordova-plugin-browsersync"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-google-analytics 1.7.5 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-locationservices 2.1.0 "Google Location Services for Cordova - Android"
cordova-plugin-media 2.3.0 "Media"
cordova-plugin-request-location-accuracy 2.2.0 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
cordova-sqlite-storage 1.4.6-pre6a "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.4.2 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Any suggestion?**
Ionic version: 2.1.18
Cordova version: 6.4.0
Node version: 5.6.0

**Comment by ethanneff** [comment]
Hello,

Unfortunately, this issue is unrelated to Branch. The `Multiple Dex Exception` happens whenever your app is too big ([over 64k methods](https://developer.android.com/studio/build/multidex.html)). Given the number of plugins you have in your app, I can understand why you are seeing this error. You might want to investigate other solutions to fix this problem ([for example](https://www.npmjs.com/package/cordova-plugin-multidex)).

Thanks,
