### ISSUE TITLE
iOS: Instead of opening application directly, Branch.io takes me to safari

### ISSUE THREAD

**Issue by sebasnavarrete** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#329]
Hi, I just implemented branch in my ionic 1 application, but I have a problem with the deeplink "xxxx.app.link", in android it works perfect, in the click it opens the app, but in ios it takes me to safari - doesn't recognize the installed app (in both cases the app Is installed).

After opening safari, if I manually open the app it recognizes the link data.

config.xml
`
<plugin name="branch-cordova-sdk" spec="^2.5.0"/>
    <branch-config>
        <branch-key value="key_live_mdxxxxxxxxxxx"/>
        <uri-scheme value="xxxxxx"/>
        <link-domain value="xxxxx.app.link"/>
        <ios-team-release value="........"/>
    </branch-config>
`
I am completely sure that the branch-config data is correct.

i tried to reinstall the plugin but it doesn't work, i tried with old version but doesn't work.

I do not know what else to do to fix that issue. 

Thanks for your help.

**Comment by razam217** [comment]
Hi @sebasnavarrete , I'm not a part of branch.io dev team, but I was also stuck while configuring, so got a little idea. 
Have you tried removing ios platform from ionic app and adding it back? 
- cordova platform remove ios
- cordova platform add ios
After doing this run cordova build ios, and check if xcode shows its configurations in info.plist. Also you will have to enable Associated Domain capability and add it to application identifier (developer.apple.com).

**Comment by sebasnavarrete** [comment]
Hello razam217, thanks for your answer. Yes i have tried that and it does not work :(

**Comment by ethanneff** [comment]
Hello hello,

Ideally, you should not need to rebuild your platform (`cordova platform remove ios && cordova platform add ios`) for Branch to work. I wrote the scripts so it should work off a build (`cordova build ios`). It is concerning that you had to do this. I will create some sample apps to see if I can replicate that issue.

For the Ionic 1 issue, I created a quick sample app and was not able to replicate your issue. Typically for Universal Linking issues, you want to make sure you:
- Make sure your [app settings](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app) match your [branch settings](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-branch)
- Run your app through Xcode at least once (to set your developer team)
- Test on a device (simulators behave finicky every now and then)
- Go through this [testing procedure](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios) to make sure your device is not caching an old state of your app

Thanks,
