### ISSUE TITLE
Branch.io init returning 400 bad request

### ISSUE THREAD

**Issue by razam217** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#330]
Branch.io API is returning 400 error with this response:
{
"error": {
"has_nfc": "wrong field type",
"screen_height": "wrong field type",
"has_telephone": "wrong field type",
"screen_width": "wrong field type",
"screen_dpi": "wrong field type",
"bluetooth": "wrong field type",
"update": "not a valid option"
}
}
Please also have a look at attached image.
<img width="1068" alt="screen shot 2017-05-27 at 7 08 25 am" src="https://cloud.githubusercontent.com/assets/9858462/26517853/e8bd0f28-42ba-11e7-9604-2b634b0608f4.png">

**Comment by ethanneff** [comment]
Hello Muhammad,

I apologize for the delay. We had an outage late Friday which caused our API to throw out 400 errors. I saw you reached out to our support and received from feedback there. It looks like updating the Branch SDK within your app resolved the issue. Can you confirm this is correct? If not, I can look into the problem.

Thanks,

**Comment by razam217** [comment]
Hi @ethanneff,
No problem and Thanks for resolving our issue. 
Updating SDK was also fixing the problem, but the applications that were already on App Store/Play Stores, were using old SDK. So your back end team fixed that 400 issue. 

Thanks again.
