### ISSUE TITLE
Deeplink from app content

### ISSUE THREAD

**Issue by YaroslavG** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#332]
Hello guys,
It is possible to read deep link from content when app open?

**Comment by ethanneff** [comment]
Hello,

Yes. You can [pass any key-value data](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#create-deep-link) you want with your deep links and [read that data](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#read-deep-link) once the user enters your app.

You can find more information about [creating links](https://dev.branch.io/getting-started/creating-links/overview/) and [configuring links](https://dev.branch.io/getting-started/configuring-links/guide/) in our main docs.

Thanks,

**Comment by YaroslavG** [comment]
Thanks for your answer
