### ISSUE TITLE
Associated domain capabilities not copied to Xcode

### ISSUE THREAD

**Issue by imrvshah** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#333]
Hi, 

When I do `cordova prepare` or `yarn cordova:reset` or `ionic reset state` does not copy the links to Associated Domains but when I do `ionic build ios` it does copy links. 

So, can we copy that when we do `yarn cordova:reset` ?

**Comment by ethanneff** [comment]
Hello Ravi,

Right now our hooks to generate the Associated Domain are on `before_prepare` ([code](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/plugin.template.xml#L46)). I will investigate if I can add theses hooks to `yarn cordova:reset` as well. 

A little forewarning, it will probably be a week before I can get this implemented as I'm limited on bandwidth as I'm the moment.

Thanks,

**Comment by harshabonthu** [comment]
I was able to replicate this bug using below steps:-

Create new cordova project
`cordova new branchbug`

Add iOS platform
`cordova platform add ios --save`

Add branch plugin
`cordova plugin add ../cordova-ionic-phonegap-branch-deep-linking --save`

Now to replicate blank slate env or new machine setup

- Delete platforms and plugins folders and do cordova prepare
`rm -rf platforms && rm -rf plugins && cordova prepare`

Now open xcode project and check the capabilities section
- Result: Associate domain capabilities are not enabled
- Expected: Associate domain capabilities should be enabled

**Comment by ethanneff** [comment]
I merged @harshabonthu's pull request.

@imrvshah can you please [update Branch to the latest SDK version](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to fix this issue?

Thanks,
