### ISSUE TITLE
Android build failure after upgrade to 2.6.6

### ISSUE THREAD

**Issue by vivekpd15** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#350]
On updating the plugin to the latest 2.6.6. The cordova android build failed with the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForArmv7Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzanq.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.274 secs
Error: /Users/admin/Desktop/cordova-proj/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
warning: string 'com_facebook_loginview_log_in_button_continue_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_in_button_continue_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_m2gender' has no default translation.
warning: string 'com_facebook_send_button_text_f1gender' has no default translation.
warning: string 'com_facebook_send_button_text_m2gender' has no default translation.
warning: string 'com_facebook_share_button_text_f1gender' has no default translation.
warning: string 'com_facebook_share_button_text_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_m2gender' has no default translation.
warning: string 'com_facebook_tooltip_default_f1gender' has no default translation.
warning: string 'com_facebook_tooltip_default_m2gender' has no default translation.

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForArmv7Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzanq.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ethanneff** [comment]
Hello @vivekpd15,

The only Google dependency the Branch SDK uses is `com.google.android.gms:play-services-appindexing:9.+`. We use this for better matching with Chrome Tabs. It looks like one of your plugins is fighting with ours. 

It looks like you are getting a lot of `com_facebook` errors. Can you please give me output for `cordova plugins` as well as `cordova info` so I can investigate?

Thanks,

**Comment by rabee1981** [comment]
I am also facing this issue
cordova plugins :
`branch-cordova-sdk 2.6.6 "branch-cordova-sdk"
com.phonegap.plugins.facebookconnect 1.7.1.3 "Facebook"
cordova-admob-sdk 0.8.0 "AdMob SDK"
cordova-plugin-admob-free 0.10.0 "Cordova AdMob Plugin"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"`

**Comment by ethanneff** [comment]
I've made a change to the `build.gradle` which the Branch Cordova SDK relies on. This should fix the Android dependency errors you are seeing. 

I would recommend [updating the Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) and going through the [testing guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-android) to make sure you are using the latest Branch Cordova SDK.

Thanks,
