### ISSUE TITLE
BranchSDK not found

### ISSUE THREAD

**Issue by amovsesy** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#356]
I recently updated to the latest branch sdk and now none of my branch links work. As I was playing with it I got the following error in xcode:

`
2017-08-16 20:49:23.238643+0200 Zently[3020:1033056] CDVPlugin class BranchSDK (pluginName: BranchSDK) does not exist.
`
`
2017-08-16 20:49:23.238727+0200 Zently[3020:1033056] ERROR: Plugin 'BranchSDK' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
`
`
2017-08-16 20:49:23.238820+0200 Zently[3020:1033056] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["BranchSDK1637249983","BranchSDK","initSession",[]]
`

**Comment by ethanneff** [comment]
Hello,

Depending on how old your last version of the Cordova Branch SDK, you might need to follow this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to reinstall Branch (we had an SDK package name rename last year).


Thanks,

**Comment by amovsesy** [comment]
I did all these steps. Everything compiles great and it builds, but when I deploy my app to my phone I see the errors above. Before I get those errors I see the following on startup in the console of xcode:
`
017-08-16 21:18:55.440528+0200 Zently[3076:1044851] CDVPlugin class BranchSDK (pluginName: branchsdk) does not exist.
`
`
2017-08-16 21:18:55.440548+0200 Zently[3076:1044851] [CDVTimer][branchsdk] 0.038981ms
`

**Comment by ethanneff** [comment]
Hello again,

Are you getting errors whenever you run Branch methods? For example, are you able to successfully generate a Branch deep link within your app? (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#create-deep-link)

I ask because it seems like the Branch SDK is successfully loaded into your app:

Your logs: (0.038981ms)
```
017-08-16 21:18:55.440528+0200 Zently[3076:1044851] CDVPlugin class BranchSDK (pluginName: branchsdk) does not exist.
2017-08-16 21:18:55.440548+0200 Zently[3076:1044851] [CDVTimer][branchsdk] 0.038981ms
```

My logs: (0.603974ms)
```
2017-08-16 13:13:46.684 Branch Testing[834:286263] Using UIWebView
2017-08-16 13:13:46.686 Branch Testing[834:286263] [CDVTimer][handleopenurl] 0.060022ms
2017-08-16 13:13:46.687 Branch Testing[834:286263] [CDVTimer][intentandnavigationfilter] 1.362979ms
2017-08-16 13:13:46.687 Branch Testing[834:286263] [CDVTimer][gesturehandler] 0.048995ms
2017-08-16 13:13:46.688 Branch Testing[834:286263] [CDVTimer][branchsdk] 0.603974ms
2017-08-16 13:13:46.688 Branch Testing[834:286263] [CDVTimer][TotalPluginStartup] 2.442002ms
```

I have a feeling the first error you are getting is a race condition, but the Branch SDK is eventually being loaded into your app.

**Comment by amovsesy** [comment]
@ethanneff I tried with the latest code and am still seeing the issue. I am getting the error multiple time so I don't think the branch SDK is ever loading. The first time I see that error does seem like a race condition where it doesn't load, but then on ready i run Branch.init and it still says the plugin is not found.

**Comment by amovsesy** [comment]
Anyone with insights on the issue, I have not been able to get this to work and the current version of the branch plugin I am using is crashing on the devices of some of our users so I'd like to figure out a path forward for us.

**Comment by ethanneff** [comment]
Hello again,

I am still unable to reproduce this on my end. However, I was able to look around the internet and found some possible solutions:

1. Don't put a space in your application name within `config.xml` ([link](https://stackoverflow.com/questions/21792101/plugin-not-found-or-is-not-a-cdvplugin-check-your-plugin-mapping-in-config-xml))
    - `<name>My Cordova Test</name>`
    - `<name>MyCordovaTest</name>`

2. Your platform may be corrupted. Rebuild it ([link](https://stackoverflow.com/questions/19221620/cordova-3-1-0-plugin-not-found-or-is-not-a-cdvplugin))
    - `cordova platform remove ios`
    - `cordova platform add ios`

3. Upgrade your outdated PhoneGab build ([link](https://stackoverflow.com/questions/19221620/cordova-3-1-0-plugin-not-found-or-is-not-a-cdvplugin))
    - `npm update -g cordova`

4. Rebuild the Branch SDK. There is a chance the `.h` and `.m` files were not installed the first time `/plugin/branch-crodova-sdk/src/ios` ([link](https://stackoverflow.com/questions/16839110/error-plugin-not-found-or-is-not-a-cdvplugin-check-your-plugin-mapping-in))
    - [Updating the Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk)

Thanks,

**Comment by jans-y** [comment]
Hello, I am having the same issue.

I do not understand update guide -> https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk , you posted earlier in this thread.

Shoudln't I run "ionic cordova plugin add branch-cordova-sdk" ?

If not, how should I install the plugin?

Thank you.

**Comment by ethanneff** [comment]
The Branch SDK is installed from `<plugin name="branch-cordova-sdk" spec="^2.6.0" />` in your `config.xml` whenever you do a `cordova build ios` or `cordova build android`.

You should not have to install the Branch SDK  from `ionic cordova plugin add branch-cordova-sdk`.

Thanks,

**Comment by HardikDG** [comment]
@ethanneff Can you provide exact steps for the installation of Branch SDK for an Ionic project? 

As per your previous comment, we should not run the command `ionic cordova plugin add branch-cordova-sdk`. We should have installed automatically with the ionic build command with the other parameters specified in the <branch-config>.

But In the another post [Adding plugin issue](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/357) in the same week, you have written steps like

```
cordova platform rm ios
cordova plugin rm phonegap-plugin-push
cordova plugin rm branch-cordova-sdk
cordova plugin add branch-cordova-sdk   \\ <--- Add a plugin via cordova plugin add
cordova plugin add phonegap-plugin-push
cordova platform add ios
cordova build ios
cordova run ios --device
```

So I am confused with what is the correct and better flow installation of the Branch SDK integration in the Ionic project. If you can provide some more details on installation it will be great.

**Comment by ethanneff** [comment]
Hello @HardikDG, 

Yes, there are two ways to install Branch:
- add `<plugin name="branch-cordova-sdk" spec="^2.6.0" />` to your `config.xml` and then run `cordova build ios` or `cordova build android`
- runs `cordova plugin add branch-cordova-sdk` which injects `<plugin name="branch-cordova-sdk" spec="^2.6.0" />` into your `config.xml` and installs the branch 

Both options will work, but I don't recommend the 2nd option because Branch used to be installed via `cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=xxxx --variable URI_SCHEME=xxxx;` which no longer works. To prevent confusion, I try not to publicize the 2nd option anywhere. 

For Ionic projects, generally the best way to integrate Branch is from the [Getting Started Guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#getting-started) on the Readme.

Thanks,

**Comment by HardikDG** [comment]
Okay, Thanks for the quick reply. I have tried with the first option and it is working properly as expected.

For the knowledge, If I use the second method Branch will take the 'BRANCH_KEY' and 'URI_SCHEME' from <branch-config> in config.xml right? As variable installation method is not working now.

**Comment by ethanneff** [comment]
Glad you got it working! You are correct, everything is pulled from the config.xml now.

**Comment by kleeb** [comment]
Sounds similar for me. The latest cordova, cordova-ios, completely fresh new project craeted from Bitrise pipeline

```
In file included from /Users/vagrant/git/platforms/ios/app/Plugins/branch-cordova-sdk/BranchSDK.m:1:
/Users/vagrant/git/platforms/ios/app/Plugins/branch-cordova-sdk/BranchSDK.h:4:9: fatal error: 'Branch.h' file not found
#import "Branch.h"
        ^~~~~~~~~~
1 error generated.
```

**Comment by echo-branch** [comment]
@kleeb Please open a new ticket for your issue.  It's likely different from the old closed issue.
