### ISSUE TITLE
Adding plugin removes aps-environment entitlement from subsequent Xcode archives

### ISSUE THREAD

**Issue by dkhaupt** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#357]
I'm working with an Ionic 3 app that previously had push notifications configured properly for both dev and production- the capability is added in Xcode, and the proper App ID, certificates, and provisioning profiles have been setup.

I'd also like to use the Branch plugin for the many features branch.io offers- however, when I install it, my entitlements become misconfigured when archiving for release. Specifically, archives I create after installing the Branch plugin no longer have the aps-environment entitlement. 

I've tried every idea I can find to try and restore that entitlement, but nothing works. Here's what I've attempted:

1. Restarting Xcode
2. Flipping the Push capability to off then back on (this is the most common advice)
3. Adding the "production" entitlement manually
4. Changing my codesigning account to something invalid for this app then changing back
5. Turning off Xcode management of codesigning, then turning it back on (this also has worked for other issues before and is a common piece of advice)
6. Redownloading profiles for my development account in Xcode (through Xcode -> Preferences -> Accounts -> Download All Profiles)
7. Redownloading the provisioning profile manually
8. Redownloading & readding the relevant cert manually

None of this has worked. I've been through this entire cycle twice now, and the only thing that works to get entitlements restored is removing the iOS platform and re-adding it.

This Github [issue](https://github.com/dpa99c/cordova-custom-config/issues/101) for a different plugin notes that the branch-cordova-sdk plugin changes entitlements, but I can't tell if the eventual fix applies here. After poking around the branch-cordova-sdk plugin files, I see that there is definitely manipulation of the entitlements going on- also referenced in a few Github issues (#316 #299 #252), but I don't think any of these have commits associated. I'm unclear on if this code is attempting to preserve the aps-environment entitlement, since I think that's only added when archiving.

The workaround of removing/re-adding the iOS platform has the side effect of breaking the Branch plugin functionality- tapping Branch links sometimes opens the App Store even when the app is installed, but mostly opens the app which closes/crashes immediately (Which I ran into during initial integration and [posted](https://stackoverflow.com/questions/45685070/branch-link-opens-ionic-3-app-which-immediately-closes-before-loading) on StackOverflow and seems to be related to the plugin not being available to handle the links properly).

Any advice here would be greatly appreciated, as it seems right now that I'll have to choose between push notifications and full branch.io functionality.

Here's my ionic info:

> cli packages: (/Users/david/Source/app/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

>global packages:

    Cordova CLI : 7.0.1 

>local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

>System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v7.4.0
    npm               : 4.0.5 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by ethanneff** [comment]
Hello,

Thank you for reaching out. 

If I remember correctly, we overrode the following files to make the Branch SDK backwards compatible with Cordova 5, 6, and 7.  
- `platforms/ios/APP_NAME/Resources/APP_NAME.enttitlements`
- `platforms/ios/APP_NAME/Entitlemens-Debug.plist`
- `platforms/ios/APP_NAME/Entitlemens-Release.plist`

However, overriding is probably the wrong technique for this scenario. In order to preserve the aps-environment entitlement, can you please give me an example of your files (listed above) before Branch overrides them? This will aid me in understanding what is being changed and what test cases I need to build around.

Thanks.

**Comment by dkhaupt** [comment]
Sure. None of them are long, so here's the content of each (I don't have a /Resources directory in /platforms/ios/APP_NAME, by the way):

> platforms/ios/APP_NAME/APP_NAME.entitlements

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:APP_NAME.app.link</string>
		<string>applinks:APP_NAME-alternate.app.link</string>
		<string>applinks:APP_NAME.test-app.link</string>
		<string>applinks:APP_NAME-alternate.test-app.link</string>
	</array>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.APP.APP</string>
	</array>
</dict>
</plist>
```

> platforms/ios/APP_NAME/Entitlements-Debug.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>development</string>
  </dict>
</plist>
```

>platforms/ios/APP_NAME/Entitlements-Release.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>production</string>
  </dict>
</plist>
```

Let me know if you'd like anything else. I may try reinstalling Branch again and checking these files to see how they changed. Normally I'd be happy to do so, but it's a bit disruptive to have to remove and re-add my iOS platform every time I do this. Getting Branch working is a priority for my company, though, so I'll see what I can do.

**Comment by dkhaupt** [comment]
I removed & re-added the Branch plugin- as I've seen before, this makes handling of deeplink clicks, when the app is installed, work correctly. However, I'm still seeing the lack of the production aps-environment entitlement when creating archives.

After re-adding the Branch plugin, my APP_NAME.entitlements file was unchanged, but Entitlements-Debug.plist and Entitlements-Release.plist files each had the same key added:

```
    <key>com.apple.developer.associated-domains</key>
    <array>
      <string>applinks:playsideline.app.link</string>
      <string>applinks:playsideline-alternate.app.link</string>
    </array>
```
I would think Ionic app developers also using Branch would very likely use push notifications as well (via the cordova-phonegap-push plugin), so perhaps there's some workaround here.

Considering that the aps-environment key is still in Release-Entitlements.plist after Branch plugin installation, does that mean there's something going on at buildtime?

**Comment by ethanneff** [comment]
Hello @dkhaupt,

Thank you for all this information. I have a feeling there could be something in our code which is making Branch behave incorrectly with other Cordova plugins (such as Push Notifications). I am still investigating the issue, but if you can provide me with your output to `cordova plugin`, this will also be helpful in my attempt to debug this issue.

Thanks,

**Comment by dkhaupt** [comment]
Thanks a lot for taking a look! Here's that output:
```
branch-cordova-sdk 2.6.8 "branch-cordova-sdk"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-mixpanel 3.1.0 "Mixpanel"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onymos-plugin-chat 1.0.5.1 "OnymosChatComponent"
phonegap-plugin-push 2.0.0 "PushPlugin"
```

**Comment by dkhaupt** [comment]
I removed & re-added the iOS platform to get everything back to working, and decided to try adding that `associated-domains` key to the Debug-Entitlements.plist and Release-Entitlements.plist files manually. This was an attempt to get the already-installed Branch plugin to work instead of crashing the app when I tap a Branch link. 

The next archive I ran looked as expected (all entitlements) so I built to my phone & tapped a Branch link. This time, the debugger stopped on the exception causing the app to crash- it happens in Branch.m, in line 10 of the `setBranchKey` method. The test that the key is of type `NSString` fails  because the key is `nil` (pretty sure this is right- apologies on terminology, I'm not a native iOS developer).

I haven't noticed issues with other plugins after removal + readdition of platforms, so could there be some hook missing that would pick up the key from `config.xml` and set it in the Branch plugin config? I looked for a file in the plugin directory where I could set the key manually, but wasn't successful.

**Comment by dkhaupt** [comment]
@ethanneff I was looking through the plugin code related to entitlements and noticed something interesting in `enableEntitlements.js`, specifically the `enableAssociatedDomains()` function.

In a previous message, I mentioned that I don't have a `platforms/ios/APP_NAME/Resources/APP_NAME.entitlements` - that entitlements file is directly in the `platforms/ios/APP_NAME/` directory.

It looks like `enableAssociatedDomains` is attempting to use a file in that `Resources/` directory:
```
var entitlementsFile = path.join(preferences.projectRoot, 'platforms', 'ios', preferences.projectName, 'Resources', preferences.projectName + '.entitlements')
```
See how 'Resources' is hardcoded into the path? I'm going to try removing it, however I'm not entirely sure which steps I need to take once I've done so. As I described above, typically the only thing I can do to restore my Branch plugin functionality (after resetting the iOS platform) is to remove and re-add it- but if I edit this file, I think removing the plugin will wipe it out. 

Any thoughts here?

**Comment by ethanneff** [comment]
Hello again,

Good find! I understand this is a problem with our SDK. Our entitlements are not cooperating correctly with other plugins and will do my best to find a solution. Unfortunately, my bandwidth is limited this week and I will not be able to develop a fix until next week.

In the meantime, you can try tinkering around with the source code within `plugins/branch-cordova-sdk/src/scripts/ios/updateAssociatedDomains.js` or you can wait for a new SDK release whenever I find time to develop a solution.

I apologize for this inconvenience. I will update this Github issue as soon as the fix is live.

Thanks,

**Comment by ethanneff** [comment]
Hello David,

I wanted to let you know I am looking into the issue. The problem seems to be how `phonegap-plugin-push 2.0.0` and `branch-cordova-sdk 2.6.0` store their entitlements: 
- `phonegap-plugin-push` platforms/ios/APP_NAME/APP_NAME.entitlements
- `branch-cordova-sdk` platforms/ios/APP_NAME/Resources/APP_NAME.entitlements

This is causing the `phonegap-plugin-push` to take precedence over the `branch-cordova-sdk` which is causing the Associated Domains to never be enabled (meaning deep linking will not work). 

I am not an expert with `phonegap-plugin-push`, but in my testing, I have noticed that the platforms/ios/APP_NAME/APP_NAME.entitlements only get created after selecting Push Notifications as a capability within Xcode - meaning this file is not generated from a hook like the `branch-cordova-sdk` entitlements. Because of this, I am toying around with the idea of removing the `/Resources` dependency from the `branch-cordova-sdk`. It seems to working, but I am going to do some more regression tests tomorrow before pushing the code change tomorrow (because I have a feeling removing this will break backwards capabilities of the SDK). 

Thank you for your patience.

**Comment by ethanneff** [comment]
Hello again,

I'm pretty confident that `2.6.11` will fix the issue you are having. Please go through this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Branch SDK.

When debugging the issue, I noticed that the two SDKs are referencing the iOS entitlements in separate locations. I added both locations to the Branch SDK so our SDK will cooperate with theirs. Furthermore, I have confirmed that our SDK will not override the entitlements of their SDK. To test this, I did the following:

  - install
    ```
    npm i -g cordova phonegap
    rm -rf my-app
    phonegap create my-app --template phonegap-template-push
    cd my-app
    ```

  - test

    ```
    cordova platform rm ios
    cordova plugin rm phonegap-plugin-push
    cordova plugin rm branch-cordova-sdk
    cordova plugin add branch-cordova-sdk
    cordova plugin add phonegap-plugin-push
    cordova platform add ios
    cordova build ios
    cordova run ios --device
    ```
  - enable `Push Notifications` within Xcode -> App Name -> Capabiltities
  - run on device
  - see `phonegap-plugin-push` push notification entitlements remain enabled after recompile
       
    ```
    cordova run ios --device
    ```

Hope this works for you!

Thanks,

**Comment by dkhaupt** [comment]
Thanks for taking a look at this, Ethan! I'll be working today/tomorrow on updating the plugin and testing it with the rest of my plugins. I really appreciate the assistance!

**Comment by codinronan** [comment]
To anyone running across this, I believe the latest SDK does this correctly but just in case it doesn't, make sure you have Xcode configured to use your entitlements in `platforms/ios/APP_NAME/APP_NAME.entitlements`, and NOT the entitlements files inside the `APP_NAME/Resources/` folder. These have ONLY the branch applinks, and nothing else. Your full entitlements are in the outer folder.

This will lead the to infamous 
`"Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement... Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. "` 

error from the App Store when you go to upload your app. Just make sure you're grabbing the outer entitlement file, not the inner one and it will fix it.

**Comment by scottwb** [comment]
In case this helps anyone else...

My situation was slightly different. I have the latest version of Branch for Ionic (2.7.1), so was assuming this fix was in, but I am still on XCode 8.2. I'm also on Ionic 2. Also, I have a setup where I prefer my build machine to do a clean install of the platform so manually changing the Ionic-generated XCode settings to turn on Push Notifications or change the location of the entitlements file it uses are not an option. With all this, I was still seeing all the problems above.

My solution, (er hack), was to script adding the entitlement to the entitlements file in my build string. So, in my build script, just after running `ionic state reset`, before my build script calls `ionic build ios --prod --release --device`, I've added this:

```
if grep -q aps-environment platforms/ios/APP_NAME/Resources/APP_NAME.entitlements; then
  # I guess it already has the aps-environment entitlement...
  echo "Push Notification Entitlement already in place."
else
  echo "Adding Push Notification Entitelment."
  sed -i '' '/^[[:space:]]*<dict>/a\'$'\n''\'$'\t''<key>aps-environment<\/key>\'$'\n''\'$'\t''<string>development<\/string>\'$'\n''' platforms/ios/APP_NAME/Resources/APP_NAME.entitlements
fi
```

Kinda hacky, but got my automated builds to work again w/o human intervention for now, until I can investigate updating to XCode 9, Ionic 3, etc... YMMV...

**Comment by matthew-valenti** [comment]
@scottwb - thanks for sharing this clever hack! This hack worked in Ionic3 for creating an iOS binary using IonicPro. We needed to work around an issue where a cordova plugin was deleting the push entitlement during the build.

/ios_push_entitlement_hack.sh
```
#!/bin/bash
if grep -q aps-environment platforms/ios/MyAppName/Resources/MyAppName.entitlements; then
  echo "Push notification entitlement already exists."
else
  echo "Push notification entitlement added."
  sed -i '' '/^[[:space:]]*<dict>/a\'$'\n''\'$'\t''<key>aps-environment<\/key>\'$'\n''\'$'\t''<string>development<\/string>\'$'\n''' platforms/ios/MyAppName/Resources/MyAppName.entitlements
fi
```
config.xml
```
<platform name="ios">
   <hook src="ios_push_entitlement_hack.sh" type="after_platform_add" />
```

**Comment by kapral** [comment]
Why is this issue closed? The plugin is still overwriting entitlements file produced by other plugins and fixing it manually in XCode isn't a right solution especially for people having automated CI deployments. @scottwb solution works but this is still a hack.
