### ISSUE TITLE
iOS: Only one branch link per session?

### ISSUE THREAD

**Issue by Luro91** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#364]
Hi,

since the newest release 2.6.10 (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/0868dde) only the first branch link in each session triggers on iOS.  Is this behavior intended?
We generate login and invite links for our app via Branch. With this current behavior a user can not login and then accept an app invite in the same session because only the first branch link (login) is triggered. The user would need to close the app and click on the invite link again.

**Comment by ethanneff** [comment]
Hello Lukas,

I apologize if this version changed the functionality within your app. The multiple deep links per session was a bug in our Branch SDK which was causing incorrect analytics on our end. Going forward, one deep link click per session is the intended behavior. This allows you to attribute the deep link analytics from click to install to open to custom events within the same session. 

Branch's main goal is getting users inside the app. So for your use case, the sharing of the deep links will need to happen outside of your app. That way, you can attribute each deep link to a successful open of your app.

Thanks,

**Comment by Luro91** [comment]
Thanks for the clarification. Will you change the behavior for Android as well?

**Comment by ethanneff** [comment]
I apologize for the late response. Yes, we have just updated the android app (`v2.6.12`) to a similar behavior. The Branch SDK will now force `SingleTask` as an Android Launch option. This will prevent the app from opening inside other apps. Instead, the app will always open up directly. Furthermore, this will prevent any analytical edge cases from happening which we might have overlooked. 

Thank you for bringing this up.

**Comment by Luro91** [comment]
Thanks for the clarification.
