### ISSUE TITLE
deepLinkDataListener not called if app is already running on Android

### ISSUE THREAD

**Issue by tlancina** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#367]
If the app is already running and a link is clicked it looks like the response from the server comes back `{"+clicked_branch_link":false,"+is_first_session":false}`  which causes the deepLinkDataListener to not be called: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/1dcdb7617179450147d75fd68bbacbba55884b9e/src/branch.js#L52-L54

If the app is not open, the link works fine. Branch is being re-initialized on resume like this:
```
document.addEventListener("resume", function () {
     Branch.initSession(callback /* not called */);
});
```
as recommended in https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/204#issuecomment-245475629.

Not sure if this is a server side issue or misconfiguration of Link Settings on our part, so apologies if that turns out to be the case, but I wanted to cover all bases. Thanks!

Versions and stuff:
  plugin 2.6.12
  Android 7.1.2
  Nexus 6P
  Chrome 60.0.3112.116 WebView

**Comment by ethanneff** [comment]
Let me investigate this later today.

Thanks,

**Comment by tlancina** [comment]
Hey thanks for taking a look, it looks like the only difference between the `/open` request POST body when the app is closed vs when it is already open is the `android_app_link_url` is missing when the app is already open. Any idea why? I can now reliably reproduce the server response by removing or adding that key to the request.

**Comment by tlancina** [comment]
I wasn't able to pinpoint the exact problem, but I'll dump what I saw in case it helps.

The Intent data from clicking the link is `null` ([Branch.java#L2238](https://github.com/BranchMetrics/android-branch-deep-linking/blob/3d0440dde07f2486ef3d603391e480e046f0ec5b/Branch-SDK/src/io/branch/referral/Branch.java#L2238)). So when `readAndStripParam` is called, it doesn't set the app link ([Branch.java#L1379](https://github.com/BranchMetrics/android-branch-deep-linking/blob/3d0440dde07f2486ef3d603391e480e046f0ec5b/Branch-SDK/src/io/branch/referral/Branch.java#L1379), [Branch.java#L1412](https://github.com/BranchMetrics/android-branch-deep-linking/blob/3d0440dde07f2486ef3d603391e480e046f0ec5b/Branch-SDK/src/io/branch/referral/Branch.java#L1412)), so when the request to `/open` is created for initSession the android app link isn't included: [ServerRequestInitSession.java#L173-L175](https://github.com/BranchMetrics/android-branch-deep-linking/blob/3d0440dde07f2486ef3d603391e480e046f0ec5b/Branch-SDK/src/io/branch/referral/ServerRequestInitSession.java#L173-L175).

No idea why the intent data is `null`, I'll have to look into it next week.

**Comment by tlancina** [comment]
Had a chance to dig in this morning, another plugin is calling `activity.setIntent(new Intent())`, so not a Branch issue at all, sorry for the false alarm!
