### ISSUE TITLE
QUESTION: *Action required* Upgrade Branch Android SDK

### ISSUE THREAD

**Issue by razam217** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#370]
I received an email from branch.io i.e. ** *Action required* Upgrade Branch Android SDK**. 
Currently I'm using **v2.5.17** of this plugin. Do I still need to update the plugin to most recent version which is **2.6.12**?

**Comment by ethanneff** [comment]
Hello,

I understand how this email can be confusing. It was meant for our Android SDK users and not our Cordova SDK users.

For the Branch Cordova SDK, I would recommend updating to the latest version `2.6.12`.  This will pull in the correct underlying Android SDK which the email is referring to. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Cordova Branch SDK.

I apologize for this inconvenience.

Thanks,

**Comment by razam217** [comment]
Thanks @ethanneff ...

**Comment by razam217** [comment]
@ethanneff I'm trying to update branch-cordova-sdk form v2.5.0 to 2.6.14. 
But deep linking is not working on IOS, and in XCode, I'm seeing the following error:
**class BranchSDK (pluginName: BranchSDK) does not exist.**

Can you please suggest me, how to fix it?

Node v6.9.5
Cordova v6.1.1
XCode 9.0

**Comment by ethanneff** [comment]
@razam217 This is a strange bug that has popped up before, but I am still not too sure why. I have a feeling it could be related to how you are installing the Branch SDK (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/356#issuecomment-333229945), or maybe it is an error on the plugin install where all the resources are not being downloaded. 

Can you try using this  [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Branch Cordova SDK? You want to make sure you clear the old SDK before installing the new SDK. 

Thanks,

**Comment by razam217** [comment]
@ethanneff I've uninstalled and reinstalled branch-cordova-sdk according to the guide. Everything works fine in Android. But in xcode it was not adding branch-sdk classes to the plugins directory in xcode. I manually added those classes, and it started working. But I think that is not good, **cordova build ios** should do that for me.

Thanks,

**Comment by ethanneff** [comment]
@razam217 I am glad you got it working. It is odd the classes are not automatically being added to your project. They should be injected from the SDK (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/plugin.xml#L85). I will investigate this today to see if I can reproduce this issue on my end.
