### ISSUE TITLE
Error in createObj: "Branch instance not set. Please execute initSession() first"

### ISSUE THREAD

**Issue by aniruddhasm** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#373]
Hello,

I am creating an android app in ionic 2/3. I have followed the documentation provided [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#install-branch) .

Please find my below code

**config.xml**
`<branch-config>
<branch-key value="key_live_okk3F5ELnrc33D2eBnb2Qnafxxxxxxxx" />
<uri-scheme value="branchcordova" />
<link-domain value="ionic3.app.link" />
</branch-config>`

Note: I've kept my key hidden the above code.

**app.component.ts**

` import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { TabsPage } from '../pages/tabs/tabs';
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = TabsPage;
  constructor(private platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {     
      console.log("ready");
      branchInit();
    });

    platform.resume.subscribe(() => {
      console.log("resume");
      branchInit();
    });

    const branchInit = () => {
      // only on devices
      console.log("inside function");
      if (!platform.is('cordova')) { return }
      const Branch = window['Branch'];
      Branch.setDebug(true);
      Branch.setCookieBasedMatching('ionic3.app.link');
      alert(JSON.stringify(Branch));
      Branch.initSession(data => {
      console.log("init");
      if (data['+clicked_branch_link']) {
          console.log("if data");
          alert('Deep Link Data: ' + JSON.stringify(data));
      }
     });
     var properties = {};
     var branchUniversalObj = null;
      alert('kkkk');
      Branch.createBranchUniversalObject(properties).then(function (res) {
        branchUniversalObj = res;
        alert('Response: ' + JSON.stringify(res))
      }).catch(function (err) {
        alert('Error: ' + JSON.stringify(err))
      });
      // optional fields
      var analytics = {
        channel: 'facebook',
        feature: 'onboarding',
        campaign: 'content 123 launch',
        stage: 'new user',
        tags: ['one', 'two', 'three']
      }

      // optional fields
      var vproperties = {
        $match_duration: -1,
        custom_string: 'my app data',
        time_stamp: Date.now()
      }
      branchUniversalObj.generateShortUrl(analytics, vproperties).then(function (res) {
        alert('Response: ' + JSON.stringify(res.url))
      }).catch(function (err) {
        alert('Error: ' + JSON.stringify(err))
      })
    }
  }
}
`

I've implemented the same code. But I am getting the error. 
 **Error in createObj: "Branch instance not set. Please execute initSession() first"**

Please help I am stuck with this from a very long time.

![emulator](https://user-images.githubusercontent.com/2951356/30862936-409cead2-a2ed-11e7-812c-97dd5b691ace.png)

**Comment by ethanneff** [comment]
Hello,

It looks like you might have a race condition. You are trying to create a deep link on app open, but the connection to the Branch servers has not finished yet. 

You can fix this by trying to create a Branch deep link elsewhere in your app, or you can wait until the connection to the Branch servers finishes:
```js
// Branch initialization
Branch.initSession(function(data) {
  if (data['+clicked_branch_link']) {
    // read deep link data on click
    alert('Deep Link Data: ' + JSON.stringify(data))
  }
}).then(function(res) {
  // create deep link
  var analytics = { 
    channel: Date.now() 
  }
  var properties = {}
  branchUniversalObj.generateShortUrl(analytics, properties).then(function (res) {
    alert('Response: ' + JSON.stringify(res.url))
  }).catch(function (err) {
    alert('Error: ' + JSON.stringify(err))
  })
});
```

Thanks

**Comment by aniruddhasm** [comment]
Thank you.

I did the exact same thing.

Called `Branch.initSession(function(data) {` in the **app.component.ts** and `branchUniversalObj.generateShortUrl` in another page **home.ts**
