### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by 1N50MN14** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#376]
Trying to add the plugin, getting the following error

```javascript
Error: Failed to fetch plugin git+https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```
It's surely not my connection, any ideas?

**Comment by ethanneff** [comment]
Hello,

I have not seen this error before. Can you try installing Branch again? ([guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk))

I have a feeling there could have been an error with NPM which prevented you from installing the Branch Cordova SDK.

Thanks,

**Comment by 1N50MN14** [comment]
@ethanneff Yup, you're  right, no complains from npm this time! Thank you

**Comment by 1N50MN14** [comment]
@ethanneff I'm now receiving the error `Provisioning profile "iOS Development Provisioning Profile" doesn't include the com.apple.developer.associated-domains entitlement.` is there any way around this without having to re-issue the certificates?

**Comment by ethanneff** [comment]
Hello again,

Sometimes the Cordova engine is unable to build the provisioning profile for your app. This can be fixed by running your app on a device by opening your project in Xcode. Xcode will automatically set your provisioning profile. This process will only need to be done once, and all additional app builds should work fine.

Thanks,

**Comment by 1N50MN14** [comment]
Yeah I tried that, unfortunately it didn't work either, so I just went to the developer profile, regenerated the profiles and manually updated xcode...

**Comment by 1N50MN14** [comment]
App is running now, thank you :)

**Comment by 1N50MN14** [comment]
@ethanneff all the sudden `phonegap-push-plugin` is throwing an error message `no valid 'aps-environment'` does this plugin override any existing entitlements or are there any known conflicts with phonegap-push-plugin?

**Comment by 1N50MN14** [comment]
This is strange, the entitlements file looks correct:
```javascript
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.developer.associated-domains</key>
    <array>
      <string>applinks:myapp.app.link</string>
      <string>applinks:myapp-alternate.app.link</string>
    </array>
    <key>aps-environment</key>
    <string>development</string>
  </dict>
</plist>
```

**Comment by ethanneff** [comment]
This issue has popped up before in the past with the `phonegap-push-plugin` (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/357#issuecomment-327526562).

Were you able to get it working? Or, do you have any more information for me so I can try to replicate the issue on my end?

Thanks,

**Comment by 1N50MN14** [comment]
@ethanneff I gave up on `phonegap-push-plugin` for now to get this to work, my main concern is that in one of the earlier comments you had you mentioned you manually revert to the "Developer" provisioning profile, is that still the case?

**Comment by ethanneff** [comment]
Maybe? Unfortunately, I have not looked into `phonegap-push-plugin` in a while, so I will have to revisit it. If you are still playing around with it and need help, let me know and I'll revisit the issue again.

Thanks,
