### ISSUE TITLE
Problem with external deep links on iOS

### ISSUE THREAD

**Issue by ksteuer** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#378]
Hello, everyone! 

I am not able to login with LinkedIn after integration with Branch.io. I've found that the problem is caused by intercepting LinkedIn deep link by Branch (LinkedIn SDK is creating its own URI-Scheme for the app.  Is there any solution to "bypass" links which are not defined in Branch configuration? 

Thanks!
Kamil

**Comment by ethanneff** [comment]
Thank you for reaching out. I am not familiar with the Linkedin SDK, so, unfortunately, it was not part of our test plans. Can you please provide me steps to reproduce the issue as well as the plugins you are using? There is a chance their SDK is clashing with the configs of our SDK.

Thanks,

**Comment by ksteuer** [comment]
Hi. Thanks for showing your interest. I use cordova-plugin-linkedin and it works pretty well until I install cordova-ionic-phonegap-branch-deep-linking. After that, I cannot authorize with LinkedIn because deep link which is needed to return to the app is caught by branch plugin, so my app doesn't receive the token.  LinkedIn is creating its own URI-Scheme ("li<my-app-id>://") so in my opinion, it shouldn't be caught by branch.

**Comment by ethanneff** [comment]
Hello again, 

This is the intended behavior of the Branch SDK. Both Branch and non-Branch deep links are parsed through our SDK ([code](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/ios/AppDelegate%2BBranchSdk.m#L32)). However, the URI Scheme will only be attributed to Branch if it is related to Branch.

If you want to isolate the Linkedin SDK and the Branch SDK, you can add logic within the `branch.initSession()` to ignore `+clicked_branch_link=false`.

Thanks,

**Comment by ksteuer** [comment]
Hello,

I do not agree with you, because I don't get this link in my app. I've found the reason in branch.js file. This occurs when other deep link (in my case linkedin deep link) is called before Branch deep link (as a first deep link after branch initialization). PreviousLinkTimestap initially is set to null and LinkedIn deep link does not contain its own timestamp property, so currentLinkTimestamp has also null value. As a result, callback is not called. I enclose the code below: 
`if ((isBranchLinkClick || isNonBranchLinkClick) && currentLinkTimestamp !== previousLinkTimestamp) {
      deepLinkDataListener(deepLinkData)
    }`

**Comment by ethanneff** [comment]
Hello again,

I revisted this issue again, and have made the following changes to the `branch.js` logic (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/382/commits/f3748a209202b40d01b3938173868d144fb0e7c0#diff-c272cc6c1de9a9807c8642f663f15d47L53). With these changes, I was able to get the LinkedIn URL scheme as a `+non_branch_link` within the `branch.initSession()
