### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by gianpaj** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#379]
Would it be possible to somehow either integrate or reference typings for various interfaces used by the plugin?

Maybe this can help to get started:
https://github.com/ionic-team/ionic-typescript-example

**Comment by ethanneff** [comment]
Hello,

This is a good idea, however, it would be harder to maintain on our end if we include examples of both vanilla javascript and typescript for all our methods. Typescript is only used for Ionic 3 and not Cordova, PhoneGap, or Ionic 1 - so we made the decision a while back to leave the Typescript compiling up to the developer.

I apologize for any inconvenience this may cause.
