### ISSUE TITLE
Android build fails: Could not find any version that matches com.android.support:multidex:25.+.

### ISSUE THREAD

**Issue by epetre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#380]
Removing this lines makes the build succeed.
[https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/5e329ae2ba480ad286eb5a5b7bc6bd05db681200/build.gradle#L9](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/5e329ae2ba480ad286eb5a5b7bc6bd05db681200/build.gradle#L9)

![Image of info](https://i.gyazo.com/b7e065d873c97e3446d755cb25e4ba20.png)

Some details about my android setup (using Android Studio 2.3.3).

My SDK Tools
![SDK Tools](https://i.gyazo.com/9549067d9592e56a3c2d5d61c3987a3c.png)

My platforms
![My platforms](https://gyazo.com/16a8fc6aad06a0aeafb79b58313e6811.png)

**Comment by ethanneff** [comment]
Glad you were able to get it working. `compile 'com.android.support:multidex:1.0.1` was added because the Branch SDK relies on some Google dependencies which cause our SDK to have over 64k methods. Removing it should not have any negative side effects.

I will monitor this issue to see if it pops up for any other partners. 

Thanks,

**Comment by epetre** [comment]
Ok, I think it has something to do with android studio 2.3+ and how they structure their new dependencies but I'm not sure.

Maybe the Android team is going towards less support for Mulidexing now that they allow to pick and choose more specific sdk dependencies.

Also had to comment out this line otherwise the app crashed on boot.
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/1dcdb7617179450147d75fd68bbacbba55884b9e/src/scripts/android/updateAndroidManifest.js#L19

**Comment by ethanneff** [comment]
This is very valuable information to have. Thank you so much for your investigations. I have not worked with Android Studio 2.3+ yet, so I will add this version to my test plans to see if I can prevent this error from happening in the future.

**Comment by SeVeNDuS** [comment]
Hi,

I have also the same described problem

Hope to be solved soon ;)

Regards

**Comment by ethanneff** [comment]
Thanks for the heads up! 

Unfortunately, I will be out of town for the next couple of days, so I will not be able to build out a fix until next week. In the meantime, I would suggest following epetre's solution of ripping out the mulitdex references. 

I apologize for this inconvenience. I will get a fix out as soon as I can.

**Comment by SeVeNDuS** [comment]
Thanks for the answer.

I have tried @epetre solution creating a fork and removing those lines but got the same error. So maybe, I have donde something wrong. @epetre do you have any fork with the temporal solution?

Regards and thanks!

**Comment by morganabel** [comment]
I am having this same issue and the fix is also not working for me.

**Comment by morganabel** [comment]
I tried making the changes in a local directory and installed from there and I am still seeing the same problem. I used the lastest master, not idea why it worked for you and not me. Maybe another plugin is causing a conflict?

**Comment by SeVeNDuS** [comment]
Hi @epetre 

I tried doing those changes in a forked repository of this one and install from that fork and got the same problem. 
Removing the plugin cordova build android works properly

Regards

**Comment by SeVeNDuS** [comment]
HI @Ethannef

Could you work something in this?

Thanks in advance

**Comment by Ziv-Barber** [comment]
Warning:
Adding com.android.support:multidex will make your app to crash in Android 4.4
Only Android 5.0+ supporting it

**Comment by Ziv-Barber** [comment]
cordova plugin add branch-cordova-sdk@2.4.9
will fix this and the other problems.
All the versions after 2.4.9 are not working in both Android and iOS

**Comment by ethanneff** [comment]
I have submitted a fix which removes Android multidexing. Testing this was a pain, so we have decided to remove it for now to unblock everyone. We will revisit this again issue in the future to see if we can add logic around multidexing depending on which version of Android Studio.

I have just updated the Branch Cordova SDK. I would recommend updating to the latest version `2.6.16`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Cordova Branch SDK. This version should fix the error you are receiving. 

Thanks,

**Comment by Ziv-Barber** [comment]
thanks for all the work, I'll try again.
BTW:
Is there a fix for the deep link callback not been called in Android?
