### ISSUE TITLE
CSP violation unsafe-eval

### ISSUE THREAD

**Issue by smithgeek** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#381]
We're getting a CSP error due to the fact that you're using sendJavascript from the java code which does an eval in javascript which violates our CSP policy. Any chance you'd be willing to change how this works?

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/53b468578e572019b75e8f420e759e3d6fc3ef69/src/android/io/branch/BranchSDK.java#L811

**Comment by ethanneff** [comment]
I have just updated the Branch Cordova SDK (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/382/commits/75ef406124720330455f6681c0e15d453900191d). I would recommend updating to the latest version `2.6.15`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Cordova Branch SDK.

Thanks,
