### ISSUE TITLE
What is "ios-team-release"? where can I take it from?

### ISSUE THREAD

**Issue by Ziv-Barber** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#383]
The documentation says noting where this secret parameter coming from.
Search in google only tell me that there's another secret parameter "ios-team-debug" that I also need to find out.

**Comment by ethanneff** [comment]
Hello hello,

I apologize for the confusion. `ios-team-release` is the key for your [iOS team ID](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/Glossary/Glossary.html). This value is used whenever you deploy your iOS app to the App Store. Branch needs this key to allow users to deep link into your app. The key is also called [Apple App Prefix](https://branchmetrics.github.io/docs/pages/apps/cordova-phonegap-ionic/#dialog-image?src=http://i.imgur.com/wazVu3U.png) on the [Branch Dashboard](https://branch.dashboard.branch.io/settings/link).

You can find your iOS Team ID on the [Apple Developer Portal](https://docs.branch.io/pages/apps/ios/#confirm-app-prefix).

I will make sure the docs are updated to prevent this confusion in the future.

Thanks,

**Comment by Ziv-Barber** [comment]
Thanks! Now it's clear
