### ISSUE TITLE
Android app not receiving Branch link data

### ISSUE THREAD

**Issue by billqian99** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#387]
Hi,

The issue I am reporting may very well due to my inexperience with Branch.  If so, I apologize for it and appreciate it deeply if you could give me some pointer.  

I have deployed an app into a Samsung Galaxy phone to test Branch.  The app created a link with custom data and the link is shared through Gmail to my colleague.  

My colleague is able to click the link from a desktop computer, which opens the corresponding web version of the app, which sees the custom data and displays the content accordingly.

However, if I click on the same link from within the test Android phone, the Chrome browser would open first, which leads to the opening of the installed app.  However, the app doesn't seem to have received the custom data as the content is not shown accordingly.  This happens no matter if the app is running in the background or closed.

Thanks for your help,

Bill

**Comment by ethanneff** [comment]
Hello, 

I have a feeling this issue may be related to https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/384#issuecomment-340621951 - which was a related to a problem with our underlying Android SDK. Can you try [updating your Cordova Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to `2.6.16` to see if this fixes the problem? 

Thanks,

**Comment by billqian99** [comment]
Hi,

I have upgraded to 2.6.16.  However, it works as expected on clicking the Branch link for the first time right after installation of the new APK.  Subsequent clicking stops working.  Actually, every time the app is uninstalled, it would work right after re-installation, not anymore thereafter.

Thanks,

Bill

**Comment by Ziv-Barber** [comment]
I saw that too with 2.4.9 and I was about to try to upgrade to 2.6.16 thinking that it'll fix it.

**Comment by Ziv-Barber** [comment]
Same here with version 2.6.16 and Android 4.4 - no call to my listener

**Comment by billqian99** [comment]
Hi,

The problem seems gone after upgrading Android platform to 6.3.0, used to be 6.2.3.  Will keep an eye for it a little longer and close the issue thereafter.

Thanks,

Bill

**Comment by ethanneff** [comment]
Hello hello,

I am glad you got it working! Unfortunately, I am unable to reproduce the error on my end. I will try downgrading the Android Platform to see if I can reproduce. 

![a](https://user-images.githubusercontent.com/2933593/32330422-55e53314-bf9d-11e7-95fa-eaa594502572.gif)

Thanks,
