### ISSUE TITLE
Getting Error: Cannot read property '$' of undefined while building android apk

### ISSUE THREAD

**Issue by shashikiran797** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#389]
cordova build android
✖ Running command - failed!
[ERROR] An error occurred while running cordova build android (exit code 1):

        Error: Cannot read property '$' of undefined

Details:
ionic info

cli packages: (/Users/shashikiranms/.nvm/versions/node/v8.1.3/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.1
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.1.3
    npm               : 5.0.3
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55

**Comment by ethanneff** [comment]
Hello hello!

Can you give me an example of your code? Branch uses `$` to distinguish special types of deep link data ([for example](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#create-deep-link)). However, when using these key-value pairs, you must wrap the value in quotation marks. This makes the value a string without errors. 

Thanks,

**Comment by shashikiran797** [comment]
The issue was with AndroidManifest.xml
My xml file had two tags for category, that was causing the issue:
 <action android:name="android.intent.action.MAIN"/>
 <category android:name="android.intent.category.LAUNCHER"/>
 <category android:name="android.intent.category.DEFAULT"/>

Removing the third line fixed the issue
