### ISSUE TITLE
Links not working from intercom messenger

### ISSUE THREAD

**Issue by Coolcat13** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#392]
Hi there, we use the branch plugin with the intercom plugin (https://github.com/intercom/intercom-cordova) - Both are on the latest version and there are no errors but when we click on a valid branch link sent via intercom into the intercom messenger window (built into our app), the link doesn't trigger the branch action - it closes the messenger and goes through branch.init() as our app resumes, but the link doesn't get recognised.

The same branch link works perfectly from Slack/SMS or any other external app, but fails when launched within intercom in our app.

I'm not sure why this is happening, I hope you can help - thanks in advance

**Comment by ethanneff** [comment]
Hello,

When looking at the [Intercom plugin](https://github.com/intercom/intercom-cordova), I am not seeing anything that should interfere with the Branch Cordova SDK. Their plugin focuses on [push notifications](https://github.com/intercom/intercom-cordova/blob/master/intercom-plugin/src/ios/AppDelegate%2BIntercomPush.m) while Branch focuses on deep linking. Additionally, the Intercom app is not included in our regression testing for [supported platforms](https://docs.branch.io/pages/links/integrate/#expected-redirect-behavior), so there could be an edge case we are missing.

When testing the Intercom app, I am able to get deep link data successfully on iOS, Android, background, and foreground. So I'm not too sure where the problem can be.

<img src="https://user-images.githubusercontent.com/2933593/32754928-c898dda0-c887-11e7-86bd-3507c5335773.png" width="250" /><img src="https://user-images.githubusercontent.com/2933593/32755056-595d4c5e-c888-11e7-9934-ecec46994958.png" width="250" />

**Comment by Coolcat13** [comment]
My apologies if this is a bit confusing. Links work fine from Intercom's public app (and all other external apps) - However Intercom also offer a plugin (https://github.com/intercom/intercom-cordova) which allows us to include their intercom messenger inside our app (to chat with our customers). Links from that plugin's window do not work, even though the same link works fine from outside the app. 

I hope this makes more sense, thank you.

**Comment by Coolcat13** [comment]
I wonder is this issue similar to #394? Is it possible branch links do not work when clicked inside the app? I would really appreciate your feedback on this. Thanks.

**Comment by dbek** [comment]
Hi, @Coolcat13 !
I'm working with @YaroslavG on #394, we've contacted the Branch support regarding this issue, but no solution so far. Branch links inside the app don't work for us too, but seem to work fine when opened from another app.
I'll try to post a solution here, if we come to any.

**Comment by rodrigoreal** [comment]
@Coolcat13 @dbek 
I'm facing the same problem right now, did u guys find any work around on this?
Thanks

**Comment by Coolcat13** [comment]
hi @rodrigoreal we ended up using the cordova "custom URL plugin" as well as branch and letting it handle the links within the app. So far so good, still in testing.
