### ISSUE TITLE
Custom URL Scheme Non-branch links fire multiple times

### ISSUE THREAD

**Issue by Coolcat13** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#393]
Hi there

On the latest version of the plugin (and tested as far back as 2.6.10) non-branch links using the custom URL scheme trigger on every resume after clicking the link, until the app is killed.

When a branch domain link is clicked, this doesn't happen, the link is only triggered once.

Thanks in advance.

**Comment by ethanneff** [comment]
Hello,

When using [Custom URL Scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme), you should be receiving deep link data from their plugin method of [handleOpenURL()](https://github.com/EddyVerbruggen/Custom-URL-scheme#3-usage). 

Unfortunately, the Branch Cordova SDK [cannot support](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-incompatible-plugins) the Custom URL Scheme plugin. It has too many [bugs](https://github.com/EddyVerbruggen/Custom-URL-scheme/issues) which makes compatibility and troubleshooting difficult.

The Branch Cordova SDK, can, however, handle non-branch deep linking. You can test this by adding another `URL Type` in your iOS `info.plist` or by adding another `Intent` in your `AndroidManifest.xml`. For example:
<img width="425" alt="screen shot 2017-11-13 at 2 42 57 pm" src="https://user-images.githubusercontent.com/2933593/32753279-149e0f56-c881-11e7-88c9-5c77a8a6de4c.png">
<img width="425" alt="screen shot 2017-11-13 at 2 45 19 pm" src="https://user-images.githubusercontent.com/2933593/32753338-4f1e77ba-c881-11e7-8baa-a5834886697b.png">
<img height="425" alt="screen shot 2017-11-13 at 2 42 57 pm" src="https://user-images.githubusercontent.com/2933593/32753282-18fa9e3e-c881-11e7-9b07-f7b42c263768.PNG">

Thanks,

**Comment by Coolcat13** [comment]
Sorry I should have been clearer - we're not using the custom url scheme plugin, we're just using the URL scheme within the branch plugin. We've been doing this by including our chosen custom URL as a parameter in config.xml as per your doc (e.g. <uri-scheme value="helloworld" />)

However when clicking on a link such as helloworld:// from anywhere, the link gets triggered everytime the app resumes after that, until killed. This is on the latest plugin version. So in your example, we get the branch alert popup everytime the app is resumed after the initial click on helloworld://

Other links that use the branch domain (eg https://helloworld.app.link) don't have that issue and only get triggered once, even if they're "non-branch" links - it seems the issue is only happening with the URL scheme links.

I hope this helps - Thanks again - great service!

**Comment by ethanneff** [comment]
Reviving this old issue - and I apologize for the delay. I am still having trouble understanding the problem. 

This is the code I am using:
```js
'use strict'

// app
var app = {
  initialize: function initialize () {
    this.bindEvents()
  },
  bindEvents: function bindEvents () {
    document.addEventListener('deviceready', this.onDeviceReady, false)
    document.addEventListener('resume', this.onDeviceResume, false)
  },
  onDeviceReady: function onDeviceReady () {
    BranchInit(true)
  },
  onDeviceResume: function onDeviceResume () {
    BranchInit(true)
  }
}
app.initialize()

// branch
function BranchInit (isDebug) {
  console.log('Trigger BranchInit()')

  // for development and debugging only
  Branch.setDebug(isDebug)

  // Branch initialization
  Branch.initSession(function (data) {
    // read deep link data on click
    console.log('Trigger DeepLinkHandler()')
    alert('Deep Link Data: ' + JSON.stringify(data))
  }).then(function (res) {
    console.log(res)
  }).catch(function (err) {
    console.error(err)
  })
}
```

And these are the results:
![a](https://user-images.githubusercontent.com/2933593/34134599-637e5e28-e410-11e7-8602-c66458778aed.gif)
![a](https://user-images.githubusercontent.com/2933593/34135378-29bfaed0-e415-11e7-96d3-cf4d4c2337ab.gif)


On our end, the Branch SDK is functioning as expected. Can you provide more guidance on the steps you are doing and the expected behavior you are looking for?

Thanks,
