### ISSUE TITLE
iOS distribution error, applinks not supported

### ISSUE THREAD

**Issue by billqian99** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#395]
Hi,

I was trying to upload my app's archive to App Store for the first time. I am getting the attached error complaining about applinks not supported issue.  I am pretty sure that there must be something that I did wrong.  However, being a novice on integrating Branch into iOS app I need some help on how to resolve the issue.  

Thanks,

Bill
<img width="744" alt="screen shot 2017-11-16 at 9 07 18 pm" src="https://user-images.githubusercontent.com/12097517/32926387-f51faf40-cb14-11e7-81b8-2f585d34ca23.png">

**Comment by ethanneff** [comment]
Interesting. The Branch Cordova SDK does not have `https://` anywhere the Associated Domain injection script. Did you add this value manually?

Regardless, the following change should remove the error:
```
applinks:0fw4.app.link
applinks:0fw4-alternate.app.link
```

Thanks,

**Comment by billqian99** [comment]
Yes, you are right.  I have removed https:// from Cordova config.xml.  It works now.  I kind of remembering that I added the https:// sometime back after reading about that only https is supported.

Anyway, thanks for pointing it out.
