### ISSUE TITLE
Cannot resolve module 'cordova/exec' in branch.js

### ISSUE THREAD

**Issue by neilmalgaonkar** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#396]
Hi all,

I am facing very weird issue while using branch.io for our cross-platform app. Whenever I try to compile the app using webpack I get the following issue 

Module not found: Error: Cannot resolve module 'cordova/exec' in /node_modules/branch-cordova-sdk/src

I even upgraded the Cordova version of the app from 6.5.0 to 7.0.1, but still no success.

my node version is v6.10.3

Any kind of help will be apprecited :)

**Comment by neilmalgaonkar** [comment]
My apologies! I found a mistake in my own code. Hence closing this issue.

**Comment by hereiskkb** [comment]
Can you give me some pointers as to what the mistake in the code was? I am stuck with the same error.
