### ISSUE TITLE
Cold Start

### ISSUE THREAD

**Issue by myrsk** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#397]
When the app is in the background and I open a deeplink, it brings the app up and goes to the page requested.

```
this.platform.ready().then(() => {
      this.statusBar.overlaysWebView(false);
      this.statusBar.backgroundColorByHexString('#222');

      this.splashScreen.hide();

      this.setRootPage();
      handleBranch();
    });

this.platform.resume.subscribe(() => {
      handleBranch();
    });

const handleBranch = () => {
      // only on devices
      if (!this.platform.is('cordova')) { return }
      const Branch = window['Branch'];
      Branch.initSession(data => {
        if (data['+clicked_branch_link']) {
          // read deep link data on click
          //alert('Deep Link Data: ' + JSON.stringify(data));
          this.nav.push(data['page'],{itemId:data['id']});
        }
      });
    }
```

However, if i force quit the app, and then click on a deeplink, it opens the app and stays on the root page.

Any ideas?

**Comment by tkuse** [comment]
did you try to look at the outputs given with `Branch.setDebug(true)` before your initSession code?

**Comment by myrsk** [comment]
There seems to be no errors. 

When i put the line below, i actually get the alert just fine. 

alert('Deep Link Data: ' + JSON.stringify(data));

So i presume the following code doesnt execute in the order set. How do i wait for the top before running the second? *confused*

this.setRootPage();
 handleBranch()

**Comment by myrsk** [comment]
Just tried to test it on an android device, and works fine - even on a cold start.

So the issue remains just for ios.

**Comment by myrsk** [comment]
Okay, in case anyone faces the same issue. Just delay branch in this.platform.ready. I have delayed it by a second - since everything is async, I do not think it will have an impact. I have tested it and it works fine.

`handleBranch();`

**Comment by ethanneff** [comment]
Hello,

Good find and good solution. It appears `this.setRootPage();` is an Ionic method which [creates a new instance of the page](https://forum.ionicframework.com/t/setrootpage-always-creates-the-new-instance-of-the-page/60595). This method must have some funky behavior interally which creates a race condition with the Branch initialization. 

Another solution besides timeouts would be to place the `handleBranch()` within the `done` parameter of `setRoot()` ([docs](https://ionicframework.com/docs/api/navigation/NavController/#setRoot)). However, this depends on which version of the Ionic SDK you are using.

Thanks,
