### ISSUE TITLE
branch.io not passing details after clicking link and installing app

### ISSUE THREAD

**Issue by thkuberlin** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#402]
We have a strange behaviour here with the branch-response after an installation of the app (currently testing only with iOS with the latest cordova plugin 2.6.18 and with custom domain)

First step is deleting the app. Then click on the link. Message to download is coming and working. After opening the installed app there is only a 50% chance of getting a
`["+clicked_branch_link"]:true`

It is not important to count this as a new install, it is only important for us to direct the user to the correct view in the app after an installation.

If the app is already installed, I can't remember any problems at all. This way is working fine.
Now you have this cool liveview on your page and when it isn't working, the last column (session referring link url) in the liveview is "null", if it works, the url is correctly filled (see attachment)
![branch_session](https://user-images.githubusercontent.com/7392402/33663440-41152512-da90-11e7-9350-225b8911c774.jpg)

In the Details from the Live-View i can see these IDs:

```
Branch Identity ID: 466886649486355179
Branch Session ID: 466886649498977789
ID: 466886649528587572
```
And in the Plugin-Debug-Output those same ids are also in the response:

```
BNCServerInterface.m(747) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = 466886649453151301;
    "identity_id" = 466886649486355179;
    link = "https://xxxx.xxxx/a/key_live_fim734jZcHMRnkUIquFBpckaqrefifPp?%24identity_id=466886649486355179";
    "session_id" = 466886649498977789;
}
```

We also tried getLatestReferringParams to get those data, but without more success.

**Comment by ethanneff** [comment]
Hello!

Are you still having problems? I know you received feedback through our support, but I wanted to make sure you got everything working.

Thanks,

**Comment by sengoontoh** [comment]
I also saw similar issues where clicked_branch_link was not being triggered most of the time for new installs. Branch support had advised me to use webhooks instead. I haven't tried it yet.

What's the most bulletproof method?

**Comment by ethanneff** [comment]
@sengoontoh either method would work. If the analytics are showing up in the Branch Dashboard, then the deep link data was successfully submitted from your app to the Branch servers. What the user sees and Branch sees will be in sync. 

I would recommend Webhooks as well since this will be a server-to-server transfer of data. It takes work off the user's device, you don't have to worry about the device's network connection, and you can get valid response codes from the server if something does go wrong.

Thanks,

**Comment by luisvillara** [comment]
Hey, I'm having the same issue, when I open the link (in Safari) and I install the app, sometimes the Deep Link doesn't work at all, this is what the logs looks like at that moment:

```
BNCNetworkService.m(219) Debug: Network finish operation https://api.branch.io/v1/install 0.639s. Status 200 error (null).
{"session_id":"516029442108308059","identity_id":"516029442087709188","link":"https://mel2.test-app.link?%24identity_id=516029442087709188","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"516029441995093675"}.
2018-04-20 19:07:13.041211-0500 New Stand[31130:4815900] [branch.io] BNCServerInterface.m(771) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = 516029441995093675;
    "identity_id" = 516029442087709188;
    link = "https://mel2.test-app.link?%24identity_id=516029442087709188";
    "session_id" = 516029442108308059;
```

It's weird because sometimes it works, this is so frustrating.

I'm using the branch-cordova-sdk (v2.6.24).
