### ISSUE TITLE
Branch deep link redirect to a page

### ISSUE THREAD

**Issue by mymai91** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#406]
Hi team / @ethanneff 
If I touch on the link to open an App is installed on my phone How can I redirect the app to page I defined? I'm building the app with Ionic3.

**Comment by ethanneff** [comment]
You can pass any deep link data you want within your deep links 
https://docs.branch.io/pages/links/integrate/#create-deep-links

You can then read this deep link data to navigate to content within your app
https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#navigate-to-content
