### ISSUE TITLE
"Trouble initializing Branch.  The request was invalid" on Android

### ISSUE THREAD

**Issue by mifkys** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#408]
Hello! I try to initialize Branch on Android 6.0 in Ionic 3 app. 

I already configured  Branch dashboard. Then i inserted in config.xml next rows:
```
<plugin name="branch-cordova-sdk" spec="^2.6.21" />
    <branch-config>
        <branch-key value="key_live_xxx" />
        <uri-scheme value="scheme_from_dashboard" />
        <link-domain value="link_from_dashboard.app.link" />
    </branch-config>
```

and in app.component.ts:
```
constructor(public platform: Platform) {
    platform.ready().then(() => {      
      console.log('initializing Branch on ready');      
      initBranch();
    });

    platform.resume.subscribe(() => {
      console.log('initializing Branch on resume');
      initBranch();
    });

    const initBranch = () => {
      if (!platform.is('cordova')) { return }
      console.log('Branch initialization');
      const Branch = window['Branch'];
      Branch.setDebug(true);
      Branch.initSession(data => {
        console.log('Deep Link Data: ', data);
        if (data['+clicked_branch_link']) {
          console.log('Clicked Deep Link Data: ', data);
        }
      }).then(function(res) {
        console.log('Response: ', res)
      }).catch(function(err) {
        console.log('Error: ', err)
      });
    }
  }
```

After `ionic cordova run android` on app start i receive next error:

> "Trouble initializing Branch.  The request was invalid."

That's all. When I click on created link I switch to my app but in console I got the same error.

> @ionic/cli-utils  : 1.19.0
>     ionic (Ionic CLI) : 3.19.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : not installed
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.5
>     Cordova Platforms  : android 6.3.0
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     Android SDK Tools : 26.1.1
>     Node              : v8.9.0
>     npm               : 5.5.1
>     OS                : Windows 10

**Comment by ethanneff** [comment]
Hello,

Thanks for reaching out!

Can you check your [console logs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-show-console-logs) for any more information or errors?

You might also want to do the [test steps](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-android) again to make sure Branch has been installed.

Thanks,

**Comment by mifkys** [comment]
No more related console logs. Only "Trouble initializing Branch. The request was invalid." in error object. 

I already did test steps. Result the same.

One time on cold app's start i receive `data` object from initSession function but I can't reproduce this again.

**Comment by mifkys** [comment]
Sorry. My bad. I didn't delete old build before integrate Branch. Delete app from device then  `ionic cordova run android` solve the problem!
