### ISSUE TITLE
large [~id] number conversion in Branch.initSession(data =>..)

### ISSUE THREAD

**Issue by deumax** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#409]
Hi,

The `~id` property of the data object returned by `Branch.initSession( data => ... )` gives me a wrong number. 
`~id: 469827475497783300` but should be `469827475497783321`
I guess the number is too large and is automatically converted to the number type.
How can I prevent this conversion and be given a string instead?

I am using branch-cordova-sdk 2.6.21 with Ionic 3

Thanks in advance

**Comment by ethanneff** [comment]
Yikes! JavaScript is truncating the integers (you can test this in the Chrome console as well)
<img width="153" alt="screen shot 2017-12-14 at 3 36 45 pm" src="https://user-images.githubusercontent.com/2933593/34019598-9d304a48-e0e4-11e7-98a1-a1c363e1e76c.png">

I will work on converting all Integers from our server response to Strings as soon as possible. In the meantime, I would recommend on using the values within the dashboard as the true values. https://dashboard.branch.io/liveview/opens

I apologize for this inconvenience.

**Comment by ethanneff** [comment]
Hello again, 

I apologize for the delay. This bug appears to be larger in scope than expected. The bug of `~id` showing incorrectly is not only broken with our Cordova SDK, but also our [Branch Dashboard](https://dashboard.branch.io/liveview/clicks), and every other SDK which uses JavaScript (React Native, Titanium, etc). Anywhere where the int is too big gets truncated by JavaScript to a wrong value.

Changing the ~id value from an int to a string from our API would be the simplest solution to fix all our platforms, but we worry this change will break any previous partner relying on ~id being an int. 

To get a better idea how to prioritize this internally, do you mind helping us understand why you need this value? Why exactly do you need the `~id`? Are you using it to coordinate your in-app deep link data to the data within the [Branch Dashboard](https://dashboard.branch.io/liveview/clicks)? If so, would `+click_timestamp` suffice for this use case? 

Any information you can provide about your use case will be helpful.

Thank you,

**Comment by deumax** [comment]
Now I am receiving `~id` as `string`. Did you change anything?
The problem with using `+click_timestamp` ist that I am interested in the id of the link the linkClick clicked on. Not the id of the linkClick.

**Comment by deumax** [comment]
The bug still exists. I am experiencing different behaviour when I open links differently.

When I open/click a branch link directly (i.e. a shared link on WhatsApp) the app receives `~id` as `number`.
![branch_bug_directly](https://user-images.githubusercontent.com/26224119/35683159-656d331e-0763-11e8-8ffa-072019d3e61a.png)

When I open the link by pasting it into a browser (i.e. chrome) the app receives `~id` as `string`.
![branch_bug_browser](https://user-images.githubusercontent.com/26224119/35683226-8b4dc0bc-0763-11e8-90f2-ba5d8bf19b48.png)

As we currently depend on `~id` our workaround is to make a separate HTTP request retreiving the data via the link url.
