### ISSUE TITLE
inquiry:  will Branch functions properly for app released in non-US App/Play store?

### ISSUE THREAD

**Issue by billqian99** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#410]
Hi,

I have integrated Branch with my app.  However, as a phased release, it has been released into several non-US stores currently.

Will Branch links still work as designed in this scenario?

Thanks,

Bill

**Comment by ethanneff** [comment]
Hello!

If a user clicks on a deep link from the web, the deep link will naturally go to the fallback url. This value is set globally in your Branch Dashboard (https://dashboard.branch.io/link-settings) or at a link-level within your deep link settings (https://docs.branch.io/pages/links/integrate/#redirections).

You can read more about deep link behavior here (https://docs.branch.io/pages/links/integrate/#default-link-behavior).

Additionally, you can try to leverage `$fallback_url_us`  (https://docs.branch.io/pages/links/integrate/#redirections) to send users to a location if the App is not available in that store yet.

Thanks,
