### ISSUE TITLE
Cannot Install with Cordova 7.1.0

### ISSUE THREAD

**Issue by jkassis** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#413]
Cannot install...

```
➜  pognerd git:(master) ✗ cordova plugin add https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking
Error: Failed to fetch plugin https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
➜  pognerd git:(master) ✗ cordova --version
7.1.0
```

**Comment by ethanneff** [comment]
Hello!

I have just confirmed the Branch SDK is compatible with Cordova 7.0.0, 7.1.0 and 8.0.0.

I would recommend trying again. I have a feeling your error is related to your network connection or a failed download from NPM. `Probably this is either a connection problem, or plugin spec is incorrect.`

Thanks,

**Comment by ethanneff** [comment]
You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to re-install the Branch SDK. Followed by your normal build process `cordova build ios` `cordova build android`.
