### ISSUE TITLE
custom object in share link

### ISSUE THREAD

**Issue by csotomon** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#414]
Hi, i'm creating a new deeplink to share calling  (i'm using ionic 3)

branchUniversalObj.showShareSheet

I'm sending this object 

`let prop = {
        $deeplink_path : 'shareInsurance',
        custom_object: { 'random': 'dictionary' },
        id: 1561
      };`

When i read the deeplink in my app custom_object is transmited like:
`{\\\"random\\\":\\\"dictionary\\\"}"`

and i can't parse the objet with JSON.parse() function because the **\\\**

How can i solve this problem?

this is all the data object:

`{"$publicly_indexable":"true","$deeplink_path":"shareInsurance","~creation_source":2,"+click_timestamp":1513916799,"source":"android","$identity_id":"472168251758265315","~feature":"Share","+match_guaranteed":true,"custom_object":"{\\\"random\\\":\\\"dictionary\\\"}","$canonical_identifier":"shareInsurance","+clicked_branch_link":true,"~id":"472607918290843928","$one_time_use":false,"+is_first_session":false,"~referring_link":"https://yyha.app.link/WorKUAdI4I","~channel":"Copy","id":"1561"}`

**Comment by ethanneff** [comment]
Hello!

Instead of creating your custom dictionary object inside your BUO contentMetadata, please create it inside your link properties. Look at the output of `custom_object: { 'random': 'dictionary' }` in the example below.

Share a link:
```js
// only canonicalIdentifier is required
var properties = {
  canonicalIdentifier: 'content/123',
  canonicalUrl: 'https://example.com/content/123',
  title: 'Content 123 Title',
  contentDescription: 'Content 123 Description ' + Date.now(),
  contentImageUrl: 'http://lorempixel.com/400/400/',
  price: 12.12,
  currency: 'GBD',
  contentIndexingMode: 'private',
  contentMetadata: {
    custom: 'data',
    testing: 123,
    this_is: true
  }
}

// create a branchUniversalObj variable to reference with other Branch methods
Branch.createBranchUniversalObject(properties).then(function (branchUniversalObj) {

  // optional fields
  var analytics = {
    channel: 'facebook',
    feature: 'onboarding',
    campaign: 'content 123 launch',
    stage: 'new user',
    tags: ['one', 'two', 'three']
  }

  // optional fields
  var properties = {
    $desktop_url: 'http://www.example.com/desktop',
    custom_string: 'data',
    custom_integer: Date.now(),
    custom_boolean: true,
    custom_array: [1, 2, 3, 4, 5],
    custom_object: { 'random': 'dictionary' }
  }

  var message = 'Check out this link'

  // share sheet
  branchUniversalObj.showShareSheet(analytics, properties, message)
})
```

Click the link:
```js
Branch.initSession(function (data) {
  if (data['+clicked_branch_link']) {
    console.log(JSON.stringify(data));
    alert(JSON.stringify(data))
  }
})
```

Read the following console.log output:
```json
{"$canonical_url":"https://example.com/content/123","$locally_indexable":true,"~creation_source":3,"$one_time_use":false,"~tags":["one","two","three"],"+is_first_session":false,"~referring_link":"https://cordova.app.link/vFeGpqKG5I","custom_array":[1,2,3,4,5],"$og_title":"Content 123 Title","$desktop_url":"http://www.example.com/desktop","$currency":"GBD","~stage":"new user","custom_object":{"random":"dictionary"},"~campaign":"content 123 launch","~channel":"Pasteboard","custom_integer":1513967555365,"$og_description":"Content 123 Description 1513967549318","$custom_fields":"{\"testing\":123,\"custom\":\"data\",\"this_is\":true}","$identity_id":467413196173649340,"$canonical_identifier":"content/123","$og_image_url":"http://lorempixel.com/400/400/","+click_timestamp":1513968688,"~id":472821079954593660,"+clicked_branch_link":true,"$price":12.12,"custom_string":"data","~feature":"onboarding","+match_guaranteed":true,"custom_boolean":true}
```

Thanks,

**Comment by csotomon** [comment]
Hi @ethanneff 

I used your same code and this is console output

Please check custom_object (i'm using the 2.6.14 version)

`{"custom_array":"[1,2,3,4,5]","$og_title":"Content 123 
            Title","source":"android","$identity_id":"472743176495691550","~stage":"new 
            user","~feature":"onboarding","custom_object":"{\\\"random\\\":\\\"dictionary\\\"}","$desktop_url":"http://www.example.com/desktop","$canonical_identifier":"content/123","~id":"473849154901258495","~campaign":"content
            123 
            launch","+is_first_session":false,"~channel":"E-mail","custom_boolean":"true","$publicly_indexable":"false","this_is":"true","~creation_source":2,"custom_integer":"1514212651713","custom":"data","testing":"123","$og_description":"Content
            123 Description 
            1514212651662","+click_timestamp":1514212793,"$og_image_url":"http://lorempixel.com/400/400/","custom_string":"data","+match_guaranteed":true,"~tags":["one","two","three"],"+clicked_branch_link":true,"$one_time_use":false,"~referring_link":"https://yyha.app.link/9Pl7egGoaJ"}`

**Comment by ethanneff** [comment]
Oh yuk, I was finally able to reproduce the issue on my end. The underlying iOS and Android SDKs handle sub dictionaries within the link data differently. Using `JSON.stringify(val.custom_object.random)` resulted in different outcomes: 

<img width="200" src="https://user-images.githubusercontent.com/2933593/34498291-d9e4063e-efb5-11e7-9702-810bb6344bd8.png" /><img width="200" src="https://user-images.githubusercontent.com/2933593/34498361-2fc4cce6-efb6-11e7-90aa-30ffe5b4623e.png" />

Android is parsing the custom dictionary as a string while iOS is not. I'm going to work with our Android team to see if we can get a solution fixed so both our underlying SDKs behave the same. 

I apologize for this inconvenience.

**Comment by ethanneff** [comment]
Hello again,

Unfortunately, after further investigation, this feature is a limitation of our underlying SDKs. Both iOS and Android SDKs can only pass custom key-value Strings when creating a deep link in your app. For example:

```js
// only canonicalIdentifier is required
var properties = {
  canonicalIdentifier: 'content/123',
  canonicalUrl: 'https://example.com/content/123',
  title: 'Content 123 Title',
  contentDescription: 'Content 123 Description ' + Date.now(),
  contentImageUrl: 'http://lorempixel.com/400/400/',
  price: 12.12,
  currency: 'GBD',
  contentIndexingMode: 'private',
  contentMetadata: {
    custom: 'data',
    testing: '123',
    this_is: 'true'
  }
}

// create a branchUniversalObj variable to reference with other Branch methods
Branch.createBranchUniversalObject(properties).then(function (branchUniversalObj) {

  // optional fields
  var analytics = {
    channel: 'facebook',
    feature: 'onboarding',
    campaign: 'content 123 launch',
    stage: 'new user',
    tags: ['one', 'two', 'three']
  }

  // optional fields
  var properties = {
    $desktop_url: 'http://www.example.com/desktop',
    custom_string: 'data',
    custom_integer: Date.now().toString(),
    custom_boolean: true.toString()
  }

  var message = 'Check out this link'

  // share sheet
  branchUniversalObj.showShareSheet(analytics, properties, message)
})
```

The following have been removed from the example as they are converted to Strings by the underlying iOS and Android SDKs - which causes read errors once the deep link opens the app.

```js
    custom_array: [1, 2, 3, 4, 5],
    custom_object: { 'random': 'dictionary' }
```

If you need to store a dictionary, your best bet is to parse each key, and then save the value at the root level of the deep link data as a String. For example:

```js
  var properties = {
    random: 'dictionary',
    some_key: 'value'
  }
```

I apologize for this inconvenience.  For deep links created in-app, you can only pass custom Strings. I will update the docs to prevent confusion in the future.

**Comment by csotomon** [comment]
thank you for your help
