### ISSUE TITLE
Exception java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by sengoontoh** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#415]
I updated to version 2.6.21 and am starting to see crashes happening in the field

java.util.LinkedList$ListItr.checkForComodification (LinkedList.java:967)
java.util.LinkedList$ListItr.next (LinkedList.java:888)
io.branch.referral.ServerRequestQueue$1.run (ServerRequestQueue.java:70)
java.lang.Thread.run (Thread.java:762)

I noticed a similar recent issue in the Android version of branch. When will this fix show up here?
https://github.com/BranchMetrics/android-branch-deep-linking/issues/521

**Comment by ethanneff** [comment]
Hello, 

Thanks for the heads up. I have been communicated with our Android team the past couple of days and we have a patch coming out next week to address this issue. You can [subscribe](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/subscription) to this repo to get updated on any changes to the Branch Cordova SDK. Additionally, I will personally update this Github issue once the version is live (you will receive an email).

I apologize for this crash. We are working hard to get this fixed as soon as possible.

**Comment by sengoontoh** [comment]
Has this been fixed?

**Comment by ethanneff** [comment]
@sengoontoh It should be. Can you please update to the latest version of the Branch Cordova SDK `2.6.22`? This version has the latest underlying Branch Android SDK (`2.14.4`) with the fix. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update.

Again, I apologize for this inconvenience.
