### ISSUE TITLE
Not compatible with Cordova Android 7.0.0 (SDK 2.6.21)

### ISSUE THREAD

**Issue by Ziv-Barber** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#416]
Howto:
cordova platform add android@7.0.0 --nosave
cordova plugin add branch-cordova-sdk@2.6.21 --variable BRANCH_KEY=... --variable URI_SCHEME=... --nosave

**Comment by ethanneff** [comment]
Hello, 

The Branch SDK is fully capable with Cordova Android 7.0.0.

I have a feeling you are having trouble with your installation method. `cordova plugin add branch-cordova-sdk@2.6.21 --variable BRANCH_KEY=... --variable URI_SCHEME=... --nosave`  is no longer supported.

The best way to install the Branch SDK is within your `config.xml`:
```xml
<plugin name="branch-cordova-sdk" spec="^2.6.0" />
```

You may need to [re-install the Branch SDK](https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#update-the-branch-sdk) before running your build scripts (`cordova build ios, cordova build android`).

You can follow this [guide](https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#integrate-branch) to fully integrate and test your Branch deep links. 

Thanks,
