### ISSUE TITLE
Error: BRANCH SDK: Invalid "android-prefix" in <branch-config> in your config.xml.

### ISSUE THREAD

**Issue by anandhsp21** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#420]
_in ionic i am getting error like this_

Error: BRANCH SDK: Invalid "android-prefix" in <branch-config> in your config.xml. Docs https://goo.gl/GijGKP
   

```
<plugin name="branch-cordova-sdk" spec="^2.6.0" /
 <branch-config>
    -- <branch-key value="key_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
     --<uri-scheme value="xxxxxx" />
     --<link-domain value="dl.xxxxxxxxxxxxxx.com" />
     --<android-prefix value="/TRknb" />
     --<android-testmode value="true" />
</branch-config>

**ionic info**

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils   1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.6.0
System:
    Android SDK Tools : 26.1.1
    Node              : v9.2.0
    npm               : 5.6.0 
    OS                : Linux 4.13

**Comment by ethanneff** [comment]
Hello,

Thank you for reaching out. 

Yep, this is a mistake in our code base. I'll update the SDK logic and submit a new version today.

I'll reach out to you in this thread it is live.

**Comment by ethanneff** [comment]
I have just fixed this issue. I would recommend updating to the latest version of the Branch Cordova SDK `2.6.23`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update.

Thanks,

**Comment by anandhsp21** [comment]
Thank you . It's working fine now
