### ISSUE TITLE
Error: BRANCH SDK: Cannot write file AndroidManifest.xml

### ISSUE THREAD

**Issue by sebasnavarrete** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#422]
Hello!

Im having this issue when i use 'cordova build android': 

(node:9295) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: BRANCH SDK: Cannot write file /app/platforms/android/AndroidManifest.xml

Cordova version: 8.0.0
Ionic v1
android Version ~7.0.0

Thanks for your help.

**Comment by ethanneff** [comment]
Hello! 

That does not look good. Can you please provide me with some more information so I can debug this on my end? Specifically the output to `cordova info` and `cordova plugin`.

Additionally, you might want to try rebuilding your platform `cordova platform rm android && cordova platform add android`. If that fails, can you try making sure you have proper ownership of the file so it can be written to `stat -f %A  /app/platforms/android/AndroidManifest.xml`?

Thanks,

**Comment by sebasnavarrete** [comment]
cordova info:

> Node version: v6.11.1
> 
> Cordova version: 8.0.0
> 
> Config.xml file: 
> 
> <?xml version='1.0' encoding='utf-8'?>
> <widget android-versionCode="XXX" id="XXXX" version="XXXX" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0">
>     <name>XXXX</name>
>     <description>XXX</description>
>     <author email="xxxx" href="xxxxx">
>         XXX
>     </author>
>     <content src="index.html" />
>     <access origin="*" />
>     <access origin="cdvfile://*" />
>     <access launch-external="yes" origin="tel:*" />
>     <access launch-external="yes" origin="sms:*" />
>     <access launch-external="yes" origin="mailto:*" />
>     <access launch-external="yes" origin="whatsapp:*" />
>     <allow-navigation href="*" />
>     <allow-intent href="https://*/*" />
>     <allow-intent href="tel:*" />
>     <allow-intent href="sms:*" />
>     <allow-intent href="cdvfile://*" />
>     <preference name="AndroidPersistentFileLocation" value="Compatibility" />
>     <preference name="iosPersistentFileLocation" value="Library" />
>     <preference name="android-minSdkVersion" value="16" />
>     <preference name="android-targetSdkVersion" value="20" />
>     <preference name="loadUrlTimeoutValue" value="700000" />
>     <preference name="webviewbounce" value="false" />
>     <preference name="UIWebViewBounce" value="false" />
>     <preference name="DisallowOverscroll" value="true" />
>     <preference name="BackupWebStorage" value="none" />
>     <preference name="SplashScreen" value="screen" />
>     <preference name="SplashScreenDelay" value="3000" />
>     <preference name="FadeSplashScreen" value="false" />
>     <preference name="FadeSplashScreenDuration" value="1000" />
>     <preference name="AutoHideSplashScreen" value="true" />
>     <preference name="ShowSplashScreenSpinner" value="false" />
>     <preference name="intercom-app-id" value="z51egnsw" />
>     <preference name="intercom-ios-api-key" value="ios_sdk-dbe9a6381b1e7925c6304f8c828f9cbb081eccb3" />
>     <preference name="intercom-android-api-key" value="android_sdk-25e4eb2999d1a3d93187495cbae47949a8c089cc" />
>     <feature name="StatusBar">
>         <param name="ios-package" onload="true" value="CDVStatusBar" />
>     </feature>
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.GET_ACCOUNTS" />
>     <uses-permission android:name="android.permission.READ_CONTACTS" />
>     <uses-permission android:name="android.permission.WRITE_CONTACTS" />
>     <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
>     <gap:config-file parent="/manifest" platform="android">
>         <application android:largeHeap="true" />
>     </gap:config-file>
>     <branch-config>
>         <branch-key value="key_live_xxxxx" />
>         <uri-scheme value="test" />
>         <link-domain value="test.app.link" />
>         <ios-team-release value="xxxx" />
>     </branch-config>
>     <platform name="android">
>         <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
>         <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
>         <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
>         <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
>         <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
>         <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
>         <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
>         <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
>         <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
>         <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
>         <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
>         <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
>         <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
>         <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
>         <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
>         <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
>         <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
>         <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
>         <hook src="hooks/after_prepare/030_copy_android_notification_icons.js" type="after_prepare" />
>     </platform>
>     <platform name="ios">
>         <allow-navigation href="sms:*" />
>         <allow-navigation href="tel:*" />
>         <allow-navigation href="whatsapp:*" />
>         <icon height="57" src="resources/ios/icon/icon.png" width="57" />
>         <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
>         <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
>         <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
>         <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
>         <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
>         <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
>         <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
>         <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
>         <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
>         <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
>         <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
>         <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
>         <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
>         <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
>         <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
>         <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
>         <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
>         <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
>         <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
>         <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
>         <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
>         <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
>         <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
>         <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
>         <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
>         <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
>         <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
>         <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
>         <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
>         <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
>     </platform>
>     <preference name="SplashShowOnlyFirstTime" value="false" />
>     <plugin name="cordova-plugin-camera" spec="^2.4.1" />
>     <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" />
>     <plugin name="cordova-plugin-contacts" spec="^3.0.0">
>         <variable name="CONTACTS_USAGE_DESCRIPTION" value="Envio de cupones" />
>     </plugin>
>     <plugin name="cordova-plugin-compat" spec="^1.2.0" />
>     <plugin name="cordova-plugin-badge" spec="git+https://github.com/katzer/cordova-plugin-badge.git" />
>     <plugin name="cordova-plugin-geolocation" spec="^2.4.3" />
>     <plugin name="cordova-plugin-inappbrowser" spec="^1.7.2" />
>     <plugin name="cordova-plugin-nativeaudio" spec="^3.0.9" />
>     <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
>     <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
>     <plugin name="cordova.plugins.diagnostic" spec="^3.9.1" />
>     <plugin name="ionic-plugin-deploy" spec="^0.6.7" />
>     <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
>     <plugin name="onesignal-cordova-plugin" spec="^2.2.5" />
>     <plugin name="cordova-plugin-device" spec="^1.1.7" />
>     <plugin name="cordova-plugin-file" spec="^4.3.3" />
>     <plugin name="cordova-plugin-x-socialsharing" spec="git+https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git" />
>     <plugin name="cordova-plugin-statusbar" spec="git+https://github.com/apache/cordova-plugin-statusbar.git" />
>     <plugin name="cordova-plugin-google-analytics" spec="^1.8.3" />
>     <plugin name="cordova-plugin-console" spec="^1.1.0" />
>     <engine name="android" spec="^7.0.0" />
>     <plugin name="cordova-plugin-facebook4" spec="^1.9.1">
>         <variable name="APP_ID" value="xxxxx" />
>         <variable name="APP_NAME" value="xxxx" />
>     </plugin>
> </widget>
> 
> 
> Plugins: 
> 
> cordova-plugin-badge,cordova-plugin-camera,cordova-plugin-compat,cordova-plugin-console,cordova-plugin-contacts,cordova-plugin-device,cordova-plugin-facebook4,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-geolocation,cordova-plugin-google-analytics,cordova-plugin-inappbrowser,cordova-plugin-intercom,cordova-plugin-nativeaudio,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-x-socialsharing,cordova.plugins.diagnostic,es6-promise-plugin,ionic-plugin-deploy,ionic-plugin-keyboard,onesignal-cordova-plugin
> 
> Android platform:
> 
> Available Android targets:
> ----------
> id: 1 or "android-14"
>      Name: Android 4.0
>      Type: Platform
>      API level: 14
>      Revision: 4
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800
>  Tag/ABIs : default/armeabi-v7a
> ----------
> id: 2 or "android-15"
>      Name: Android 4.0.3
>      Type: Platform
>      API level: 15
>      Revision: 5
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800
>  Tag/ABIs : default/armeabi-v7a, default/mips, default/x86, google_apis/armeabi-v7a, google_apis/x86
> ----------
> id: 3 or "android-16"
>      Name: Android 4.1.2
>      Type: Platform
>      API level: 16
>      Revision: 5
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a, default/mips, default/x86, google_apis/armeabi-v7a, google_apis/x86
> ----------
> id: 4 or "android-17"
>      Name: Android 4.2.2
>      Type: Platform
>      API level: 17
>      Revision: 3
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a, default/mips, default/x86, google_apis/x86
> ----------
> id: 5 or "android-18"
>      Name: Android 4.3.1
>      Type: Platform
>      API level: 18
>      Revision: 3
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a, default/x86, google_apis/armeabi-v7a, google_apis/x86
> ----------
> id: 6 or "android-19"
>      Name: Android 4.4.2
>      Type: Platform
>      API level: 19
>      Revision: 4
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a, default/x86
> ----------
> id: 7 or "android-20"
>      Name: Android 4.4W.2
>      Type: Platform
>      API level: 20
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
>  Tag/ABIs : android-wear/armeabi-v7a, android-wear/x86
> ----------
> id: 8 or "android-21"
>      Name: Android 5.0.1
>      Type: Platform
>      API level: 21
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
>  Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
> ----------
> id: 9 or "android-22"
>      Name: Android 5.1.1
>      Type: Platform
>      API level: 22
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
>  Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
> ----------
> id: 10 or "android-23"
>      Name: Android 6.0
>      Type: Platform
>      API level: 23
>      Revision: 3
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320
>  Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/x86, default/x86_64
> ----------
> id: 11 or "android-24"
>      Name: Android 7.0
>      Type: Platform
>      API level: 24
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : android-tv/x86, default/arm64-v8a, default/armeabi-v7a, default/x86, default/x86_64
> ----------
> id: 12 or "android-25"
>      Name: Android 7.1.1
>      Type: Platform
>      API level: 25
>      Revision: 3
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320
>  Tag/ABIs : android-tv/x86, android-wear/armeabi-v7a, android-wear/x86
> ----------
> id: 13 or "android-26"
>      Name: Android 8.0.0
>      Type: Platform
>      API level: 26
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : no ABIs.
> ----------
> id: 14 or "android-27"
>      Name: Android 8.1.0
>      Type: Platform
>      API level: 27
>      Revision: 1
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : no ABIs.
> ----------
> id: 15 or "Google Inc.:Google APIs:15"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 3
>      Description: Android + Google APIs
>      Based on Android 4.0.3 (API level 15)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800
>  Tag/ABIs : default/armeabi-v7a
> ----------
> id: 16 or "Google Inc.:Google APIs:16"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 4
>      Description: Android + Google APIs
>      Based on Android 4.1.2 (API level 16)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a
> ----------
> id: 17 or "Google Inc.:Google APIs:17"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 4
>      Description: Android + Google APIs
>      Based on Android 4.2.2 (API level 17)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a, google_apis/armeabi-v7a
> ----------
> id: 18 or "Google Inc.:Google APIs:18"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 4
>      Description: Android + Google APIs
>      Based on Android 4.3.1 (API level 18)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : default/armeabi-v7a
> ----------
> id: 19 or "Google Inc.:Glass Development Kit Preview:19"
>      Name: Glass Development Kit Preview
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 11
>      Description: Preview of the Glass Development Kit
>      Based on Android 4.4.2 (API level 19)
>      Libraries:
>       * com.google.android.glass (gdk.jar)
>           APIs for Glass Development Kit Preview
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : no ABIs.
> ----------
> id: 20 or "Google Inc.:Google APIs:19"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 20
>      Description: Android + Google APIs
>      Based on Android 4.4.2 (API level 19)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86
> ----------
> id: 21 or "Google Inc.:Google APIs:21"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 1
>      Description: Android + Google APIs
>      Based on Android 5.0.1 (API level 21)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
>  Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
> ----------
> id: 22 or "Google Inc.:Google APIs:22"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 1
>      Description: Android + Google APIs
>      Based on Android 5.1.1 (API level 22)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
>  Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
> ----------
> id: 23 or "Google Inc.:Google APIs:23"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 1
>      Description: Android + Google APIs
>      Based on Android 6.0 (API level 23)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320
>  Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
> ----------
> id: 24 or "Google Inc.:Google APIs:24"
>      Name: Google APIs
>      Type: Add-On
>      Vendor: Google Inc.
>      Revision: 1
>      Description: Android + Google APIs
>      Based on Android 7.0 (API level 24)
>      Libraries:
>       * com.android.future.usb.accessory (usb.jar)
>           API for USB Accessories
>       * com.google.android.media.effects (effects.jar)
>           Collection of video effects
>       * com.google.android.maps (maps.jar)
>           API for Google Maps
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : google_apis/arm64-v8a, google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64

**cordova plugin:**

> cordova-plugin-badge 0.8.7 "Badge"
> cordova-plugin-camera 2.4.1 "Camera"
> cordova-plugin-compat 1.2.0 "Compat"
> cordova-plugin-console 1.1.0 "Console"
> cordova-plugin-contacts 3.0.1 "Contacts"
> cordova-plugin-device 1.1.7 "Device"
> cordova-plugin-facebook4 1.9.1 "Facebook Connect"
> cordova-plugin-file 5.0.0 "File"
> cordova-plugin-file-transfer 1.7.0 "File Transfer"
> cordova-plugin-geolocation 2.4.3 "Geolocation"
> cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
> cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
> cordova-plugin-intercom 5.0.1 "Intercom"
> cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
> cordova-plugin-splashscreen 4.1.0 "Splashscreen"
> cordova-plugin-statusbar 2.4.2-dev "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
> cordova.plugins.diagnostic 3.9.1 "Diagnostic"
> es6-promise-plugin 4.1.0 "Promise"
> ionic-plugin-deploy 0.6.7 "IonicDeploy"
> ionic-plugin-keyboard 2.2.1 "Keyboard"
> onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"

**Comment by sebasnavarrete** [comment]
![image](https://user-images.githubusercontent.com/7929302/35405583-995c55e0-01d4-11e8-972b-b43c389db58f.png)
I think that in cordova 7.0 the AndroidManifest.xml file is not located in the root of the android folder.

**Comment by ethanneff** [comment]
This is the logic in the SDK:

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/scripts/android/updateAndroidManifest.js#L33-L45

**Comment by sergii-frost** [comment]
Hi, 

I am facing same issue (even though AndroidManifest can be found under `platforms/android/app/src/main/AndroidManifest.xml`

Ionic info outpit:
```

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-sim           : 6.1.2
    Node              : v9.4.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Applications/android-sdk

Misc:

    backend : pro
```

cordova platform output:

```
Installed platforms:
  android 7.0.0
  ios 4.5.4
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

`stat -f %A platforms/android/app/src/main/AndroidManifest.xml` gives result:
`644` (or `-rw-r--r--`)

**Comment by ramkrishna70** [comment]
Hi Sergii,
I hope you doing good. But according to the last comment as you have given 644 (-rw-r--r--) permission to the file. Are you running the project with root privilege, if so you need to change the owner ship and simply run chmod -R 777 * in side the project folder.

I hope it will resolve the issue.
Thank You

**Comment by sebasnavarrete** [comment]
Hi Sergii, please try to update the branch plugin to the latest version. That helps me to solve the issue, if you still have the issue after update the plugin feel free to contact me and I will be glad to help you.

**Comment by sergii-frost** [comment]
Hi, 
I managed to get it working that time, but now the issue is back after `cordova-android` was updated to the version 7.0.0, as well as `branch-cordova-sdk` is 2.7.1.

I can see in `updateAndroidManifest.js` under node_modules that there is code present to handle new path to AndroidManifest.xml which is not in the root of `platforms/android` but in `platforms/android/app/src/main`, but I am still getting the same error `BRANCH SDK: Cannot write file .../platforms/android/AndroidManifest.xml`.

I cannot understand why it tries to write to file on wrong path.

@sebasnavarrete if you have any thoughts, could you please help with this?

**Comment by sequoiaat** [comment]
@sergii-frost can you you please update to latest version of branch Cordova sdk and see if you still have the same issues.
