### ISSUE TITLE
Cordova Branch Plugin seems to be changing apk release signing signature

### ISSUE THREAD

**Issue by kd8ssq** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#424]
I've been working on a new app and got to the point where I was looking to test it in Testflight and as an Android Alpha release.  I was able to submit it to Testflight fine but when I went to the Google Play Store, I kept getting the error "You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR (APK Signature Scheme v2 signer #0): APK integrity check failed. CHUNKED_SHA256 digest mismatch. " when I went to upload the apk.

I was able to narrow it down to the branch-cordova-sdk plugin.  If I remove that plugin, I can upload the apk without issue.  Not sure if it's conflicting with another plugin or not.

Cordova: 7.1.0
Android: 6.3.0
branch-cordova-sdk: 2.6.23

Addl plugins:
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ios-no-export-compliance 0.0.1 "iOS No Export Compliance" - custom
cordova-plugin-ios-privacy-descriptions 0.0.1 "iOS 10 Privacy Descriptions" - custom
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 4.0.0 "Media"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 3.7.3 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
nl.kingsquare.cordova.background-audio 1.0.1 "background-audio"
phonegap-plugin-push 2.1.2 "PushPlugin"

Any help would be greatly appreciated.

**Comment by sojanpr** [comment]
@kd8ssq Do you still face the signing issue?Branch SDK  doesn't  have any thing that can affect the signing process. Could you please share how you solved it for others reference.

**Comment by kd8ssq** [comment]
@sojanpr I haven't figured out the issue, but I whacked all my plugins and started adding them back in one by one.  I started with cordova-plugin-crosswalk-webview and branch-cordova-sdk and built the release and it let me add it to the Play Store.  So I wanted to do more investigating by adding each plugin back one at a time to see if I could narrow it down more.
