### ISSUE TITLE
initSession + clicked_branch_link behaviour question

### ISSUE THREAD

**Issue by gonzaloserrano** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#428]
Hi there,

I've managed to configure my app in the Branch dashboard and properly installed and configured the cordova plugin properly.

So far I just got some behaviour that not sure if it's intended or not.

Lets say my app link is configured as `my.app.link`.

Clicking in a like like `https://my.app.link` opens the app with the following `initSession()` `data`:
```json
{
  "~referring_link": "https://my.app.link",
  "+clicked_branch_link": true,
  "~id": 0,
  "+match_guaranteed": true,
  "+click_timestamp": 1518009580,
  "~creation_source": 6,
  "+is_first_session": false
}
```

So far, so good.

But when I click in a link like `https://my.app.link/foo`, if it *HAS NOT* been configured as a "Quick Link" in the Branch dashboard, the data received when the app is open is:
```json
{
  "+clicked_branch_link": false,
  "+is_first_session": false,
  "+non_branch_link": "https://my.app.link/foo",
}
```

I expected this to have `"+clicked_branch_link": true` since it IS a branch link, although not created explicitly in the dashboard.

Any hints?

Thanks.

**Comment by ethanneff** [comment]
Hello @gonzaloserrano,


We have multiple ways to create Branch Deep Links (outside of the Dashboard quick links) ([docs](https://docs.branch.io/pages/links/integrate/#create-deep-links)):
   - Use [Quick Links](/pages/dashboard/analytics/#quick-links) for fast link creation and easy tracking
  - Use our [App SDK](#dialog-code?ios=create-deep-link&android=create-deep-link&adobe=create-deep-link&cordova=create-deep-link&mparticleAndroid=create-deep-link&mparticleIos=create-deep-link&titanium=create-deep-link&reactNative=create-deep-link&unity=create-deep-link&xamarin=create-deep-link) to create and share links within your app
  - Use our [Web SDK](/pages/web/integrate/#create-deep-link) to create to links convert web to app users
  - Use our [HTTP API](/pages/apps/api/#link-create) to programmatically create links from your server
  - Use our [Chrome Extension](https://chrome.google.com/webstore/detail/branch-link-creator/pekdpppibljpmpbcjelehhnldnfbglgf) to generate links from your browser

Unfortunately, you cannot create links by appending `/foo` to your link domain. This link will only redirect to your fallbacks URLs set in your Branch Dashboard (https://dashboard.branch.io/link-settings). This link will not pass data (`"+non_branch_link": "https://my.app.link/foo"`).

To pass link data, you must create a link with one of the methods mentioned above.

Thanks,

**Comment by gonzaloserrano** [comment]
Understood, thanks.
