### ISSUE TITLE
Opening deeplink inapp

### ISSUE THREAD

**Issue by aless673** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#430]
Hi,

in Ionic v3 the deeplink is working fine when i use it outside the app but nothing is fired when i use it inside the app with this command 

`window.open(url, '_system', 'location=yes');`

```
Branch.initSession(data => {
      console.log(data); // print when coming in from outside but not from inside
});
```

Any idea ?

**Comment by ethanneff** [comment]
related to https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/430

**Comment by aless673** [comment]
There's a problem, you linked the wrong issue (my own issue)

**Comment by ethanneff** [comment]
Well, that is embarrassing haha. Here is the related issue https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/394. I have revived it as well.
