### ISSUE TITLE
Should routing work when using the URI scheme?

### ISSUE THREAD

**Issue by dfattlar** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#431]
Hello,
We are able to get deep linking, with routing, working with the basic config outlined for a Universal Link using Ionic1. The link opens the app and triggers our routing functions in the callback to Branch.initSession(). However when using just the URI scheme, the app opens but does not route. The callback to Branch.initSession() is never called. Should we expect to be able to route when just the URI scheme is used? It seemed to be possible in [this comment](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/411#issuecomment-355462872), but wasn't clear in the documentation. This issue also presents itself in our Android tests.

Links used:
`https://ourapp.app.link/LseujdfKMK?formID=form123`    // works with routing
`ourapp://open?formID=form123`   // opens app, but initSession callback never called

Cordova CLI: 8.0.0
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0
Node version: v6.11.4
Xcode 9.2
Build version 9C40b

**Comment by evanoralph** [comment]
we having the same issue but its only not working if the query string is pass by #

**Comment by ethanneff** [comment]
Hello!

Here are some example deep links and their corresponding outputs in `branch.initSession()`:

### https://cordova.app.link/YOA8gtSe6K
```
{
  "$locally_indexable": true,
  "$ipad_url": "http://www.example.com/ipad",
  "~stage": "new user",
  "~creation_source": 3,
  "$og_title": "Content 123 Title",
  "custom_array": [
    1,
    2,
    3,
    4,
    5
  ],
  "custom_string": "data",
  "$custom_fields": "{\"testing\":123,\"custom\":\"data\",\"this_is\":true}",
  "+click_timestamp": 1520452327,
  "~tags": [
    "one",
    "two",
    "three"
  ],
  "~feature": "onboarding",
  "$canonical_identifier": "content/123",
  "$ios_url": "http://www.example.com/ios",
  "custom_boolean": true,
  "+clicked_branch_link": true,
  "$android_url": "http://www.example.com/android",
  "$identity_id": 467413196173649340,
  "$currency": "GBD",
  "custom_object": {
    "random": "dictionary"
  },
  "$og_image_url": "http://lorempixel.com/400/400/",
  "~id": 500015444967786400,
  "~referring_link": "https://cordova.app.link/YOA8gtSe6K",
  "$one_time_use": false,
  "$desktop_url": "http://www.example.com/desktop",
  "$match_duration": 2000,
  "custom_integer": 1520451198464,
  "$price": 12.12,
  "$canonical_url": "https://example.com/content/123",
  "~campaign": "content 123 launch",
  "$og_description": "Content 123 Description 1520451196906",
  "+is_first_session": false,
  "~channel": "facebook",
  "+match_guaranteed": true
}
```
### branchcordova://open?link_click_id=500015444967786346
```json
{
  "$locally_indexable": true,
  "$ipad_url": "http://www.example.com/ipad",
  "~stage": "new user",
  "~creation_source": 3,
  "$og_title": "Content 123 Title",
  "custom_array": [
    1,
    2,
    3,
    4,
    5
  ],
  "custom_string": "data",
  "$custom_fields": "{\"testing\":123,\"custom\":\"data\",\"this_is\":true}",
  "+click_timestamp": 1520452480,
  "~tags": [
    "one",
    "two",
    "three"
  ],
  "~feature": "onboarding",
  "$canonical_identifier": "content/123",
  "$ios_url": "http://www.example.com/ios",
  "custom_boolean": true,
  "+clicked_branch_link": true,
  "$android_url": "http://www.example.com/android",
  "$identity_id": 467413196173649340,
  "$currency": "GBD",
  "custom_object": {
    "random": "dictionary"
  },
  "$og_image_url": "http://lorempixel.com/400/400/",
  "~id": 500015444967786400,
  "~referring_link": "https://cordova.app.link/YOA8gtSe6K",
  "$one_time_use": false,
  "$desktop_url": "http://www.example.com/desktop",
  "$match_duration": 2000,
  "custom_integer": 1520451198464,
  "$price": 12.12,
  "$canonical_url": "https://example.com/content/123",
  "~campaign": "content 123 launch",
  "$og_description": "Content 123 Description 1520451196906",
  "+is_first_session": false,
  "~channel": "facebook",
  "+match_guaranteed": true
}
```

### branchcordova://hello/world?yes=123
```json
{
  "+clicked_branch_link": false,
  "+is_first_session": false,
  "+non_branch_link": "branchcordova://hello/world?yes=123"
}
```



Depending on your use case, you may need to update your logic within your `branch.initSession()`. Furthermore, you should receive data whenever the app is backgrounded or terminated. If not, you will want to make sure your `branch.initSession()` method is being called by your `deviceready` and `resume` lifecycles. 

Thanks,
