### ISSUE TITLE
iOS Debugger Error

### ISSUE THREAD

**Issue by malua** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#434]
`[branch.io] Branch.m(187) Log: Branch version 0.22.4 started at 2018-03-16 16:29:05 +0000.
 [branch.io] BNCSystemObserver.m(239) Error: Please report this to Branch: Build date is (null) and install date is 2018-03-16 16:28:12 +0000. iOS version 11.2.6.`

I get this error in iOS debugger. Since it literally says 'report this to branch', i thought i would do that. If you need more information, i will try and provide it.

thanks!

**Comment by malua** [comment]
ok it seems, that branch doesn't get the app version. should have looked in bncsystemobserver before posting this.

**Comment by E-B-Smith** [comment]
Thanks for reporting this! These reports are super helpful to us so we can make sure the SDK continues to work correctly.

I've updated this part of the underlying SDK code recently.  We'll get an update to the Cordova SDK shortly.

**Comment by ethanneff** [comment]
Hello @malua,

I have just updated the Branch Cordova SDK. I would recommend updating to the latest version `2.6.24`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update Branch Cordova SDK.

Thanks,

**Comment by malua** [comment]
Thanks! Error is gone, also deeplinking (more specifically passing deeplink data) didn't work on iOS 11 anymore. It's working again now. Did something change?

**Comment by ethanneff** [comment]
Hello @malua, there is currently a bug in iOS where the AASA file is not being downloaded. We have posted a warning in our docs here: https://docs.branch.io/pages/apps/cordova-phonegap-ionic/

I apologize for the inconvenience. We are doing our best to coordinate with Apple to get this fixed as soon as possible.

Thanks,
