### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by bhavinwebdesk** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#436]
Hello Branch Team,

I am ionic developer and I am already using [Firebase Dynamic Link ](https://ionicframework.com/docs/native/firebase-dynamic-links/) and [Deep Link](https://ionicframework.com/docs/native/deeplinks/) within my live app.

My reason to move from Firebase to branch is because of deprecated plugin of Deep Link
by ionic community and there are many edge cases that they (Deep Link) did not handle well.

Is there any migration guide for move to firebase to Branch with support of firebase? I search through open and closed issue. I found that we can not use both plugin (Branch and Firebase) at same time because both override same properties in android and iOS.

Thanks,
Bhavin.

**Comment by ethanneff** [comment]
Hello @bhavinwebdesk,

We will gladly do whatever we can to make our plugins communicate well with each other. However, it looks like the Firebase Dynamic Link plugin is still in beta. Once that plugin is stable, we will make the needed code changes so both plugins will work.
<img width="400" alt="screen shot 2018-03-20 at 8 55 51 am" src="https://user-images.githubusercontent.com/2933593/37666558-138dcb7e-2c1d-11e8-8246-40f28a9feb31.png">
 
There is a chance that both SDKs work fine already. The best way is to install both and test some Branch Deep links (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios) and Firebase Dynamic Links.

Best,

**Comment by bhavinwebdesk** [comment]
Thanks @ethanneff ! I will check and let you know. Till then I am closing this issue.
