### ISSUE TITLE
How to install this plugin

### ISSUE THREAD

**Issue by premtemp** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#439]
Hello.

 Sorry .. how do you install this plugin...   Is it an  npm install or cordova install..... 

Thanks for your help

**Comment by ethanneff** [comment]
Hello,

The best way to install the Branch Cordova SDK is to follow this guide: 
https://docs.branch.io/pages/apps/cordova-phonegap-ionic/

You should install the plugin by adding the Branch values your `config.xml` file. 

Thanks,

**Comment by newuser44** [comment]
That site doesn't not explain how to install this plugin for ionic.  
???
ionic cordova plugin add cordova-ionic-phonegap-branch-deep-linking
npm install --save @ionic-native?????

Is this part of ionic native or its own npm package?

**Comment by newuser44** [comment]
This did not work 
ionic cordova plugin add cordova-ionic-phonegap-branch-deep-linking
I'll keep guessing

**Comment by newuser44** [comment]
The only one I can't figure out is the <uri-scheme value="branchcordova" />
myapp://

**Comment by ethanneff** [comment]
Were you able to get Branch installed? The best way to get the SDK installed is by following this guide https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#integrate-branch. Having branch in your `config.xml` and running `cordova run ios` should install the plugin.

**Comment by newuser44** [comment]
Yes I think so.  I can see it got added to package.json. 
What gets confusing is we don't have a uri.   We do have an android and ios app.  (do I select yes or no for the first question?) 

A uri-scheme is required in the config.xml  not sure what to put there if we don't have one?  

I can't get Universal link working.  I build the ios app.  I sent an email with the app link to the phone. I click the link and it opens it up in the browser, then asking if you want to open this in the app store.  

The app is on the phone it should just take me to it.  

Similar with Android, when I click the link I get a box asking which app should open it, the app or chrome.  
I don't want that.  

Everything seems to be set up correctly for app links and universal links.  Not sure what else to check.

**Comment by fdambrosio** [comment]
@newuser44 I have the same problem, I've configured the branch dashboard but when I click on the link branch opens the app on the appstore (but before I've installed the app from xcode)
