### ISSUE TITLE
Handle Non-Branch Deep links [ Firebase email login link]

### ISSUE THREAD

**Issue by Bengejd** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#442]
I want to start off by thanking you guys for all of your hard work on this wonderful plugin. I have tested Branch.io links, and they work flawlessly.

I am sending the user a Firebase passwordless email link, which in theory they would click, it will authenticate and they will be logged in. But I am not sure if this is possible to do within Branch. I was wondering if I could set the Firebase URL link to the Branch.io link, and then pass the authentication data to the Branch.io link from Firebase.

**Comment by Bengejd** [comment]
I figured out the answer to this, and it works flawlessly!

Basically, you have to:
-  go into Firebase Dynamic Links, check the box that says "Skip the app preview page (not recommended)". 

- Create your Branch.io link, copy the link URL and whitelist it in your Firebase/Authentication/Sign in Methods/Authorized Domains section of your Firebase Console.

- After you have done that, go into your `environment.actionCodeSettings` and set the URL to be the Branch.io link that you copied above. After that, you are set! It should all work as expected, the app will originally route to the Firebase link, after which it redirects to the Branch.io deep link, passing the parameter `'+referrer']` which is your Firebase auth URL for that particular user, which can be accessed by using the Branch.io subscription method, and just grabbing the `data['+referrer']` and passing it into your Firebase Authentication method, and boom! You are now fully authenticated.

**Comment by ethanneff** [comment]
Hello @Bengejd,

I apologize for not responding sooner. I am glad you were able to get it working. I'll coordinate with our documentation team to see if we can add your notes to it. I can see them being very useful for future developers.

Thanks,

**Comment by Bengejd** [comment]
Hi @gibbsvjy007. Sorry for the delayed response, I meant to share this with you a couple days ago, but time just got away from me. 

[Here](https://medium.com/@bengejd/connecting-firebase-dynamic-link-authentication-with-the-edge-cases-of-branch-io-b31c2fc1d63e) is a short article that I wrote regarding the solution. I hope this helps!
