### ISSUE TITLE
branch.io not passing details after clicking link and installing app

### ISSUE THREAD

**Issue by luisvillara** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#447]
Hey @ethanneff, I'm having the same issue, when I open the link (in Safari) and I install the app, sometimes the Deep Link doesn't work at all, this is what the logs looks like at that moment:

```
BNCNetworkService.m(219) Debug: Network finish operation https://api.branch.io/v1/install 0.639s. Status 200 error (null).
{"session_id":"516029442108308059","identity_id":"516029442087709188","link":"https://mel2.test-app.link?%24identity_id=516029442087709188","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"516029441995093675"}.
2018-04-20 19:07:13.041211-0500 New Stand[31130:4815900] [branch.io] BNCServerInterface.m(771) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = 516029441995093675;
    "identity_id" = 516029442087709188;
    link = "https://mel2.test-app.link?%24identity_id=516029442087709188";
    "session_id" = 516029442108308059;
```

It's weird because sometimes it works, this is so frustrating.

This is the same log, it says `install` but I'm not sure what those it means because my app couldn't read that:
<img width="1403" alt="screen shot 2018-04-20 at 7 13 45 pm" src="https://user-images.githubusercontent.com/2540621/39078369-ff40dbfa-44ce-11e8-8979-e7bec5e375ca.png">

I'm using the branch-cordova-sdk (v2.6.24).

**Comment by ethanneff** [comment]
`"+is_first_session":true` is an `install`. 
`"+is_first_session":false` is an `open`.

Can you elaborate on the issue? I'm not too sure what the problem is. Thanks,
