### ISSUE TITLE
Unclear documentation for disableTracking

### ISSUE THREAD

**Issue by Morathil** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#453]
Hi, we are a bit confused how to disable trackings with the `disableTracking` function.

The readme says:
```
// for GDPR compliance (can be called at anytime)
Branch.disabledTracking(false);
```

But when we have a look at `src/index.js` `disableTracking(false)` ([link](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/index.js#L52)) sets `this.trackingDisabled` to `false` what is double negative and would mean tracking is enable (not disabled).

Furthermore the android [documentation](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/android/io/branch/BranchSDK.java#L579) of this function is also a bit confusing. (enable debugging mode?)

Can you please clarify this, as we want to do it the right way?

**Comment by ethanneff** [comment]
Hello! 

I can understand the confusion. The default is 'Branch.disabledTracking(false);' or not calling the method at all. If you want to enable GDPR compliance, set the value to 'true'. This will disable tracking on our backend.

Hope this clears up everything.

**Comment by Morathil** [comment]
Ok cool, thanks! 👍
