### ISSUE TITLE
AppDelegate methods are not firing

### ISSUE THREAD

**Issue by undersieg** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#462]
After installing plugin and setup everything I was trying open app from banner(Safari) with some data. App was opening fine, but I was not receiving data and I noticed that methods from AppDelegate (BranchSDK) was not firing. 
I added swizzled method to AppDelegate file which helped me out with it:

```
+ (void)load{
    Method original, swizzled;
    original = class_getInstanceMethod(self, @selector(init));
    swizzled = class_getInstanceMethod(self, @selector(branch_sdk_init));
    method_exchangeImplementations(original, swizzled);
}
- (AppDelegate *)branch_sdk_init{
    return [self branch_sdk_init];
}
```

I hope it will help someone with the same problem.

**Comment by csalmi-branch** [comment]
@undersieg Are you still experiencing this issue?

**Comment by undersieg** [comment]
Actually I refactored my all plugins and it started working. In my case was that if it's more than one AppDelegate category with the same methods override it will randomly choose method and just one will run.  Currently just AppDelegate+BranchSdk is overriding native methods.

**Comment by csalmi-branch** [comment]
Thanks for the update! I'm closing this issue, but if you run into this problem again please either file a support ticket, or open a new github issue.
