### ISSUE TITLE
initSession promise is not resolved on app resume on Android

### ISSUE THREAD

**Issue by Luro91** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#463]
Hi,
when disabling tracking (`Branch.disableTracking(true)`) on Android the promise `Branch.initSession()` is not resolved anymore on app resume.
We are waiting for the promise to be resolved before we finish our app resume process. Now that the promise is never resolved our app gets stuck in the resume screen.

**Comment by sequoiaat** [comment]
@Luro91 We tried it on the ionic app, we are unable to reproduce it. Are you trying on ionic/cordova/phonegap?

On ionic it opens the app with data on resume.

We used latest branch SDK 3.0.1. Can you please try it on the latest version and let us know if you still face this issue.

**Comment by sequoiaat** [comment]
@Luro91  Since we have not heard back , we will close the issue. if you still face the issue please feel free to reopen
