### ISSUE TITLE
Send and count invites

### ISSUE THREAD

**Issue by scrabionau77** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#464]
First of all, thanks for this wonderful plugin. I use it in my Cordova app and it work very well.

Now I have a new need.
Within the app, users can send invitations to their contacts (by e-mail or text message). The invitation contains a link to download the app. The app must store every invitation in the database.
When one of the invited users downloads the app by invitation, a credit is assigned to the user who sent the invitation.

For this, actually i use firebase-invitation to send invitations by email or sms and this plugin return the number of sent invites and a reference-id.
But when i click on the dynamic-link in the invitation email/sms, i can download app from Store but when i start app, branch doesn't fire.
Note that if instead I click on the invitation when the app is already installed, branch fires!

So the question is:
1) Is there a way to handle firebase dynamic link?
2) or is there a way to send invitations by email/sms using branch and track (by javascript, in the process of sending) each single invitation by a reference-id?

Sorry for my bad english!
Thanks in advance for any help

**Comment by sequoiaat** [comment]
Could you please check if you are setting Branch.disableTracking(true) before calling Branch.InitSession?
Answers for above questions:-
By using custom share sheet ,we can send invitation(deeplink) by email/sms and by setting the identity of a user we can track events, deep links, and referral using single userid's

**Comment by csalmi-branch** [comment]
@scrabionau77 did the response above help resolve your issue? If not, could you provide more specifics around what version of the SDK you are using and your configurations?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
