### ISSUE TITLE
Data not passed on resume, but is passed if app is completely closed.

### ISSUE THREAD

**Issue by Bengejd** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#468]
I ran into an issue in our production app that randomly popped up between the time for testing and approval of the app store for the update. Basically what is happening is that the app-link, is being called only when the application is completely closed, not when it is idling in the background.

There was another [thread](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/411) that was closed in January that talks about the issue that I'm having now. 

Here is an example log output about what is happening. 

<img width="1141" alt="screen shot 2018-05-23 at 10 29 21 am" src="https://user-images.githubusercontent.com/11723093/40431847-42f13c30-5e76-11e8-8d63-bec77ccbb516.png">

They are about 30 seconds apart (because I was excited that it finally worked again), and then it stopped working. But If I close the app after I send the email link, and then click the link, it works.

**Comment by Lukizzle** [comment]
I was facing the same issue. Links opened correctly when the app was closed. But when the app was in the background, the link opened up the app but Branch.initSession didn't do anything.
I was able to solve it by upgrading branch-cordova-sdk to 3.0.0. Now everything works fine.

**Comment by sequoiaat** [comment]
@Bengejd Have/Can you checked/check if the latest version of branch-cordova-sdk(3.0.0) solves your issue as suggested by **Lukizzle**?

**Comment by etchen99** [comment]
@sequoiaat - this is still a problem on 3.0.1
