### ISSUE TITLE
Always opening app store.

### ISSUE THREAD

**Issue by bear1030** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#470]
Hi all,
I am using branch-cordova-sdk.

I've integrated Branch.io for our phonegap project.

And it works fine for all except one device.
On iphone 7 plus it took me to the app store even though I've installed my app on my phone.

Please help me to find out why Branch-io doesn't see the app installed.
Thanks.

**Comment by sequoiaat** [comment]
Hi,

We are trying to reproduce the issue on iPhone 7 plus but we are unable to reproduce it. Would you have access to another device to see if you are getting the same issue on that also to eliminate any device dependency issue as we are not able to reproduce it.

Thanks

**Comment by Sarkar** [comment]
@bear1030, this might be a configuration issue. If it's working fine on other devices, it's possible that you're running into the AASA not being downloaded on iOS 11.2+ (a known bug on the platform). If you continue to have issues, please reach out to integrations@branch.io, and they can help solve it.
