### ISSUE TITLE
Universal link does not open application it take me to Safari

### ISSUE THREAD

**Issue by darshitmaniar** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#473]
Hi 
I have integrated branch into my Cordova application.

The universal link is not working only on IOS it takes me to safari but it works fine on Android.

I installed my plugin this way: 
cordova plugin add branch-cordova-sdk

added branch-config element to config.xml
```
<branch-config>
        <branch-key value="branch_key_live" />
        <uri-scheme value="myapp2" />
        <link-domain value="myapp2.app.link" />
        <ios-team-release value="xxxxxxxxxx" />
</branch-config>
```
<preference name="AndroidLaunchMode" value="singleTask" />

Create a link to open an app like this: https://myapp2.accept.dev.nl
Please let me know what I'm doing wrong.

![capture](https://user-images.githubusercontent.com/25265362/41287196-9892075c-6e5f-11e8-8531-7ca3d276c4aa.PNG)

**Comment by darshitmaniar** [comment]
I am getting error while adding link domain

> Domain not properly configured; please CNAME your domain to 'custom.bnc.lt'. If you've already done this, note that it can take up to several hours to propagate.

**Comment by crabbydavis** [comment]
Did you close this because you figured out what was wrong? I'm facing a similar issue
