### ISSUE TITLE
BranchLinkId received as number

### ISSUE THREAD

**Issue by malua** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#474]
> The bug still exists. I am experiencing different behaviour when I open links differently.
When I open/click a branch link directly (i.e. a shared link on WhatsApp) the app receives ~id as number.
branch_bug_directly
When I open the link by pasting it into a browser (i.e. chrome) the app receives ~id as string.
branch_bug_browser
As we currently depend on ~id our workaround is to make a separate HTTP request retreiving the data via the link url.

[https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/409](url)

**Comment by csalmi-branch** [comment]
@malua Are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
