### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by paulstelzer** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#475]
I using the branch cordova plugin successful on Android. Here the user can create and share the link without problems. If I create the link on iOS, this is the result:

`https://MY.app.link?%24identity_id=539199043147205089`

On Android everything is okay and the link is:

` https://MY.app.link/16O3ywoJ2N`

So the iOS link opens the app, but has no data in it. If I open the Android Link on Android Smartphone, the data will be read with no problems. If I open it on iOS, no data are in it ("`+clicked_branch_link: false`")

So it seems that the cordova plugin for iOS is not working correctly. I will test what causing the problem and update this thread. Maybe another has the same problem, then please let me know.

To make it clear: Clicking on the link opens the app, but then he has no deep link data and says that no branch link was clicked.

**Comment by sequoiaat** [comment]
@paulstelzer We are unable to reproduce it. Can you please mention the versions that you're using? Like,
1. branch SDK version
2. Cordova/ionic versions
3. iOS version

**Comment by paulstelzer** [comment]
I am using the latest version of Branch Cordova Plugin (3.0.0) - my device was iOS 11 - I think it is similar to #477

**Comment by paulstelzer** [comment]
After upgrading my project to Ionic4 / Angular6, it works now. Seems that I made something wrong on the iOS side

**Comment by sequoiaat** [comment]
@paulstelzer We are  unable to reproduce this issue as when we tried the steps you mentioned it worked for us.  Can you Please try using the branch SDK version that I used is 3.0.1 instead of 3.0.0 and Facebook SDK version 2.4.0  instead of 2.2.0

**Comment by paulstelzer** [comment]
> We are unable to reproduce this issue as when we tried the steps you mentioned it worked for us. Can you Please try using the branch SDK version that I used is 3.0.1 instead of 3.0.0 and Facebook SDK version 2.4.0 instead of 2.2.0

@sequoiaat Still not working for me - I will create a repository, then you can take a look

**Comment by paulstelzer** [comment]
@sequoiaat So, the repo is ready -> https://github.com/paulstelzer/branch-io-demo

I have uploaded ios platform, too so you can start directly by opening Xcode and select the xcodeproject.

Then open the app on iOS and tap on the "GENERATE SHARE LINK". You will see a generated link like that: https://MY.app.link?%24identity_id=539199043147205089

If you now do the same with the Android version, you will see a response like https://MY.app.link/xysfasf and this is a correct link!

**Comment by paulstelzer** [comment]
Damn it :D Forgot to add the `canonicalIdentifier` - So everything works on iOS :)

**Comment by tarun57** [comment]
Hi i'm using branch but my app is not open from link on ios it is redirecting on link and not open my app.
But on android its working Ok.
