### ISSUE TITLE
Installing plugin breaks Ionic browser production build

### ISSUE THREAD

**Issue by djmeph** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#480]
After attempting to install the `branch-cordova-sdk` plugin in my Ionic 3 project, the browser production build breaks and returns the console error: "TypeError: window.clientInformation is undefined"

Steps to reproduce:

1. Add plugin directive and branch configuration in config.xml
2. re-compile browser app with --prod switch `ionic cordova build browser --prod`
3. Bootstrap browser app (In this case, with a docker container)

I have published the broken version of the app with the Branch plugin installed to the following address: 

https://branch-debug.azurewebsites.net/

Compare that to our production dashboard, which does not have the plugin installed:

https://dashboard.boostup.com

After bringing this issue up on Twitter, I was told by support account to submit this ticket. Thanks for you help!

**Comment by sequoiaat** [comment]
@djmeph we're able to see the  error on Firefox.  window .client information is not supported on Firefox, that's why it's returning undefined. We are working on a fix and will be release in 2-3 days

**Comment by djmeph** [comment]
Yes, I'm using Firefox. Understandable why this was overlooked. Thanks for looking into it, sounds like the fix will be ready just in time for our next sprint!

**Comment by sequoiaat** [comment]
@djmeph We have fixed this issue. Please check.
We are closing it, please re-open if you are facing any issue.
