### ISSUE TITLE
initSession() promise returning data on "resume" when no Branch link clicked

### ISSUE THREAD

**Issue by dfibuch** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#483]
I've just been doing some Branch debugging and noticed something new since the change to 3.0.0 and `initSession()` being a promise.

If I tab away and back into my app the `resume` even fires, which then triggers `Branch.initSession()` to run, which is expected behaviour. What isn't expected behaviour and something that didn't happen before these changes is that now that code returns me data in the promise:

![image](https://user-images.githubusercontent.com/4235431/43517610-461baa2a-9581-11e8-8cbc-6823e6243085.png)

So this now means that I have to check for the `+clicked_branch_link` parameter to see if the user actually clicked the link or if it's just a dummy promise being returned.

I guess isn't much of an issue but maybe it should be made more obvious for those upgrading because this has caused me weeks of weird behaviour that I couldn't understand and now know it's this passing data around and then failing.

**Comment by sequoiaat** [comment]
@dfibuch We tried it on the ionic app, we are unable to reproduce it.  It looks like you are using ionic, please confirm.

We tab away and back into the app, the app opens with no deep link data.

We used the latest branch SDK 3.0.1. Can you please try it on the latest version and let us know if you still face this issue.

**Comment by dfibuch** [comment]
Yea we are using Ionic v1 (I know I know...). I have come off this project now and won't be looking at it for a while so happy to close this and come back to it if I can recreate it when/if I do end up working on it again.

For my work around I just put an `if` statement to check that I actually have link data.
