### ISSUE TITLE
cordova and branch : Deep link does not work when App is closed but works on resume

### ISSUE THREAD

**Issue by leaditnet** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#488]
hi,
Deep link works for me on resume but it never fires, if the app was closed:
here is my code:
  ```
  this.platform.ready().then(() => {
      setTimeout(() => {
        branchInit();        
      }, 5000);
    });
const branchInit = () => {
    if (!this.platform.is('cordova')) { 
      return; }
    const Branch = window['Branch'];
  Branch.initSession(data => {
});
}   
```

Any ideas are appreciated, thanks

Update: 
Interesting thing, 
Android : the resume works (get the link data) on Android while the launch does not work
IOS: Opposite! the launch works , while the on resume does not work (initSession seems to be ignored)

**Comment by etchen99** [comment]
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/468

I am still having this problem on 3.0.1

**Comment by csalmi-branch** [comment]
@leaditnet and @etchen99 were you able to check the disableTracking setting?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
