### ISSUE TITLE
Chinese App Stores / Baidu App Store

### ISSUE THREAD

**Issue by gubyy** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#489]
I'm wondering when a deep link is clicked by a Chinese user on android where they will be directed to. They don't use the google play store and have multiple popular app stores instead. If a user's primary app store is Baidu, is it possible to direct them to the Baidu app store download after clicking the link?

**Comment by sequoiaat** [comment]
@gubyy Can you please try by specifying the Baidu Store URL as the custom URL in the dashboard

![image](https://user-images.githubusercontent.com/20103264/44455069-c63c4800-a61a-11e8-88af-cfc95a437d98.png)

**Comment by sequoiaat** [comment]
@gubyy  We assume that this issue is fixed for you. please feel free to reopen if its still did not solve the problem
