### ISSUE TITLE
Not working facebook login when plugin update to 3.0.0

### ISSUE THREAD

**Issue by YaroslavG** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#490]
Hi everyone, 
I try to upgrage branch-sdk plugin from 2.5.8 to the latest 3.0.0 I can't login with facebook. 

If branch is installed, on ios and when I click on the facebook login, I am prompted by facebook to authorize the app but when facebook returns to the app, branch seems to be intercepting the call and I am not receiving any of the response back from the facebook oauth call.
My logs:
[branch.io] BNCServerInterface.m(758) Debug: URL: https://api.branch.io/v1/open.
2018-08-29 17:33:35.674154+0300 2Meet[20183:9654928] [branch.io] BNCServerInterface.m(762) Debug: Body: {
"ad_tracking_enabled" = 1;
"app_version" = "0.1.67";
"apple_ad_attribution_checked" = 0;
"branch_key" = "<key_live>";
brand = Apple;
cd = {
mv = "-1";
pn = "<bundle_ID>";
};
country = UA;
debug = 1;
"device_fingerprint_id" = <device_fingerprint_id>;
"external_intent_uri" = "^fb\d+:";
"facebook_app_link_checked" = 0;
"first_install_time" = 1535356830958;
"hardware_id" = "C4BAF0D5-D985-4AF8-B621-61E3ED4827C5";
"hardware_id_type" = random;
"identity_id" = 563330891265323284;
instrumentation = {
"/v1/close-brtt" = 394;
};
"ios_bundle_id" = "com.App.myApp";
"ios_vendor_id" = "08FA843B-328B-4AFC-9DF5-D7D9602F6683";
"is_hardware_id_real" = 0;
language = ru;
"lastest_update_time" = 1535553159000;
"latest_install_time" = 1535550988706;
"local_ip" = "10.201.26.346";
model = "iPhone8,4";
os = iOS;
"os_version" = "11.3";
"previous_update_time" = 1535553159000;
retryNumber = 0;
"screen_height" = 1136;
"screen_width" = 640;
sdk = "ios0.24.2";
update = 1;
"uri_scheme" = "com.App.myApp";
"user_agent" = "Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E216 (4388349648)";
}
JSON: {"os_version":"11.3","ios_bundle_id":"com.App.myApp","debug":true,"country":"UA","is_hardware_id_real":false,"instrumentation":{"/v1/close-brtt":"394"},"sdk":"ios0.24.2","ad_tracking_enabled":true,"device_fingerprint_id":"564352474843369351","uri_scheme":"com.App.myApp","retryNumber":0,"previous_update_time":1535553159000,"facebook_app_link_checked":false,"external_intent_uri":"^fb\d+:","local_ip":"10.202.11.346","brand":"Apple","lastest_update_time":1535553159000,"update":1,"cd":{"pn":"com.App.myApp","mv":"-1"},"screen_height":1136,"apple_ad_attribution_checked":false,"model":"iPhone8,4","branch_key":"<key_live>","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E216 (4388349648)","first_install_time":1535356830958,"hardware_id":"C4BAF0D2-D974-4AF8-B621-61E5ED4827C6","os":"iOS","identity_id":"563332891265313284","hardware_id_type":"random","latest_install_time":1535550988706,"screen_width":640,"language":"ru","ios_vendor_id":"08FA843B-428B-4AFC-9DF5-D7D9602F6683","app_version":"0.1.67"}.

**Comment by Sarkar** [comment]
Hi @YaroslavG , this is by design. The way to get around this is by moving the openURL call below the Facebook Login call, in your deep linking handler. Can you move the FB oauth login logic above your Branch logic? That should let FB login resume.

**Comment by YaroslavG** [comment]
I just updated fb plugin to latest and this fixed my problem
