### ISSUE TITLE
How to get clicked link details in flight mode

### ISSUE THREAD

**Issue by anilsaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#491]
If mobile got no network, is it possible to get clicked link details as initSession will give error.

**Comment by sequoiaat** [comment]
No, if the phone has no internet connectivity then Branch SDK cannot connect to Branch Server. 

Please see this thread, it is on iOS SDK but you should get the idea
https://github.com/BranchMetrics/ios-branch-deep-linking/issues/734
