### ISSUE TITLE
Deeplinks not recognized on iOS 12 / Update to iOS SDK 0.25.5

### ISSUE THREAD

**Issue by malua** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#494]
On iOS 12 with branch sdk 0.24.2 universal links open the app correctly, but Branch doesn't recognize the links as branch links, and hence no deeplink data is passed into the app. I updated the branch ios SDK to 0.25.5 and deeplinking is working again.

I updated manually because i didnt see the updateNativeSDK script at first. Also this script looks for an gulp file which isn't there.

It would be awesome if someone updated the cordova plugin to use the lastest ios sdk, so iOS 12 is supported. thanks!

> branch-cordova-sdk: 3.0.1
> cordova-plugin-facebook4: 3.0.0

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.1.2
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.0
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : android 7.1.1, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic 5.2.4, cordova-plugin-ionic-webview 1.2.1, (and 21 other plugins)
> 
> System:
> 
>    Android SDK Tools : 26.1.1
>    ios-deploy        : 1.9.2
>    NodeJS            : v8.2.0
>    npm               : 6.1.0
>    OS                : macOS High Sierra
>    Xcode             : Xcode 9.4.1 Build version 9F2000

**Comment by sequoiaat** [comment]
Thanks for pointing it out . We will work on updating it next week

**Comment by csalmi-branch** [comment]
The Cordova plug-in is currently using iOS SDK 0.25.5, so I am closing this issue. If any further issues come up, please let us know.
