### ISSUE TITLE
Use of CocoaPods and Gradle

### ISSUE THREAD

**Issue by paulstelzer** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#495]
Currently the Branch SDK for Android and iOS is integrated in this project. I think it would be better if the Branch SDK will be loaded via CocoaPods (iOS) and Gradle (Android) to get the newest version of the Branch SDK automatically.

CocoaPods can be easily integrated on Cordova by using the following plugin: https://github.com/blakgeek/cordova-plugin-cocoapods-support

**Comment by Sarkar** [comment]
Thanks for submitting this PR. Closing.
