### ISSUE TITLE
iOS Ionic 3, initSession not being triggered on Resume

### ISSUE THREAD

**Issue by Tommyjohn05** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#502]
Hey all,

ripped out all of my code and went back to the basic setup to trigger alerts.

```
constructor(private platform: Platform, private statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      statusBar.styleDefault();
      splashScreen.hide();
      handleBranch();
    });

    platform.resume.subscribe(() => {
      handleBranch();
    });

    // Branch initialization
    const handleBranch = () => {
      // only on devices
      if (!platform.is('cordova')) { return }
      const Branch = window['Branch'];
      Branch.initSession().then(data => {
        if (data['+clicked_branch_link']) {
          // read deep link data on click
          alert('Deep Link Data: ' + JSON.stringify(data));
        }
      });
    }
  }

```

Alert does not trigger when resuming the app from the background.

Alert triggers as normal when launching the app fresh.

When Branch Debug mode is on, you can see the calls to the api:

```
[branch.io] BNCNetworkService.m(219) Debug: Network finish operation https://api.branch.io/v1/open 0.564s. Status 200 error (null).
{"session_id":"x","identity_id":"x","link":"https://x.app.link?%24identity_id=x","data":"{\"+match_guaranteed\":true,\"$marketing_title\":\"Go to scanner\",\"~creation_source\":1,\"~marketing\":true,\"+clicked_branch_link\":true,\"+click_timestamp\":1538363816,\"$one_time_use\":false,\"~id\":x,\"+is_first_session\":false,\"~referring_link\":\"http://x.app.link/scan\",\"page\":\"x\",\"~feature\":\"marketing\"}","device_fingerprint_id":"x"}.
2018-09-30 23:16:56.803348-0400 x[3719:906789] [branch.io] BNCServerInterface.m(771) Debug: Server returned: Status: 200; Data: {
    data = "{\"+match_guaranteed\":true,\"$marketing_title\":\"Go to scanner\",\"~creation_source\":1,\"~marketing\":true,\"+clicked_branch_link\":true,\"+click_timestamp\":1538363816,\"$one_time_use\":false,\"~id\":x,\"+is_first_session\":false,\"~referring_link\":\"http://x.app.link/scan\",\"page\":\"x\",\"~feature\":\"marketing\"}";
    "device_fingerprint_id" = x;
    "identity_id" = x;
    link = "https://x.app.link?%24identity_id=x";
    "session_id" = x;
}.
```

However, you cannot retrieve the data from the initSession promise on resume. Data retrieval works fine the first time you launch the app using the link.

Edit: removed all identity and app data and replaced it with an 'x'.

**Comment by sequoiaat** [comment]
Are you using latest Cordova SDK 3.0.1? If not please share the version you're using.

**Comment by mm44m6** [comment]
Hi, I'm having the same issue using Cordova SDK 3.0.1. It just doesn't trigger the initSession when the app is coming back from background mode. I'm using the exact same code as provided in this topic. Help?

**Comment by mm44m6** [comment]
> Are you using latest Cordova SDK 3.0.1? If not please share the version you're using.


Hi, @sequoiaat, I'm having the same issue using Cordova SDK 3.0.1. It just doesn't trigger the initSession when the app is coming back from background mode. I'm using the exact same code as provided in this topic. Help?

**Comment by TwashRocketLoans** [comment]
Upgraded to 3.1.0, Everything is working perfectly. Please close this ticket and thank you!

**Comment by mm44m6** [comment]
> > Are you using latest Cordova SDK 3.0.1? If not please share the version you're using.
> 
> Hi, @sequoiaat, I'm having the same issue using Cordova SDK 3.0.1. It just doesn't trigger the initSession when the app is coming back from background mode. I'm using the exact same code as provided in this topic. Help?

Forget about this, its working perfectly. I was calling the function inside the platform.ready() only instead of plataform.resume. my mistake

**Comment by sequoiaat** [comment]
@mm44m6 @TwashRocketLoans We are closing this issue . please feel free to reopen if you face any issues again
