### ISSUE TITLE
iOS ionic 3 empty data

### ISSUE THREAD

**Issue by adriansaenz** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#503]
Hey all,
I'm experimenting an issue when the link is tapped and the init session is triggered. The data returned is only showing two fields, +clicked_branch_link and +is_first_session (both are false). I'm using the version 3.0.1 of plugin and iOS 10.0 and iOS 11.2. The source code is the following:

this.branchio.initSession().then(
      data => {
        if (data["+clicked_branch_link"]) {
            console.log(data)
        }
      }
}

It does not matter from where link is tapped, messages app or apple notes, the behaviour is the same.

**Comment by warbadev** [comment]
same thing here did u solve this?

**Comment by sequoiaat** [comment]
@adriansaenz We will close this for now if you face any issue please feel free to reopen .
