### ISSUE TITLE
Deeplink not working when custom data with hyphen (-) is present

### ISSUE THREAD

**Issue by mujeeba** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#509]
If custom data is appended to deeplink which contains **hyphen (-)**, when this url link is clicked and **app is installed**,  app gets launched but we get  **+clicked_branch_link:false**

**Expected Behavior:**
URL below should launch mobile app and deeplink data should contain +clicked_branch_link:true
`http://xxx.app.link/zOYn9adsN?$desktop_url=http://abc.com/reset-password?q=B2C&token=$2jadghasdg
`

**Current Behavior:** 
Mobile app is launched when clicked on above URL but  `+clicked_branch_link:false`

Also Tried **Url encoding** and replacing **hyphen (-) with %2D** but nothing worked
`http://xxx.app.link/zOYn9adsN?$desktop_url%3Dhttp%3A%2F%2Fabc.com%2Freset-password%3Fq%3DB2C%26token%3D%242jadghasdg`

**works well when hypen(-) is removed** from URL
`http://xxx.app.link/zOYn9adsN?$desktop_url=http://abc.com/resetpassword?q=B2C&token=$2jadghasdg
`

**Comment by sequoiaat** [comment]
Can you please try underscore(_) instead of  hyphen(-)
Please refer https://docs.branch.io/pages/links/integrate/#pass-data-from-link-to-app

Does it work for you?

**Comment by sequoiaat** [comment]
@mujeeba we will close this PR if you still have issues please feel free to reopen it
