### ISSUE TITLE
App is crashing when running branch init in iOS

### ISSUE THREAD

**Issue by sangeethkumarsg** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#517]
I am using ionic v1 to build a cordova project. My app runs in android and iOS. But when I try to implement deeplinking using branch, the app is crashing. I am not able to track the console also. Here is the details of my app.

Node : 6.11.2
Cordova : 7.1.0
Ionic : 1.7.16

Plugin list

branch-cordova-sdk 2.6.24 "branch-cordova-sdk"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-admobpro-firebase 2.29.23 "AdMob Plugin Pro"
cordova-plugin-apprate 1.1.7 "AppRate"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova.plugins.diagnostic 3.1.7 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 1.0.9 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
phonegap-plugin-push 2.1.2 "PushPlugin"

Here is my code :

**Config.xml**
 ```
<plugin name="branch-cordova-sdk" spec="^2.5.0" />
<branch-config>
        <branch-key value="key_live_XXXXXXXX" />
        <uri-scheme value="xxxx" />
        <link-domain value="xxxx.app.link" />
        <ios-team-release value="XXXXXXX" />
    </branch-config>

```

Code :

```
// for development and debugging only
Branch.setDebug(true)

// for GDPR compliance (can be called at anytime)
Branch.disableTracking(true);

// Branch initialization
Branch.initSession().then(function(data) {
  if (data['+clicked_branch_link']) {
    // read deep link data on click
    alert('Deep Link Data: ' + JSON.stringify(data))
  }
})
```

The app is working fine in Android. But in iOS, it is keep on crashing. Please help

Update 1:
While debugging with xcode, I am getting the following error :

`*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInternalInconsistencyException> Invalid Branch key of type '<nil>'.`

I have my key specified in my config.xml as above. Not getting what is the real issue.

**Comment by sequoiaat** [comment]
@sangeethkumarsg   we have tried to replicate this issue but its running as expected . We will try to reproduce in in the latest version of xcode - 10  . Are you trying it also on the latest version

**Comment by sequoiaat** [comment]
@sangeethkumarsg  - SInce we have not heard back we are assuming the issue is solved. we will go ahead and close the issue. please feel free to reopen if you still face this issue
