### ISSUE TITLE
Git commit error, caused by branch-cordova-sdk@3.1.0

### ISSUE THREAD

**Issue by Bengejd** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#519]
I'm getting an error when trying to push a commit, which is being caused by something in the Branch.io SDK.

I've attached the error below.
<img width="596" alt="screen shot 2018-11-05 at 1 42 45 pm" src="https://user-images.githubusercontent.com/11723093/48019242-f4510480-e100-11e8-83aa-dc63228a4b62.png">

**Comment by sequoiaat** [comment]
@Bengejd  - sorry for the late reply 

 In the branch's package.json, we  included some scripts to run

 "scripts": {

    "validate": " echo 'run validation scripts'; node ./src/scripts/npm/updatePluginXml",

    "travis-deploy-once": " echo 'prevent multiple deploys'; travis-deploy-once",

    "commitmsg": " echo 'validate commit messages'; commitlint -e $GIT_PARAMS",

    "precommit": " echo 'run prettier on commit'; lint-staged",

    "examples": " echo 'generate examples'; node ./src/scripts/examples",

    "prettier": " echo 'run prettier'; prettier --write './{src,testbed,tests}/**/*.js'",

    "lint": " echo 'run code linter'; eslint --ext=js --fix ./src",

    "semantic-release": " echo 'run continuous integration'; semantic-release"

  }

*In this, on precommit, you have provided  a  "lint-staged" to run.

*"lint-staged" is added as a devdependency and is used to run linters against staged git files and filter it with the given argument pattern.

*Here in branch's package.json, the command given in lint- staged are


  "lint-staged": {

    "src/*.{js,json,css,md}": [

      "prettier --write",

      "git add"

    ]

  }

* On the error reported, since it's given as "lint-staged" command not found.

*This error may occurs due to  "lint-staged" library installation failure.

**Comment by Mike1707** [comment]
Hey! How can we solve this issue? Installing _lint-staged_ globally leads to the next missing dependency _commitlint_ and after installing this library git reports `Error: Cannot find module "@commitlint/config-conventional"`.

**Comment by csalmi-branch** [comment]
@Mike1707 Did @sequoiaat's response help you fix this issue?

**Comment by Mike1707** [comment]
Hey @csalmi-branch! Unfortunately, it didn't help because I'm not sure what to do. It would help to explain some steps which solve this issue or which I can try. Normally, I just install the packages over npm and everything works out of the box.

**Comment by Mike1707** [comment]
Hey @sequoiaat, installing the missing library just in my project root doesn't work either. Also, I tried to run `npm i` in `myproject/node_modules/branch-cordova-sdk` which leads to the following output:

```
npm WARN deprecated travis-deploy-once@5.0.11: We recommend to use Travis Build Stages instead
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> husky@0.14.3 install myproject/node_modules/branch-cordova-sdk/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
trying to install from sub 'node_module' directory, skipping Git hooks installation
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 1235 packages from 1138 contributors and audited 12310 packages in 22.143s
found 0 vulnerabilities
```

Due to the warning, I run `npm i ajv@^5.0.0`. Nevertheless, the git commit shows the following in Sourcetree: 

```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/88/2zw_1_fx3nq_xxcllz326h8m0000gn/T/SourceTreeTemp.GPD8rO -a 
husky > npm run -s precommit (node v10.14.2)

run prettier on commit
sh: lint-staged: command not found

husky > pre-commit hook failed (add --no-verify to bypass)
Completed with errors, see above
```
For the reproducing, here is the output of my ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.10.0 (/Users/mike/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/mike/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.14.2 (/Users/mike/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

And my package.json:

```
{
  "name": "myproject",
  "version": "0.0.1",
  "author": "Mike Langendorf @ myproject",
  "homepage": "https://myproject.com",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "ionic:build:after": "node tools/fix_sourcemaps.js"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@auth0/angular-jwt": "^1.2.0",
    "@ionic-native/app-version": "^4.20.0",
    "@ionic-native/branch-io": "^4.20.0",
    "@ionic-native/browser-tab": "^4.20.0",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/core": "^4.20.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/dialogs": "^4.20.0",
    "@ionic-native/google-analytics": "^4.20.0",
    "@ionic-native/keyboard": "^4.20.0",
    "@ionic-native/splash-screen": "^4.20.0",
    "@ionic-native/status-bar": "^4.20.0",
    "@ionic/lab": "^1.0.20",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "@sentry/cli": "^1.37.4",
    "angular-svg-round-progressbar": "^1.2.1",
    "branch-cordova-sdk": "^3.1.5",
    "cordova-android": "7.1.2",
    "cordova-background-geolocation": "git+https://github.com/transistorsoft/cordova-background-geolocation.git#2.13.2",
    "cordova-ios": "4.5.5",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-appsee": "^2.4.15",
    "cordova-plugin-background-fetch": "^5.4.1",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-cocoalumberjack": "0.0.4",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-google-analytics": "1.8.3",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.6.0",
    "ionic-angular": "^3.9.2",
    "ionicons": "3.0.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.23",
    "rxjs": "5.5.11",
    "sentry-cordova": "^0.13.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.2",
    "tslint-ionic-rules": "0.0.21",
    "typescript": "~2.6.2",
    "xml2js": "^0.4.19"
  },
  "description": "myproject Ionic Project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": "FOO",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": "FOO"
      },
      "cordova-plugin-browsertab": {},
      "cordova-plugin-appsee": {},
      "cordova-plugin-google-analytics": {},
      "cordova-background-geolocation": {
        "LICENSE": "SECRET",
        "GOOGLE_API_VERSION": "16.0.0",
        "APPCOMPAT_VERSION": "27.1.1",
        "MOTION_USAGE_DESCRIPTION": "FOO",
        "LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION": "FOO",
        "LOCATION_ALWAYS_USAGE_DESCRIPTION": "FOO",
        "LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION": "FOO",
        "BACKGROUND_MODE_LOCATION": "<string>location</string>"
      },
      "branch-cordova-sdk": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-sqlite-storage": {},
      "sentry-cordova": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  },
  "config": {
    "ionic_generate_source_map": true
  }
}

```

Thanks in advance!

**Comment by sequoiaat** [comment]
@Mike1707  We are unable to replicate the issue you are facing. we are attaching a video of step by step of what we did. We  hope that helps you  to troubleshoot the issue . We donot think this is anythign to do with with cordova branch SDK plugin .

**Comment by Mike1707** [comment]
@sequoiaat thanks for your video. I reinstalled my global npm packages and now the commitlint works.

Unfortunately, my command `git commit -m "error check"` cannot be validated:

```
Mikes-MacBook-Pro:cc-ionic mike$ git status
On branch feature/pre-commit
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test.txt

Mikes-MacBook-Pro:cc-ionic mike$ git commit -m "error check"
husky > npm run -s precommit (node v10.14.2)

run prettier on commit
No staged files match any of provided globs.
husky > npm run -s commitmsg (node v10.14.2)

validate commit messages

⧗   input: error check
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings 
    (Need help? -> https://github.com/conventional-changelog/commitlint#what-is-commitlint )

husky > commit-msg hook failed (add --no-verify to bypass)
```

That's weird because in your video you use the same message. Do you know how this can be?

**Comment by csalmi-branch** [comment]
That error you copied in seems to be a problem with the `husky` setup, which @sequoiaat was not using in their example. @Mike1707 Can you try either uninstalling `husky` and seeing if everything works, or double checking your `husky` configurations?

**Comment by Mike1707** [comment]
I don't get it because I didn't install anything like husky. I just installed the branch library with `npm install` in my ionic project. Do you have any advices for the husky configuration? I never used anything like that.

**Comment by sequoiaat** [comment]
@Mike1707  - See if this video here helps with your problem  https://asciinema.org/a/216555

**Comment by csalmi-branch** [comment]
@Mike1707 Hopefully the video @sequoiaat just linked helps you out, since it will show you how to create a git message to avoid the issues you noted earlier.

Husky is not part of the branch package, so maybe that was installed as part of a previous step in your ionic project setup. If you don't want it, you can uninstall it with `npm uninstall husky`. If you want to learn more, you can visit their github repository at https://github.com/typicode/husky. This is not a branch product though, so that is really as far as my or @sequoiaat's help can go in regards to the configuration of husky.

**Comment by Mike1707** [comment]
This helped a lot! Now I understand the semantic git messages and I‘ll read further about it. It‘s interesting that husky is a dev dependency in the branch‘s package.json though it isn‘t part of the branch package as you said.

Thanks for your help and for me this can be closed now.
