### ISSUE TITLE
entitlements script requires `node-version-compare` to be present

### ISSUE THREAD

**Issue by ermik** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#520]
Executing `cordova prepare` hooks `before_prepare`, but the NPM dependencies from linked scripts may not be present in certain CI environments.

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/010fb85630b4045c88f2f30dbdb0a2ad1548a4d2/src/scripts/hooks/beforePrepare.js#L6

In our case CI fails due to `node-version-compare` module missing from the environment. We  pull from master:
```xml
<plugin name="branch-cordova-sdk" spec="https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git" />
```

**Comment by sequoiaat** [comment]
@ermik can you please see to install node dependencies manually and see if you still face the same issue

**Comment by ermik** [comment]
It works with node dependencies manually installed and I think it works if we pull from cordova (npm) not straight from git. Pulling straight from git also results in missing cocoapods — fixed by adding the cocoapods plugin as a dependency in cordova

**Comment by ermik** [comment]
Any fix planned?
