### ISSUE TITLE
Capacitor compatibility

### ISSUE THREAD

**Issue by leshik** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#528]
[Capacitor](https://capacitor.ionicframework.com/docs/) is the new system that will eventually replace `Cordova` in `Ionic Framework`, but can also be used standalone (which is great). Is there anything specific regarding configuring `Branch` to go along with `Capacitor` one should know?

**Comment by leshik** [comment]
So far I was unable to make it work with `Capacitor` – its `Cordova` compatibility layer can't find `Branch` header files, no matter if I add the `Branch` pod manually and undefine `BRANCH_NPM`, nor automatically. Any ideas?

**Comment by paulstelzer** [comment]
Everything that will be done automatically on Cordova, you have to add manually on Capacitor. So it would be the best to take a look at the branch android and ios documentation to see how it has to be implemented

**Comment by leshik** [comment]
@paulstelzer your PR #527 helped, but I had to change pod version to `0.25.6`, otherwise got
```
[!] CocoaPods could not find compatible versions for pod "Branch":
  In Podfile:
    Branch

    CordovaPluginsStatic (from `../capacitor-cordova-ios-plugins`) was resolved to 1.0.0-beta.11, which depends on
      Branch (~> 0.25.8)

Specs satisfying the `Branch, Branch (~> 0.25.8)` dependency were found, but they required a higher minimum deployment target.
```
Do you know why is that? At least partially it can be done automatically, I wonder why I have this versioning problem.

Another issue I have now is it doesn't compile with the error `Declaration of 'CDVPluginHandleOpenURLNotification' must be imported from module 'Cordova.CDVPlugin' before it is required` in line 24 of `AppDelegate+BranchSdk.m`. What might be the reason?

**Comment by leshik** [comment]
@paulstelzer fixed by adding `#import <Cordova/CDVPlugin.h>`, now it compiles, but complains `CDVPlugin class BranchSDK (pluginName: branchsdk) does not exist.`

**Comment by leshik** [comment]
Manually adding `BranchSDK.m` to Build Phases -> Compile Sources helps, but it still doesn't work as expected – no matter what I do it returns `{+clicked_branch_link: false, +is_first_session: false}`.

We probably need a separate plugin and/or instructions for `Capacitor`, @aaustin @ethanneff @dmitrig01.

**Comment by csalmi-branch** [comment]
@leshik We are looking into potentially supporting capacitor as a separate plugin, and I have backlogged a ticket for the team.

Are you currently blocked or having a specific issue related to the Cordova plugin?

**Comment by leshik** [comment]
@csalmi-branch We postponed deeplinks integration for now, so I'm not blocked. Thanks for considering the separate plugin, this would be helpful.

**Comment by csalmi-branch** [comment]
I'm closing this issue, since this isn't specifically a Cordova issue. We will be looking into supporting Capacitor, and will let you know if end up putting out a beta version!

For any further questions or issues, please file a ticket with our support team (support.branch.io) or open a new github issue.

**Comment by agonzalezjr** [comment]
@csalmi-branch - any updates on Capacitor support?

**Comment by justjoeyuk** [comment]
@csalmi-branch I'm also hoping for Capacitor support.

**Comment by jawkneew8** [comment]
Also hoping for Capacitor support. I received an email from support that it isn't officially supported yet, and that it was being escalated internally. Any idea on when this might be prioritized?

**Comment by Taylorsuk** [comment]
+1 for capacitor support. I'm unable to build so it's a blocker now :(

Thanks for continuing to consider Capacitor.

**Comment by mikejpeters** [comment]
I'm in the same boat so I started on a plugin: https://github.com/boundstate/capacitor-branch-deep-links

It's in the early stages, but I've tested the Android portion of the plugin works ok. If anyone can help with the iOS portion it would be greatly appreciated.

**Comment by justjoeyuk** [comment]
@csalmi-branch Please consider using and maintaining mike's plugin.

**Comment by junhohong** [comment]
+1 !

**Comment by Sebschock** [comment]
I faced the same issue. I made the Cordova plugin work on iOS (capacitor and ionic 5) by including the changes in `AppDelegate.swift` from  https://github.com/BranchMetrics/capacitor-branch-deep-links (I did not install capacitor-branch-deep-links).

**Comment by abarax** [comment]
> I faced the same issue. I made the Cordova plugin work on iOS (capacitor and ionic 5) by including the changes in `AppDelegate.swift` from https://github.com/BranchMetrics/capacitor-branch-deep-links (I did not install capacitor-branch-deep-links).

Where did you set up the <branch-config> to make this work ?
