### ISSUE TITLE
How to add Google Advertising ID

### ISSUE THREAD

**Issue by Mike1707** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#544]
I read in the [documentation](https://docs.branch.io/pages/apps/android-launch/) that it's recommended to add the IDFA for Apple and GAID for Google. For the IDFA, I can see in Xcode the AdSupport.framework is already linked with my project. Nevertheless, I can't find any references for the GAID respectively the play-services-ads.

How can I enable the GAID in my project because in my `build.gradle` file are no other play-services linked, but in my `project.properties`?

Since I use ionic, you can find my ionic info output down below.

Thanks in advance!
Mike

```
Ionic:

   ionic (Ionic CLI)  : 4.7.1 (/Users/mike/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/mike/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.14.2 (/Users/mike/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by sequoiaat** [comment]
@Mike1707 Please refer the relevant reference in the Branch documentation at
https://github.com/BranchMetrics/android-branch-deep-linking#proguard-settings-for-leveraging-branchs-pooled-matching

A more complete reference on GAID can be found at 
http://www.androiddocs.com/google/play-services/id.html
https://developers.google.com/android/guides/setup
https://developervisits.wordpress.com/2016/09/09/android-2/

Please let us know if helps.

**Comment by sequoiaat** [comment]
@Mike1707  Please let us know if the above  links helped and if we can close this issue .

**Comment by Mike1707** [comment]
Hey @sequoiaat! Thanks for your reply. Unfortunately, I was not able to test this yet but I guess the links will help. You can close this issue and in the worst case, I will ask you again!
