### ISSUE TITLE
Deeplink data logged in xcode logs, not in initSession

### ISSUE THREAD

**Issue by ankitjainOfficial** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#545]
Deeplink is working perfectly, but the data is not passed to the app. However I can see the data in xcode logs.

Here is my code (Angular 5):

```
  ngOnInit () {
    this.platform.ready().then(this.branchInit.bind(this));
    this.platform.resume.subscribe(this.branchInit.bind(this));
  }


  private branchInit () {
    if (this.platform.is('cordova')) {
      console.log('trying branch init') // This is being logged
      Branch.initSession(data => {
        console.log(data) // Nothing here
        if (data.scope && data.code) {
          ...
        }
      });
    }
  }
```

And here are Xcode logs:

```
BNCNetworkService.m(232) Debug: Network start operation https://api.branch.io/v1/open.
2019-01-28 18:22:54.221110+0530 %APPNAME%[9311:121169] [branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api.branch.io/v1/open 0.373s. Status 200 error (null).
{"session_id":"618415511147036050","identity_id":"615101230846950563","link":"https://fleb.app.link?%24identity_id=615101230846950563","data":"{\"$marketing_title\":\"title\",\"code\":\"ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"~creation_source\":1,\"+click_timestamp\":1548679974,\"~feature\":\"marketing\",\"+match_guaranteed\":true,\"~marketing\":true,\"+clicked_branch_link\":true,\"scope\":\"read_write\",\"$one_time_use\":false,\"~id\":511810298395717526,\"+is_first_session\":false,\"~referring_link\":\"https://fleb.app.link/O3ZuPt9fYL?state=30&scope=read_write&code=ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"state\":\"30\"}","device_fingerprint_id":"615101230809166363"}.
2019-01-28 18:22:54.221222+0530 %APPNAME%[9311:121169] [branch.io] BNCServerInterface.m(818) Debug: Server returned: Status: 200; Data: {
    data = "{\"$marketing_title\":\"title\",\"code\":\"ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"~creation_source\":1,\"+click_timestamp\":1548679974,\"~feature\":\"marketing\",\"+match_guaranteed\":true,\"~marketing\":true,\"+clicked_branch_link\":true,\"scope\":\"read_write\",\"$one_time_use\":false,\"~id\":511810298395717526,\"+is_first_session\":false,\"~referring_link\":\"https://fleb.app.link/O3ZuPt9fYL?state=30&scope=read_write&code=ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"state\":\"30\"}";
2019-01-28 18:22:54.236527+0530 %APPNAME%[9311:121168] [branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api.branch.io/v1/open 0.416s. Status 200 error (null).
{"session_id":"618415511206028533","identity_id":"615101230846950563","link":"https://fleb.app.link?%24identity_id=615101230846950563","data":"{\"$marketing_title\":\"title\",\"code\":\"ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"~creation_source\":1,\"+click_timestamp\":1548679974,\"~feature\":\"marketing\",\"+match_guaranteed\":true,\"~marketing\":true,\"+clicked_branch_link\":true,\"scope\":\"read_write\",\"$one_time_use\":false,\"~id\":511810298395717526,\"+is_first_session\":false,\"~referring_link\":\"https://fleb.app.link/O3ZuPt9fYL?state=30&scope=read_write&code=ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"state\":\"30\"}","device_fingerprint_id":"615101230809166363"}.
2019-01-28 18:22:54.236660+0530 %APPNAME%[9311:121168] [branch.io] BNCServerInterface.m(818) Debug: Server returned: Status: 200; Data: {
    data = "{\"$marketing_title\":\"title\",\"code\":\"ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"~creation_source\":1,\"+click_timestamp\":1548679974,\"~feature\":\"marketing\",\"+match_guaranteed\":true,\"~marketing\":true,\"+clicked_branch_link\":true,\"scope\":\"read_write\",\"$one_time_use\":false,\"~id\":511810298395717526,\"+is_first_session\":false,\"~referring_link\":\"https://fleb.app.link/O3ZuPt9fYL?state=30&scope=read_write&code=ac_EQQSuh1StBljCI9pj6lNRgmI8ma9giXA\",\"state\":\"30\"}";
```

Please let me know, if more details are required. Thanks,

**Comment by sequoiaat** [comment]
@ankitjainOfficial  Is this issue in the latest version of Cordova ? there was a similar issue reported earlier but it was solved in cordova version 3.1.0 https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/502

**Comment by sequoiaat** [comment]
@ankitjainOfficial  - could you please share the other plugins as well . Sometimes these plugins could cause compatibility issues and some of them are already known issues.  Also our assumption is after the upgrade also you still have the same issue

**Comment by ankitjainOfficial** [comment]
@sequoiaat Here are the plugins:

```
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 3.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sms-plugin 0.1.13 "Cordova SMS Plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

**Comment by sequoiaat** [comment]
@ankitjainOfficial  we will revert back on this after some investigation at our end

**Comment by ankitjainOfficial** [comment]
@sequoiaat Did you find anything? I don't want to be a pest, but my app experience is getting hampered. Sorry. Any work around also, will be greatly appreciable, Thanks.

**Comment by sequoiaat** [comment]
@ankitjainOfficial  - We have not been able to reproduce this without the plugins. To help us narrow down can you please clarify the following queries- 

Can you please confirm the deep link data is being queued up?
* Is the data is not coming in on first app open, or does it come in on the second app open?
* Is it happening for all your deep links or only one?
* Have you seen any behavior when the app is background  or when it terminated or it happens in both cases ? 

Any further steps  you may have followed to help us  replicate the issue.

**Comment by ankitjainOfficial** [comment]
* Is the data is not coming in on first app open, or does it come in on the second app open?
- The data is not processed, at any time. I've placed my code on both app start and resume.
* Is it happening for all your deep links or only one?
- I only have one deeplink.
* Have you seen any behavior when the app is background  or when it terminated or it happens in both cases ?
- I did not get this one. Can you explain a bit, with what do you mean by **behavior**?

One more thing, I found today, while debugging is that, the data is not received in both Android and iOS. Also, if I call the promise function `Branch.getLatestReferringParams` from console, it returns the data. But, If I call it in app resume or load, it returns false.

Is it some race condition, I am hitting?

**Comment by sequoiaat** [comment]
@ankitjainOfficial  It is possible that its a race condition however we have not been able to replicate this at our end yet  to say this definatively . You may have gone through this, but if not please review these links - https://support.branch.io/support/solutions/articles/6000192812-link-data-not-passing-to-ios-app-on-link-click 
https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#read-deep-link

we were looking only at iOS but will look at Android.  Are you seeing this issue on real device or in emulator ?

**Comment by ankitjainOfficial** [comment]
@sequoiaat I found the error. initSession function was a promise, and I had implemented as a callback. Looking back, I had upgraded from 2.6 to 3.1, and the initSession was changed, sometime between that. Changing implementation from callback to promise, was just it took to resolve the issue. Thanks. 

:)
