### ISSUE TITLE
ionic cordova plugin add branch-cordova-sdk fails

### ISSUE THREAD

**Issue by leonardomontes** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#548]
ionic cordova plugin add branch-cordova-sdk
Fetching plugin "branch-cordova-sdk" via npm
Installing "branch-cordova-sdk" for ios
BRANCH SDK: Installing node dependency plist
Failed to install 'branch-cordova-sdk':Error: Cannot find module 'plist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

Ionic:

   ionic (Ionic CLI)  : 4.10.2 (/Users/leo/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : ios 4.3.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/leo/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.4 (/Users/leo/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by sequoiaat** [comment]
@leonardomontes Can you please update to latest version of cordovan and see if the issue goes away ? 
Also  another possibility is that Cannot find module 'xml2js; can happen if you are trying to run multiple Cordova commands at once because the async calls within the Branch  install process will not finish, and the dependencies to not install. Here is a testing guide also- https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios

**Comment by leonardomontes** [comment]
Updated to the following and it is working now, maybe just specify that the plugin doesn't work with node 8.x. Thanks for your quick reply!

Ionic:

   ionic (Ionic CLI)  : 4.10.2 (/Users/leo/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/leo/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.1 (/Users/leo/.nvm/versions/node/v10.15.1/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by sequoiaat** [comment]
It’s a known issue in Cordova older versions. We will go ahead and close this

**Comment by zarko-tg** [comment]
Any chance of fixing this for Cordova 6.5.0 if not too much trouble?

**Comment by zarko-tg** [comment]
We got the problem even while using cordova (CLI) 8.1.0.

Apple macOS: installed darwin
Xcode: installed 10.1
ios-deploy: installed 1.9.4
CocoaPods: installed 1.6.1
Node.js: 10.15.3 LTS

**Comment by zarko-tg** [comment]
Feel free: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/560

**Comment by tryhardest** [comment]
@sequoiaat wondering why this was closed. @zarko-tg have you (or anyone) got even an old Branch plugin to work with latest CordovaAndroid 8.1.1, let alone the latest plugin release?
