### ISSUE TITLE
Branch deeplinks shows false value in alert

### ISSUE THREAD

**Issue by liyansanath** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#549]
I am experience an issue when the deep link is clicked and the init session is fired.After clicking deep link it shows a alert, +clicked_branch_link and +is_first_session (both are false). 
Corvoda Branch SDK version:- 3.1.5 
iOS 10.0 and iOS 11.2. 
The source code is the following:

`this.branchio.initSession().then(
data => {
if (data["+clicked_branch_link"]) {
console.log(data)
}
}
}`

**Comment by sequoiaat** [comment]
@liyansanath  we are trying to reproduce this. Is there any other information that you can share on your setup which may help us reproduce this faster .

**Comment by liyansanath** [comment]
*ionic (Ionic CLI) : 4.5.0
*Ionic Framework : ionic angular 3.9.2
*@ionic/app-scripts:3.2.1

*System:
*Android SDK Tools: 26.1.1
*ios-deploy :1.9.2
*NodeJS : v7.10.0
*npm : 5.4.2
*OS : macOS Sierra
*Xcode : XCode 10.1

`cordova plugins version`
* branch-cordova-sdk 3.1.5

**Comment by sequoiaat** [comment]
@liyansanath   Are you using any plugins by any chance ?   One possibility we see is that there is a plugin which may be creating this issue . Please confirm if there are any plugins ?

**Comment by liyansanath** [comment]
@sequoiaat ; below the list of plugins used -
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-universal-links-plugin ^1.2.1
cordova-plugin-file 5.0.0 "File"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sms-plugin 0.1.13 "Cordova SMS Plugin"

**Comment by sequoiaat** [comment]
@liyansanath  we see that there is a plugin which is known to not work with branch -  cordova-universal-links-plugin ^1.2.1 . Can you please try without that and see if you still face the same issue ? then we will try to check which other plugin may be conflicting.

**Comment by liyansanath** [comment]
@sequoiaat ; thanks for point out, universal-links-plugin was clashing with branch plugin. I'm closing this ticket.
